### ISSUE TITLE
Provided script tag is invalid

### ISSUE THREAD

**Issue by shreve** [mikecao/umami#10]
The provided self-closing script tag is invalid HTML. 

    <script async defer data-website-id="[red]" src="[red]/umami.js" />

I put this in the head element of my HTML and rendering of my entire page broke. The browser interpreted it as only an open tag, so the remaining document was script.

Run through the W3C validator, it gives the following message:

    Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.

**Comment by PabloSzx** [comment]
I think it's a self-closing tag due to JSX usage, where it being self-closed tag is completely valid, the solution if you are just adding it to plain html is to 
```html
<script async defer data-website-id="[red]" src="[red]/umami.js"></script>
```

**Comment by mikecao** [comment]
I can update it to make sure it's not self-closing. Thanks for catching it.

**Comment by nodesocket** [comment]
Small fix, but would be great to get pushed out.

**Comment by mikecao** [comment]
Should be fixed in latest commit.
