### ISSUE TITLE
CORS issue on Vercel

### ISSUE THREAD

**Issue by martin-ro** [mikecao/umami#100]
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://umami-q8g0lml5u.vercel.app/api/collect. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Any idea how to fix that?

**Comment by mikecao** [comment]
The collect endpoint should be sending the correct CORS header. I am running on Vercel now. Are you trying to go from `https` to `http` maybe?

**Comment by martin-ro** [comment]
I have `https` on both ends. I have fixed that now by adding a `vercel.json` config to the deployment as per their documentation https://vercel.com/knowledge/how-to-enable-cors#enabling-cors-using-vercel.json

**Comment by vvo** [comment]
Same issue, I guess this could be a change in Next.js latest version

**Comment by martin-ro** [comment]
This error cam back. I had to add

```
async headers() {
    return [
      {
        // mathching all API routes
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Credentials", value: "true" },
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
          { key: "Access-Control-Allow-Headers", value: "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" },
        ]
      }
    ]
  }
```

to `next.config.js`

**Comment by surjithctly** [comment]
BREAKING: Same issue. Analytics stopped tracking Since many days because of this CORS Error. 

Need Immediate FIX.

**Comment by hugomd** [comment]
@surjithctly have you tried the fix listed above?

**Comment by surjithctly** [comment]
@hugomd Yes. Tried, Now instead of CORS Error, I get `502` Error for fetch `api/collect` 

Response was: `{"error": {"code": "502", "message": "An error occurred with this application."}}`

**Comment by hugomd** [comment]
@surjithctly can you post the logs of the Vercel app please?

**Comment by surjithctly** [comment]
Here you go:

```
[POST] /api/collect
18:37:34:09
2020-09-22T13:07:34.637Z	90aa1b37-891e-4278-9371-ed2accda4a24	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open '/var/task/node_modules/geolite2-redist/dbs-tmp/GeoLite2-City.mmdb'","code":"ENOENT","errno":-2,"syscall":"open","path":"/var/task/node_modules/geolite2-redist/dbs-tmp/GeoLite2-City.mmdb","stack":["Error: ENOENT: no such file or directory, open '/var/task/node_modules/geolite2-redist/dbs-tmp/GeoLite2-City.mmdb'"]}
Unknown application error occurred
```

**Comment by mikecao** [comment]
@surjithctly Try redeploying. That error is because one of the node packages needs to download files, but I don't think Vercel allows file system access. When you re-deploy it will do it during the install process.

**Comment by surjithctly** [comment]
@hugomd Thanks. it works now.

**Comment by ShubhamVerma1811** [comment]
> 
> 
> This error cam back. I had to add
> 
> ```
> async headers() {
>     return [
>       {
>         // mathching all API routes
>         source: "/api/:path*",
>         headers: [
>           { key: "Access-Control-Allow-Credentials", value: "true" },
>           { key: "Access-Control-Allow-Origin", value: "*" },
>           { key: "Access-Control-Allow-Methods", value: "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
>           { key: "Access-Control-Allow-Headers", value: "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" },
>         ]
>       }
>     ]
>   }
> ```
> 
> to `next.config.js`



> 
> 
> @hugomd Thanks. it works now.

What did you to fix it?

**Comment by surjithctly** [comment]
@ShubhamVerma1811 Add the code in my next congig: https://github.com/surjithctly/web3analytics/blob/master/next.config.js#L15-L28

Then manually re-deployed from Vercel Dashboard.

**Comment by ShubhamVerma1811** [comment]
> @ShubhamVerma1811 Added the code in my next config: https://github.com/surjithctly/web3analytics/blob/master/next.config.js#L15-L28
> 
> Then manually re-deployed from Vercel Dashboard.

It works, Thanks!

**Comment by surjithctly** [comment]
@hugomd @ShubhamVerma1811 

Seems, re-deploying not an option because the error seems re-appeared now. Error is same as above. 

Need some permanent solution for this: @mikecao

**Comment by mikecao** [comment]
@surjithctly Can you start a new issue with the problem? We shouldn't be using this unrelated thread. Closing this.

**Comment by ShubhamVerma1811** [comment]
> 
> 
> @surjithctly Can you start a new issue with the problem? We shouldn't be using this unrelated thread. Closing this.

#229 I started the new issue here.
