### ISSUE TITLE
Script Name Variable Won't Apply

### ISSUE THREAD

**Issue by AFilthyLeaf** [mikecao/umami#1000]
I am running this on Heroku, I added `TRACKER_SCRIPT_NAME` to my config vars, with the value `viewcount` and restarted all dyno's. Even after the restart the script doesn't work at the `viewcount` location.

**Comment by mikecao** [comment]
In the current version you need to rebuild the app for it to apply, sorry. In the next release it should work at runtime as intended.

**Comment by mikecao** [comment]
Fixed in v1.27.0
