### ISSUE TITLE
clic on /page will add /page filter but doesn't render related pageview chart

### ISSUE THREAD

**Issue by creharmony** [mikecao/umami#1001]
when I clic on a given page (from `Pages` table list), this add a new filter to umami view with page path (cf image). 
Exemple under `/about` page. That's fine.

but I'm wondering why I didn't see related visitor/page view in graph ?
![image](https://user-images.githubusercontent.com/74717011/156165260-d1001061-f416-4554-b06c-d2ebba7dab64.png)

(and seems that page filter has no impact on the rest of the page : per browser, per os...)

**Comment by mikecao** [comment]
Maybe you didn't have any view on `/about` in the past 24 hours?

**Comment by creharmony** [comment]
Sorry for the delay I missed your question
first I produce a visit on some page of my test env
![image](https://user-images.githubusercontent.com/74717011/162580034-55c309ac-168f-4e6d-8a73-bce6d01d11c8.png)

A) I was able to see it in timeline
![image](https://user-images.githubusercontent.com/74717011/162580050-618f3c68-6b1e-4fb6-96fb-5c7cc11783e6.png)

B) after filter on `/cookies` : I see the filter, but nothin in timeline, I suspect a bug because that's so confusing
![image](https://user-images.githubusercontent.com/74717011/162580065-1ff5f49d-4182-478d-8e9e-560805a783e1.png)
![image](https://user-images.githubusercontent.com/74717011/162580096-621a7b70-f74b-469b-beb4-94867044be42.png)
