### ISSUE TITLE
error: Your local changes to the following files would be overwritten by merge: yarn.lock

### ISSUE THREAD

**Issue by cirrusflyer** [mikecao/umami#1009]
Currently running v1.26.0 and trying to upgrade to v1.27.0 by following instructions here:  https://umami.is/docs/updates

Getting this error when running "git pull":

error: Your local changes to the following files would be overwritten by merge:
	yarn.lock
Please commit your changes or stash them before you merge.
Aborting

**Comment by mikecao** [comment]
This is related to git. You've made changes toy our yarn.lock. You can do `git stash` to stash your local changes or `git reset --hard HEAD` to remove your changes.

**Comment by cirrusflyer** [comment]
The reset worked, but I never touched the yarn.lock file.  This happened the last upgrade as well.  What would cause this?

**Comment by mikecao** [comment]
It's possible yarn made changes to the lockfile during the last install. If you want to be sure no changes are made you can use `yarn install --frozen-lockfile`.
