### ISSUE TITLE
Failed at the prisma@3.9.2 preinstall script

### ISSUE THREAD

**Issue by jannik0402** [mikecao/umami#1010]
Hey guys,

while installing umami on two completely different servers (both Ubuntu 20.04.4) npm stops with Error
`npm ERR! code ELIFECYCLE`
`npm ERR!" errno 1`
`npm ERR! prisma@3.9.2 preinstall: 'node scripts/preinstall-entry.js'`
`mpm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the prisma@3.9.2 preinstall script`

In the log files is written

`verbose stack Error: [prisma@3.9.2](mailto:prisma@3.9.2) preinstall: 'node scripts/preinstall-entry.js'`
`253 verbose stack Exit status 1`
`253 verbose stack     at EventEmitter.<anonymous>`
`(/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)`
`253 verbose stack     at EventEmitter.emit (events.js:198:13)`
`253 verbose stack     at ChildProcess.<anonymous>`
`(/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)`
`253 verbose stack     at ChildProcess.emit (events.js:198:13)`
`253 verbose stack     at maybeClose (internal/child_process.js:982:16)`
`253 verbose stack     at Process.ChildProcess._handle.onexit`
`(internal/child_process.js:259:5)`
`254 verbose pkgid [prisma@3.9.2](mailto:prisma@3.9.2)`
`255 verbose cwd /var/www/html/umami`
`256 verbose Linux 5.13.0-30-generic`
`257 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"`
`258 verbose node v10.19.0`
`259 verbose npm  v6.14.4 `

Because of this Error on two completly different servers, i think its a problem with the package. Maybe someone knows a solution?
Greetings!

**Comment by mikecao** [comment]
This is your problem: `node v10.19.0`. You need at least node 12.

**Comment by jannik0402** [comment]
Sorry, my mistake - was the wrong logfile. Here the one which schould be relevant with Node.js 17.4
Same Mistake also with 16.1 and 12.22.10:

6873 verbose stack Error: command failed
6873 verbose stack     at ChildProcess.<anonymous> (/opt/plesk/node/17/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
6873 verbose stack     at ChildProcess.emit (node:events:527:28)
6873 verbose stack     at maybeClose (node:internal/child_process:1090:16)
6873 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
6873 verbose stack     at Socket.emit (node:events:527:28)
6873 verbose stack     at Pipe.<anonymous> (node:net:688:12)
6874 verbose pkgid prisma@3.9.2
6875 verbose cwd /var/www/vhosts/**********/**********
6876 verbose Linux 5.4.0
6877 verbose argv "/opt/plesk/node/17/bin/node" "/opt/plesk/node/17/bin/npm" "install"
6878 verbose node v17.6.0
6879 verbose npm  v8.5.1
6880 error code 127
6881 error path /var/www/vhosts/**********/**********/node_modules/prisma
6882 error command failed
6883 error command sh -c node scripts/preinstall-entry.js
6884 error sh: 1: node: not found
6885 verbose exit 127
6886 timing npm Completed in 164562ms
6887 verbose unfinished npm timer reify 1646680312798
6888 verbose unfinished npm timer reify:build 1646680470134
6889 verbose unfinished npm timer build 1646680470142
6890 verbose unfinished npm timer build:deps 1646680470144
6891 verbose unfinished npm timer build:run:preinstall 1646680470202
6892 verbose unfinished npm timer build:run:preinstall:node_modules/prisma 1646680470203
6893 verbose code 127

**Comment by mikecao** [comment]
`error sh: 1: node: not found` seems to indicate the script can't find node. You'll probably have to symlink it to common location like `/usr/bin/node`.

**Comment by mejje** [comment]
Same issue here, unable to npm install in hosted Plesk applications, seems unique to prisma.
