### ISSUE TITLE
Question: Chart by event type?

### ISSUE THREAD

**Issue by lookingdown** [mikecao/umami#1014]
Thanks for Umami...
Is it possible to update event chart when selected event type is changed OR a chart for each event type..
I have  couple of events.. Product Views (To know which products generates most interest), 
Checkout (With info from which Product was viewed when clicking checkout),
Abandoned Cart with value and exit point (completed or not address input, recurring customer etcetera)
(and a few more like customer profile active (logged in user ))

With chart for each it would be easy to see most looked at products, which products generate most checkout impulses etcetera

Either update the chart when selected event type changes via the dropdown OR optionally charts for each event type (in settings?)..
Thanks..

**Comment by mikecao** [comment]
This is being tracked in #494
