### ISSUE TITLE
Does not start umami

### ISSUE THREAD

**Issue by deniuscoder** [mikecao/umami#1015]
First error during installation:
"error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc"
corrected by replacing babel
after assembly, I can not log in with a username and password
"PrismaClientInitializationError: Authentication failed against database server at `localhost`, the provided database credentials for `umamiadmin` are not valid."
login and password are correct, privileges to the database are all set, what could be the problem?

**Comment by deniuscoder** [comment]
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /root/umami/.env
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
PrismaClientInitializationError: Authentication failed against database server at `localhost`, the provided database credentials for `umamiadmin` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
    at cb (/root/umami/node_modules/@prisma/client/runtime/index.js:38709:17)
    at async PrismaClient._request (/root/umami/node_modules/@prisma/client/runtime/index.js:40859:18)
    at async __WEBPACK_DEFAULT_EXPORT__ (/root/umami/.next/server/pages/api/auth/login.js:90:19)
    at async Object.apiResolver (/root/umami/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async NextNodeServer.runApi (/root/umami/node_modules/next/dist/server/next-server.js:386:9)
    at async Object.fn (/root/umami/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/root/umami/node_modules/next/dist/server/router.js:228:32)
    at async NextNodeServer.run (/root/umami/node_modules/next/dist/server/base-server.js:600:29)
    at async NextNodeServer.handleRequest (/root/umami/node_modules/next/dist/server/base-server.js:307:20) {
  clientVersion: '3.9.2',
  errorCode: undefined
}

**Comment by deniuscoder** [comment]
CentOS Linux release 7.9.2009 (Core)

**Comment by erdmenchen** [comment]
I tried your fix with the fallback to babel, but it did not work for me. 
I had to `npm install next@canary` in order to get it working with SWC again.
After that, I had no issue building and running it.

(I updated umami from version 1.23 to the latest version 1.27)

**Comment by deniuscoder** [comment]
I did so, like the assembly passed, but now another error
"400 Bad Request" 
there is nothing in the logs on the server side
version umami@1.27.0 start
"/api/auth/login" 400 Bad Request

**Comment by mikecao** [comment]
@deniuscoder Can you post what request you're making?

**Comment by deniuscoder** [comment]
Autorization

**Comment by mikecao** [comment]
I mean how are you making the request? what parameters? etc

**Comment by mikecao** [comment]
I assume you're making the call through the browser right? The only way to get a bad request is if you don't enter a username or password in the body of the request.

**Comment by deniuscoder** [comment]
After build here is the result https://umami.lizvan.ru/
you need to enter a username and password, try

**Comment by mikecao** [comment]
The response headers from your server look odd:
```
date: Tue, 08 Mar 2022 17:34:56 GMT
server: nginx
```
For example here are mine from Vercel:
```
cache-control: public, max-age=0, must-revalidate
content-length: 507
content-type: application/json; charset=utf-8
date: Tue, 08 Mar 2022 17:33:17 GMT
etag: "1fb-FtvCkLUpN2QtYKytEFdzlRT7T98w"
server: Vercel
strict-transport-security: max-age=63072000
x-matched-path: /api/auth/login
x-vercel-cache: MISS
x-vercel-id: sfo1::sfo1::mv5h8-164684757974766-65f0eefbe26778
```
So it seems like your nginx is not passing along the credentials to umami.
