### ISSUE TITLE
Map labeling suggestion

### ISSUE THREAD

**Issue by NianwenDan** [mikecao/umami#1019]
Hello umami developer,

The umami is a great open-source project. It is lightweight and easy to install. The documentation is detained and good for beginners. However, I find a map problem that may cause issues in the future.

I am currently running umami v1.27.0, and I find out Taiwan is separated from China. I knew this is a controversial topic all the time. However, I hope you could take notice of it.

To fix that, the easiest way to fix it is to add a label near Taiwan, such as **Taiwan(China)**. So, you don't have to change the source code too much.

Thanks for bringing this awesome project to the world.

**Comment by mikecao** [comment]
umami uses external data sources for maps and country names. You can file an issue with https://github.com/zcreativelabs/react-simple-maps if you want a label change.

**Comment by NianwenDan** [comment]
Thank you!
