### ISSUE TITLE
'Incorrect username/password.' when first login

### ISSUE THREAD

**Issue by DreamOfIce** [mikecao/umami#1021]
when I first login to umami,using the user `admin` and password `umami`,it prompts:
![picture](https://user-images.githubusercontent.com/80821706/157688916-43432b9f-76ce-4e16-b35c-d550624408f5.png)
I tried to reset the database,but it still occured
What should I do?

I host it with my own server with node16,nginx and pm2.
I tried to use the dev mode,but there is nothing error.

**Comment by DreamOfIce** [comment]
emm... the default user/password is umami/umami,Why?

**Comment by mikecao** [comment]
Did you add the user `umami`? The only account in the database at the beginning is `admin`.

**Comment by DreamOfIce** [comment]
> 你添加用户了`umami`吗？开始时数据库中的唯一帐户是`admin`.

No,I did nothing,but the default user is admin

**Comment by DreamOfIce** [comment]
I found that the admin in my SQL file seems to have become umami. I should have made a mistake by accident. Thank you for your help

**Comment by DrBash** [comment]
Thank you guys, I just set it up with postgres. I added a user and everything, which didn't do the trick. Based on your comments, I tried "admin" as the user and "umami" as the password, which worked.

Thanks.
