### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by jakobbouchard** [mikecao/umami#1023]
I've recently updated to 1.27 and since then (I think, possibly before), I've been getting too many redirect errors when trying to load it. If you want to try loading my deployment, [here it is](https://umami-one-pi.vercel.app)

I tried deleting the Vercel project and recreating it, but it didn't help. I'll be trying to make a new database.

**Comment by jakobbouchard** [comment]
Interestingly, changing the database didn't help, but putting a new hash salt fixed the issue. Still kinda odd to me. Maybe I missed something in the release notes.

**Comment by mikecao** [comment]
@jakobbouchard do you recall which url it was trying to redirect to? The hash_salt affects the login token, so basically changing it forces you to log out.

**Comment by jakobbouchard** [comment]
It was redirecting to `/`. However, I think it actually might've been `FORCE_SSL` instead, as the problem reoccured when I added it back a couple of minutes ago. FWIW, I deploy on Vercel, which uses the `.app` domain, and my own domain uses `.dev`. Both of these are on the HSTS preload list, so it might be bugging out?

**Comment by jakobbouchard** [comment]
[This deployment](https://umami-pugf5k6qn-jakobbouchard.vercel.app/) has `FORCE_SSL` enabled. Running `curl -s -L -D - https://umami-pugf5k6qn-jakobbouchard.vercel.app -o /dev/null` in my terminal shows a whole bunch of redirects.

**Comment by mikecao** [comment]
Thanks, that's very helpful.

**Comment by jm4rsh4ll** [comment]
I also have the same issue with the last version. My setup on Heroku. Temporary solved by removing `FORCE_SSL`.

I don't have statistic for last days (after update) and saw that web part tried to load `/api/realtime/update` infinite number of times.

**Comment by KonstantinReido** [comment]
I also have the same issue with the last version. My setup on Heroku. Temporary solved by removing FORCE_SSL.

I don't have statistics for the last days (after the update) and saw that web part tried to load `/api/realtime/update` an infinite number of times.

**Comment by KonstantinReido** [comment]
@mikecao I updated today on 1.28.0 and still have the issue with `FORCE_SSL`.

Now, an infinite loop happens when the system tries to load `method=GET path="/dashboard"`

**Comment by joelgoodman** [comment]
Confirmed to happen on Railway, too.

**Comment by mikecao** [comment]
Ughhh this `FORCE_SSL` is such a pain. I might just remove it. For some reason Next.js is not returning the right info.

**Comment by jakobbouchard** [comment]
Haven't checked the implementation, but could it be possible for the variable to enable HSTS instead? I.E by setting the header. That way I think it wouldn't cause the redirect issue.
