### ISSUE TITLE
WebsiteId = undefined

### ISSUE THREAD

**Issue by WasyfAli** [mikecao/umami#1024]
When hitting realtime website id is coming Nan/undefined

**Comment by mikecao** [comment]
Going to need more information than that.

**Comment by WasyfAli** [comment]
When there is nno user on the website this api is  giving internal  server  error as there is no real user
GET http://localhost:3000/api/website/undefined/active 500 (Internal Server Error)
![image](https://user-images.githubusercontent.com/46135061/158266581-f0a41d6f-e1e4-45c9-8f29-24b745c05842.png)

**Comment by youssefm** [comment]
I get this too. Just try to load the realtime dashboard in a browser and you'll see a 500 in the browser console:

![image](https://user-images.githubusercontent.com/1513212/159201534-12eab5f4-da65-4c97-a671-96c3911a2271.png)

**Comment by mikecao** [comment]
Should be fixed in v1.29.0.
