### ISSUE TITLE
When hitting a 404 page, the "home" link points to umami.is not my site

### ISSUE THREAD

**Issue by christopherpickering** [mikecao/umami#1028]
When hitting a 404 url, for example https://app.umami.is/asdf, the home link:
![image](https://user-images.githubusercontent.com/17788706/158656865-f2b9def2-93ae-4101-916a-d876e1983a9f.png)

points to `umami.is` instead of `app.umami.is`. 

Or if my site is `analytics.atlas.bi`, the 404 "home" url still points to `umami.is` instead of `analytics.atlas.bi`.

Is it possible to point the home url to my home?

**Comment by mikecao** [comment]
Yea, that's a bug.
