### ISSUE TITLE
[Error] dotenv prisma generate fails on RPi4

### ISSUE THREAD

**Issue by smorrin28** [mikecao/umami#103]
When  I try to build the app, it always fails when it runs "dotenv prisma genrate". If I try to run the command on my own, I get the following error: "Error: No such command "prisma"". I have prisma installed, but somehow it doesnt work. Here's my npm log: 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-db-client'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild-db-client', 'build-db-client', 'postbuild-db-client' ]
5 info lifecycle umami@0.21.0~prebuild-db-client: umami@0.21.0
6 info lifecycle umami@0.21.0~build-db-client: umami@0.21.0
7 verbose lifecycle umami@0.21.0~build-db-client: unsafe-perm in lifecycle true
8 verbose lifecycle umami@0.21.0~build-db-client: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/umami/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/umami/node_modules/.bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle umami@0.21.0~build-db-client: CWD: /home/ubuntu/umami
10 silly lifecycle umami@0.21.0~build-db-client: Args: [ '-c', 'dotenv prisma generate' ]
11 silly lifecycle umami@0.21.0~build-db-client: Returned: code: 1  signal: null
12 info lifecycle umami@0.21.0~build-db-client: Failed to exec build-db-client script
13 verbose stack Error: umami@0.21.0 build-db-client: `dotenv prisma generate`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid umami@0.21.0
15 verbose cwd /home/ubuntu/umami
16 verbose Linux 5.4.0-1016-raspi
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "build-db-client"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error umami@0.21.0 build-db-client: `dotenv prisma generate`
22 error Exit status 1
23 error Failed at the umami@0.21.0 build-db-client script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mikecao** [comment]
What does your `npm install` look like?

**Comment by smorrin28** [comment]
It has some deprecation warnings, but I manged to fix the issue by just provisioning the database on my Raspberry Pi & using Vercel for everything else.
