### ISSUE TITLE
Not friendly as Google Analytics

### ISSUE THREAD

**Issue by realtouseef** [mikecao/umami#1032]
When I first came across Umami, I loved the idea and overall, but as I scrolled down the Readme, I found out it requires you to have a database, which I don't like. 

On the other hand, the Google Analytics doesn't require you to have a database, you just have to add their `tag manager` into your site and you're all setup. I'd love to use umami, but I don't want to go through the DB process and I am sure there will be a lot of people who aren't that technical. No offense to umami.

If there's a way to make it as simple as the GA then Im more than happy to switch to umami. And Im sure that others will switch to umami as well. I just want to help you make umami better.

Thanks

**Comment by mikecao** [comment]
The reason Google Analytics is free and requires less setup is because they sell your data. Umami is meant to be self-hosted. Are you interested in a paid hosting solution for umami?

**Comment by ruibaby** [comment]
@mikecao Maybe a hosting service like plausible?

**Comment by bernd-wechner** [comment]
> I found out it requires you to have a database, which I don't like.

Ironically, what you don't like others love. I am with Umami, specifically **because** it stores its data in my database. I want to own our data not sell it some free hosing provider. What is free, in terms of data storage, is essentially sold to market analysts and advertisers.
