### ISSUE TITLE
"XML Parsing Error" in v1.28

### ISSUE THREAD

**Issue by cjdenio** [mikecao/umami#1035]
After upgrading to v1.28, all of my sites started throwing the following error in the console:

<img width="402" alt="Screen Shot 2022-03-18 at 4 32 18 PM" src="https://user-images.githubusercontent.com/34525547/159079220-bab4ab9f-ccd0-4e39-aa85-b8553ead5f5a.png">

This is also happening on https://umami.is.

<img width="319" alt="Screen Shot 2022-03-18 at 4 32 26 PM" src="https://user-images.githubusercontent.com/34525547/159079233-bc854383-6a68-4e98-b03f-bc11031c05d5.png">

**Comment by mikecao** [comment]
Looks like this only happens in Firefox. It something to do with headers according to this, https://stackoverflow.com/questions/51000009/i-keep-getting-this-error-xml-parsing-error-syntax-error-but-still-the-website
The code still runs fine so no need to worry. I'll still fix it in the next release.

**Comment by cjdenio** [comment]
Ah, thanks!
