### ISSUE TITLE
Docker versioning schema

### ISSUE THREAD

**Issue by quickstar** [mikecao/umami#1037]
Hi
I just started to use umami and I really love how simple it is to setup and operate. Though the versioning of the docker container is a little bit confusing with the git hashes. Wouldn't it make more sense to have the same versioning schema like the umami node app itself?

**Comment by mikecao** [comment]
Haven't had time to look into this, but I think we can use git tags for version info. Would welcome a PR.

**Comment by quickstar** [comment]
Happy to assist! I'll try to look into it this week.
