### ISSUE TITLE
[Roadmap] Custom URLs (URL shortener)

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#104]
- Use the umami base to support generating and tracking URLs similar to Bitly and Yourls
- Track metrics for URLs just like websites

**Comment by scoates** [comment]
This sounds really useful. I humbly request that included in this is a documented API for creating/resolving these shortened URLs.

Do you already have a design in mind?

**Comment by mikecao** [comment]
@scoates The app currently makes API calls already, so this feature would just be an extension of that. There is no API documentation at the moment though. I will create an admin interface for creating links in the app, but of course you can just call the APIs directly as well.

**Comment by codyogden** [comment]
Explaining my 👎 :

I'm not sure this is a great feature. Self-hosting URL shorteners is never good for ensuring content is preservable. Specifically, [Link rot](https://en.wikipedia.org/wiki/URL_shortening#Linkrot) becomes a permanent issue if a user decides to leave umami for another service in the future, or just stop using analytics all together

**Comment by scoates** [comment]
Curious: was this closed because it's been implemented in an upcoming version, @mikecao?

**Comment by mikecao** [comment]
I think it's better off as a separate app like @codyogden mentioned. Keep umami strictly for analytics and I will create another app for links.
