### ISSUE TITLE
Ability to set new users as admin

### ISSUE THREAD

**Issue by MagicLike** [mikecao/umami#1045]
When I installed Umami, I immediately noticed when I wanted to create a new user that I could not set it as administrator. I solved this by editing the database. However, I think for less technical users it would be easier to set it via the GUI.

![7f00f1b7-a3fb-4880-877f-8fb6fc421175](https://user-images.githubusercontent.com/82117109/159220658-c6e29d88-46c7-40a2-8808-84d94249a33d.jpg)

**Comment by bernd-wechner** [comment]
I just installed umami and noticed the same. I second this, as it is important for security reasons on a public facing URL to avoid stock usernames like admin. My standard plan would be to create anew admin account with a specific and local name, and then delete the default admin account or disable logins for it in any case.

**Comment by mikecao** [comment]
The original idea was that you would never need to have more than one admin account, like a root account in linux. The admin abilities are pretty destructive so it's better to limit the number. As for renaming the admin account, we can probably allow that in the UI.
