### ISSUE TITLE
Vercel Hosting - Free Version

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#107]
Glad to see Umami offers vercel hosting.

However after checking vercel docs, they only allow 12 serverless functions per repo. So will I be able to host this on vercel for free? or is paid plan necessary?

Also, Is it possible to host Umami for 100+ client domains with around 50k requests for each domain will work fine on Vercel? Also in free plan or Pro Plan?

Can anyone explain this?

or, Simply how can I do this without breaking the bank?

**Comment by mikecao** [comment]
You'll have to refer to Vercel policies https://vercel.com/docs/platform/fair-use-policy
and limits https://vercel.com/docs/platform/limits

**Comment by surjithctly** [comment]
@mikecao I read that pages. That’s why I got this query. They mention 12 functions for free plan. So I’m asking do umami have more functions?

Anybody have success in uploading to vercel in free plan?

**Comment by mikecao** [comment]
I am running Vercel and I know a lot of others are as well. If the serverless function limit was hit, it would not even deploy.

As for how many hits it can take, I don't know. I know there is a 100GB traffic limit.

**Comment by surjithctly** [comment]
Thank you
