### ISSUE TITLE
`FORCE_SSL` variable causing redirect loop on Railway deploy

### ISSUE THREAD

**Issue by joelgoodman** [mikecao/umami#1070]
**What:** When updating a forked Umami repo deployed on Railway, a redirect loop is caused on redeploy.

**Context:** This happened to me on Railway twice and today Railway devs tracked it down to the `FORCE_SSL` env variable. Removing that fixed the issue, but were not 100% what exactly was happening. Reporting here in case it's an obvious thing.

Should note, it's been fine when I deploy fresh and new code. But if I have `FORCE_SSL` defined, it causes the redirect loop. Maybe I don't need to force ssl?

**Comment by KonstantinReido** [comment]
#1023 is the same issue

**Comment by joelgoodman** [comment]
Ugh, thanks. I even searched!
