### ISSUE TITLE
Tracking data going to different domain

### ISSUE THREAD

**Issue by stephenrutherford** [mikecao/umami#1072]
I have two domains in my Umami dashboard but when I visit domain#2 the visits are being tracked under domain#1.

Dashboard:
![image](https://user-images.githubusercontent.com/6411817/161628623-9d4c1633-0779-40a5-9c3e-9b3a8e7a8a64.png)

[domain #1 script config](https://github.com/stephenrutherford/portfolio_v5/blob/main/pages/_document.js)
[domain #2 script config](https://github.com/stephenrutherford/dc3/blob/main/pages/_document.js)

Realtime logs (All Websites):
![image](https://user-images.githubusercontent.com/6411817/161628914-c64d0e66-f67c-47fd-92c6-e395519cca75.png)

I've updated to `v1.29.0` and redeployed but noticed it happening on earlier versions too. 
Also tried deleting and re-adding domain#2 with a new `website-tracking-id`.

Am I being silly and missing something simple here?

**Comment by mikecao** [comment]
So you mean when you visit  `dc3.vercel.app`, that visit actually gets recorded under `rutherdord.dev`? The page visit should always go to the `data-website-id`. Are you sure you're not triggering the wrong tag in your local setup?

**Comment by stephenrutherford** [comment]
Hi Mike, that is correct but I did figure out the issue. 

My deployment on Vercel was pointing to an outdated branch name due to own mistake. 
Everything looks to be good now!

![image](https://user-images.githubusercontent.com/6411817/161729343-62dcceef-8463-49a6-8569-f793a31f226d.png)
