### ISSUE TITLE
Cannot destructure property 'session_id' of 'session'

### ISSUE THREAD

**Issue by benestangl** [mikecao/umami#1075]
When there is a unique constraint error from the db, the script fails.

```
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
at getSession (/home/ubuntu/umami-analytics/.next/server/chunks/4704.js:227:13)
```

Reason should be the following line:
https://github.com/mikecao/umami/blob/aa9dbd209224f938904a89a6993e8e24854e5ea4/lib/session.js#L52

See here:
https://github.com/mikecao/umami/blob/aa9dbd209224f938904a89a6993e8e24854e5ea4/lib/session.js#L58

I don't think this was intended.

Thanks for creating the project

**Comment by thueske** [comment]
Same issue with current umami version on docker:

```
yesterday at 11:50:37TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
yesterday at 11:50:37    at getSession (/app/.next/server/chunks/1649.js:230:13)
yesterday at 16:37:21TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
yesterday at 16:37:21    at getSession (/app/.next/server/chunks/1649.js:230:13)
```

**Comment by ryancanzo** [comment]
I have the same issue. The server eventually crashed but not sure if that is related to the error. I'm using Railway with the default Heroku builder. 

`TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
at getSession (/app/.next/server/chunks/1649.js:230:13)
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by benestangl** [comment]
The reason is that is can happen that the session_uuid already exists
`Key (session_uuid)=(dc571839-9995-59e2-91ba-013d7a3f215c) already exists.`

And then there is this check still:
https://github.com/mikecao/umami/blob/aa9dbd209224f938904a89a6993e8e24854e5ea4/lib/session.js#L52

which leads to the destruct error, since when the uuid already exists the session is `null` .
i think it would be more useful to remove the check for unique constraint , since we could see the real reason for that error and not the destruct error - but still not really solving it
