### ISSUE TITLE
[Feature request] Exclude or include domains

### ISSUE THREAD

**Issue by dakshshah96** [mikecao/umami#109]
Proposed feature: Ability to specify `excluded-domains` and `included-domains` in the `script` tag.

Use case: This would make it easy to ignore tracking hits from a local development environment or a staging environment.

**Comment by mikecao** [comment]
Waiting on this PR #162 to be completed, then I can consider supporting this.

**Comment by hemorej** [comment]
Can we make this feature support IPs as well? Let's say I don't want to count my own visits if I'm testing a new deployment I could add my home IP to the exclude list

**Comment by mikecao** [comment]
@hemorej You can't get the IP on the client side. I'll support for it on the server side.

@dakshshah96 I think I'll implement this only for `include`. I can't think of a case where `exclude` would be useful.

**Comment by dakshshah96** [comment]
> @dakshshah96 I think I'll implement this only for `include`. I can't think of a case where `exclude` would be useful.

Agreed! Better to have a minimal feature set.
