### ISSUE TITLE
number of users / views  is really off compared to GA

### ISSUE THREAD

**Issue by JohnMica** [mikecao/umami#1094]
Hi and thanks for this library.

I am running into a strange issue.
We are running Umami on 2 servers (separate DB, instances) for production.

We've seen strange differences between the numbers reported for the past couple of months since we started using Umami in parallel with Google Analytics (GA)

GA says there are 896 users and 1495 Page Views
Umami says there are 36 users and  125 Views ( safe to assume these are Page Views ?)

since the differences are quite huge, i am not sure if this is due to 
- config errors
- page tracking errors

For the pages we are using a simple  trick in our `layout.vue` template

```
  head() {
    return {
      script: [
        this.$config.umamiUrl &&
          this.$config.umamiId && {
            hid: 'analytics-u',
            src: this.$config.umamiUrl + '/umami.js',
            'data-website-id': this.$config.umamiId,
            'data-auto-track': true, // this is for tracking all pages
            async: true,
            defer: true
          }
      ].filter(v => !!v)
    }
  },
```

which is being loaded and running on all pages (we have quite a few of dynamic pages indeed)

since all pages are SSR rendered, all page views should be tracked and displayed as such, no ?

not sure what the issue might be but a few pointed would for sure help out

**Comment by mikecao** [comment]
If you are the using the default `umami.js` script, it's possible it's being blocked. Try using a different name with `TRACKER_SCRIPT_NAME`.

**Comment by JohnMica** [comment]
thanks for the quick reply @mikecao 

managed to solve this issue 
- was a DNS issue that was causing the numbers to not register.
- moved the tracking into individual pages so

```
  head() {
    return {
      script: [
        this.$config.umamiUrl &&
          this.$config.umamiId && {
            hid: 'analytics-u',
            src: this.$config.umamiUrl + '/umami.js',
            'data-website-id': this.$config.umamiId,
            'data-auto-track': false, // this is for tracking all pages
            async: true,
            defer: true
          }
      ].filter(v => !!v)
    }
  },
````
and on each page that needs tracking

````
async onMounted() {
     ...... some other things happening
   if (window.umami) {
      await window.umami.trackView(this.$route.fullPath) // to include the URL params as well for different searches, etc ...
   }
}
```
