### ISSUE TITLE
Unable to install umami via the link provided in  documentation 

### ISSUE THREAD

**Issue by Justin-Jordan** [mikecao/umami#1097]
When I try to deploy umami on heroku it say "We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**Comment by af1** [comment]
I had the same issue using Heroku, I was able to get it working via Railway

**Comment by giuliomagnifico** [comment]
Same here on Heroku (if I try to deploy a new app), and I also have an error when updating. I'm still on 1.28, I think there's an issue with the Heroku ToS or similar, I don't think it's a code bug.

**Comment by bonesoul** [comment]
same here..

**Comment by AlbertoMontalesi** [comment]
Same here

**Comment by mikecao** [comment]
It's an issue with Heroku. You'll have to bring it up with them.
