### ISSUE TITLE
Erroneous display of IP:s that can't be geolocated

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#1102]
IP:s that can't be geolocated (i.e. "null") displays as  [object Object]
![Skärmavbild 2022-04-12 kl  19 02 58](https://user-images.githubusercontent.com/10003475/163016571-e96f017b-c87f-4075-acc4-bf45eb081f82.png)
]

**Comment by sellertool** [comment]
@mikecao The latest version still has this error
