### ISSUE TITLE
Node.js v12 EOL soon

### ISSUE THREAD

**Issue by olof-nord** [mikecao/umami#1105]
hello @mikecao!

In the readme its specified that umami supports Node.js 12+.

The official docker image uses v12, which is in Maintenance LTS, with the maintenance end currently set at 2022-04-30 (that's soon!).

What are some potential roadblocks/tasks/thoughts regarding an upgrade? 

With an upgrade, do you see the 14.x, or the current LTS, 16.x version as a goal?

I am happy to help out in the process.

**Comment by mikecao** [comment]
The minimum version is just what is minimally supported by Next.js and Prisma, two core packages that are used. You are free to use any version you want.

**Comment by olof-nord** [comment]
you got it! closing this issue.
