### ISSUE TITLE
Undocumented `TELEMETRY_DISABLE` env change

### ISSUE THREAD

**Issue by KcZer0** [mikecao/umami#1111]
Commit 281671b792eb6df3fa979ed8fc8b3d7b902cf738 changed the `TELEMETRY_DISABLE` env to `DISABLE_TELEMETRY`  
but it's not mentioned in the [v1.29.0 release](https://github.com/mikecao/umami/releases/tag/v1.29.0), nor [documented](https://umami.is/docs/environment-variables).  

Some people may prefer to disable any telemetry, even if it's anonymous

**Comment by mikecao** [comment]
Updated docs on website.
