### ISSUE TITLE
[Feature request] BaseURL

### ISSUE THREAD

**Issue by xepolite** [mikecao/umami#112]
Proposed feature: Ability to specify a BaseURL
Use case: This allows incorporation on servers that do not use subdomains

Forgot to mention: this software rocks. Its very beautiful and intuitive.

**Comment by mikecao** [comment]
That is a feature of Next.js already, https://nextjs.org/docs/advanced-features/module-path-aliases

**Comment by xepolite** [comment]
Oh my god... I've been working around this with Apache like an idiot haha. Thanks for letting me know.
