### ISSUE TITLE
Show page title for referrers as well as the link

### ISSUE THREAD

**Issue by max-programming** [mikecao/umami#1125]
Right now the referrer's URLs are shown. It would be better to show the title of the referrer instead of the URL and show the URL in a tooltip when hovered over it.

![image](https://user-images.githubusercontent.com/51731966/165279273-ab713ad4-e757-4b2a-bf73-5a62021516fa.png)

> [`open-graph-scraper`](https://npmjs.com/open-graph-scraper) is a great tool for it.

**Comment by Aggtaa** [comment]
I believe it's not possible to display a page title as it's simply not reported to the tracker.

Fetching page titles by URLs is impossible in general as referrer URL is not always public or even a valid URL at all. 
And even if there is a downloadable page at that URL, scraping it would generate a lot of local traffic and will almost immediately result in blocking the umami server source IP by that page website owners.

**Comment by max-programming** [comment]
But there has to be some way to do that

**Comment by mikecao** [comment]
Titles are inconsistent among websites and they don't represent the page better than the url.
