### ISSUE TITLE
[Feature Request] Ignore visits based on hostname

### ISSUE THREAD

**Issue by patrickhilker** [mikecao/umami#1151]
I use a DynDNS pointing to my IP at home. By resolving this hostname Umami could get my IP and ignore my visits.

Would such a feature be appreciated? I would be able to contribute the code.

**Comment by mikecao** [comment]
You just need to add `umami.disabled = true` to local storage and your visits will be ignored.

**Comment by patrickhilker** [comment]
As far as I know this has to be done for every website, on every client, hasn't it? For everyone tracking a few websites this becomes pretty quick a huge task. On mobile devices this is not even possible (at least in Chrome on Android).

Tracking 30 websites and working from 3 clients I personally have to edit my local storage 90 times. If one is an agency with employees this becomes absolutely unmaintainable.

**Comment by mikecao** [comment]
You can use the `IGNORE_IP` environment variable then. See https://umami.is/docs/environment-variables

**Comment by patrickhilker** [comment]
As I get a new IP every day this is not really an alternative

**Comment by mikecao** [comment]
Ok, we can prob add a new environment variable then.

**Comment by rohandebsarkar** [comment]
This will be helpful.

**Comment by mikecao** [comment]
Just keep in mind that this could potentially be very slow. You are effectively running a DNS lookup for every pageview.

**Comment by rohandebsarkar** [comment]
Sorry, probably I understood the issue wrong.

I meant to ignore visits based on hostnames, like while testing my website locally, if the visits are coming from `localhost` or `127.0.0.1`.

Sorry for misunderstanding.

**Comment by mikecao** [comment]
@rohandebsarkar You can use the existing variables to do that, https://umami.is/docs/environment-variables

**Comment by rohandebsarkar** [comment]
Thank you for replying. Are you talking about the `hostname variable`? There is no documentation below it.

**Comment by mikecao** [comment]
No just the `IGNORE_IP`, just enter your localhost IP

**Comment by rohandebsarkar** [comment]
> No just the `IGNORE_IP`, just enter your localhost IP

I tried `IGNORE_IP`. But it didn't work.
But I was able to get it to work with [`data-domains`](https://umami.is/docs/tracker-config) attribute.

**Comment by cmj2002** [comment]
> > You just need to add `umami.disabled = true` to local storage and your visits will be ignored.
> 
> is this documented somewhere other than your comment in this gh issue? Are there other localStorage variables we can set?

It is documented in https://umami.is/docs/track-events#prevent-tracking-yourself

I don't know any other localStorage variables we can set.

**Comment by nicolas-bastien** [comment]
Hi, the documentation explains how to work with local storage but this is not really usable with non developers.
https://umami.is/docs/exclude-my-own-visits

@mikecao Plausible as a simple way to do that : https://plausible.io/docs/excluding
So I can ask a customer to go to https://whatismyipaddress.com/ and I just save their ip once.

I don't know if your customers are the same as mine but they can refresh the page several times when they change small texts.
What do you think about implementing the plausible feature in Umami ?

**Comment by AndyTopley** [comment]
I'm using hosted Umami and I've been testing it along with two others options as a route to shift my client sites to. 

Not being able to ignore my IP and my client IP's are a deal breaker for me, most importantly my IP. I can have Umami as an option if I can't easily input my IP on the dashboard as one to always ignore.

**Comment by mikecao** [comment]
@AndyTopley If you simply want to exclude yourself, you can do this https://umami.is/docs/exclude-my-own-visits

For self-hosted users, they can use the `IGNORE_IP` environment variable.

For Umami Cloud, we will be adding the option to add IP addresses.

**Comment by MatijaOsojnik** [comment]
> [@AndyTopley](https://github.com/AndyTopley) If you simply want to exclude yourself, you can do this https://umami.is/docs/exclude-my-own-visits
> 
> For self-hosted users, they can use the `IGNORE_IP` environment variable.
> 
> For Umami Cloud, we will be adding the option to add IP addresses.

@mikecao has this been implemented? I want to exclude my team's IPs - we're using the Umami Cloud.

**Comment by david-fortini** [comment]
@mikecao  same here, we are using umami cloud and I find it quite surprising that the self-hosted version has the only 'option' to pass an IP-list...

**Comment by briangladu** [comment]
I also think this feature is needed in the Cloud solution! Loving Umami, but being able to ignore by IP seems like table stakes.
