### ISSUE TITLE
Support for Prisma 3.13 ETA?

### ISSUE THREAD

**Issue by bhadaway** [mikecao/umami#1155]
As far as I can tell, the only thing holding us back from installing Umami on Ubuntu 22.04 now is support for Prisma 3.13 (or newer) in Umami?

**Comment by mikecao** [comment]
Next release will have this.

**Comment by bhadaway** [comment]
Great to hear. Any ETA, even if just a ball park estimate? Thanks.

**Comment by mikecao** [comment]
Available in v1.32.0
