### ISSUE TITLE
Minor typo in localization strings

### ISSUE THREAD

**Issue by MoltenCoffee** [mikecao/umami#116]
I was on the fence whether I should create this issue, as it doesn't seem to cause any problems.

The strings in the language files (`en.json`, `zh-CN.sjon`, etc.) contain one listing typed `label.adminsitrator` instead of `label.administrator`. I believe this typo does not cause problems down the line, it's probably reflected elsewhere, but a typo nonetheless.

**Comment by mikecao** [comment]
That should definitely be fixed. Thanks for catching it.

**Comment by mikecao** [comment]
This should be fixed by #119
