### ISSUE TITLE
Request to use Fetch (with keepalive) instead of Beacon

### ISSUE THREAD

**Issue by rohandebsarkar** [mikecao/umami#1160]
Recently, I found out that beacon request are blocked by ad blockers such as uBlock Origin. After searching a bit on the internet, I found that the beacon request are equivalent to [fetch API with keepalive](https://developer.mozilla.org/en-US/docs/Web/API/fetch#keepalive) option.

Therefore, I tried replacing beacon with fetch (with keepalive option), it seems to work fine.

So I think, if both methods are equivalent it would be better to use fetch as it will not be blocked by ad blockers, or may be to add a fallback to fetch if the beacon fails.

Anyway, thanks for this awesome project.

**Comment by MagicLike** [comment]
I just also discovered that.
Even if it is unnessesary, here a screenshot from the uBlock log, when I triggered some events:
![grafik](https://user-images.githubusercontent.com/82117109/170104696-e542e311-97ef-491a-869c-9bc8c38d57d8.png)

**Comment by rohandebsarkar** [comment]
I created PR #1163 to solve this.

**Comment by rohandebsarkar** [comment]
This feature was released with [`v1.32.0`](https://github.com/mikecao/umami/releases/tag/v1.32.0).
