### ISSUE TITLE
Invalid download url in `scripts/build-geo.js`

### ISSUE THREAD

**Issue by pseudoyu** [mikecao/umami#1165]
As shown in this commit:
[chore(redist): update databases - cron job GH-327](https://github.com/GitSquared/node-geolite2-redist/commit/18c0106a4590b91604b604571e055e91c7b6ed02)

The file `GeoLite2-Country.tar.gz` was removed but the url in `scripts/build-geo.js` was absolute path with the url `'https://raw.githubusercontent.com/GitSquared/node-geolite2-redist/master/redist/GeoLite2-Country.tar.gz'`.

So when I build the project, it went wrong.

**Comment by mikecao** [comment]
When I go to the url, `https://raw.githubusercontent.com/GitSquared/node-geolite2-redist/master/redist/GeoLite2-Country.tar.gz` the file is there.

**Comment by pseudoyu** [comment]
> When I go to the url, `https://raw.githubusercontent.com/GitSquared/node-geolite2-redist/master/redist/GeoLite2-Country.tar.gz` the file is there.

It's fixed and I deploy successfully using Railway. Thank you!
