### ISSUE TITLE
binding to IPv6 via next results in HTTP 400 errors

### ISSUE THREAD

**Issue by Grauwolf** [mikecao/umami#1168]
There seems to be an issue when binding the next server to IPv6.

Up to umami 1.26.0 it worked when starting the next.js server with `-H ::`.

Since then, the umami server will start and bind to IPv6, but any HTTP request will get a HTTP 400 response without any logs.

This can be easily reproduced by starting it via `./node_modules/.bin/next start -H ::` or via docker

`docker run --rm -ti -e DATABASE_TYPE=postgresql -e 'DATABASE_URL=postgresql://umami:1234@host:5432/umami' -p 3000:3000 --entrypoint "/usr/local/bin/yarn" ghcr.io/mikecao/umami:postgresql-v1.31.0 run next start -H ::`

**Comment by mikecao** [comment]
You can try upgrade the next version and see if it has been resolved in the latest version. v1.26 used next v12.0.10. We are currently on next v12.1.0.

**Comment by Grauwolf** [comment]
I might have not written that clearly enough. This issue still persists in v1.31.0. It just started with versions that came after 1.26.0.

**Comment by mikecao** [comment]
I'm saying we update Next.js versions with almost every release of Umami. It is likely due to some change in Next. You can try switching out Next versions to find one that works.

**Comment by Grauwolf** [comment]
Starting the server with server.js, that seems to have been introduced in 1.32.0, has solved the issue!
Thanks!
