### ISSUE TITLE
Remove external resources.

### ISSUE THREAD

**Issue by codyogden** [mikecao/umami#1173]
We should remove calls to external resources. I stumbled upon this resource call after some warnings in Dev Tools showed up because the prefetch was being rendered over and over again.

The particular usage below seems like it was included to track usage of umami. If we don't want to remove it, provide users a ENV flag that lets users opt-out completely from external resources.

https://github.com/mikecao/umami/blob/8384d6af352a9393310540cf0c02fff3aee64cbc/pages/_app.js#L38-L43

This flag could:

- opt out of using an external file for the logo
- stop pinging GitHub's API for release updates

I really enjoy using this project. Happy to discuss or hear your thoughts.

**Comment by mikecao** [comment]
Yea that could work. We can add a variable to opt out of release updates and just remove the logo load altogether.

**Comment by mikecao** [comment]
Added `DISABLE_UPDATES` var in v1.33.
