### ISSUE TITLE
Customized TRACKER_SCRIPT_NAME in Docker not working

### ISSUE THREAD

**Issue by MatthK** [mikecao/umami#1174]
I just tried to customize my script name in a docker container. 

The ENV variable is set to `TRACKER_SCRIPT_NAME=u.js` but `/u.js` is not accessible, while `umami.js` still is. I also tried `ALTERNATIVE_SCRIPT_NAME=a.js` but neither of that works. I just get a page not found error.

I removed the container and started it again using the following code:

```
docker run -d --name umami --restart unless-stopped \
-e DATABASE_URL=mysql://umami:password@db.domain.com:3306/umami \
-e DATABASE_TYPE=mysql \
-e HASH_SALT=secret_string \
-e TRACKER_SCRIPT_NAME=u.js \
-e ALTERNATIVE_SCRIPT_NAME=a.js \
-p 3000:3000 ghcr.io/mikecao/umami:mysql-latest
```

It runs the latest v1.31.0.

What am I doing wrong?

**Comment by mikecao** [comment]
The script name does not include `.js`.

**Comment by MatthK** [comment]
Thanks, that worked.
