### ISSUE TITLE
Multiple users & sites

### ISSUE THREAD

**Issue by joshinat0r** [mikecao/umami#118]
The current behaviour with multiple users is intended, so its not really a bug.
Should be easier if I explain it with an example:
- User ABC creates a website ABC
- User ABC creates a user XYZ
- User XYZ logs into Umami and the dashboard is empty
- User XYZ creates a website XZY
- User ABC only sees site ABC
- User XYZ only sees site XYZ

What I was expecting was:
- User ABC creates a website ABC
- User ABC creates a user XYZ
- User XYZ logs into Umami and can see website ABC

I know that I could enable the share URL, but that also means that user XYZ needs several links if I have several sites (and the stats are visible to everyone with the link). The only solution for me right now is to share my account.

I'm aware that a proper permission system is quite a bit of work, but that would cover all usecases with more granular control over users and which sites they can access.

An easier solution for now might be a `.env` var that is calling a `getAllWebsites()` method [here](https://github.com/mikecao/umami/blob/8df3c21ada790fc0a4dae10ca1f4e777580a4e06/pages/api/websites.js#L11) that selects all sites, instead of executing [this](https://github.com/mikecao/umami/blob/8df3c21ada790fc0a4dae10ca1f4e777580a4e06/lib/queries.js#L67) query that only selects sites created by the user.

Not a perfect fix since were either showing all available sites or not enough sites (for my usecase anyways), thats why I first wanted to create an issue. To see if there is a point to a cruel .env parameter or if a permission system is something that other people want/need.

**Comment by mikecao** [comment]
Can you explain your use case a little more? Trying to understand what you're trying to accomplish.

Most people will never need to create an account because they are using it for their own websites, so they will just use the default account. Accounts are for people who have clients and they want to host stats for their client's websites. The client can log in with their account and manage everything themselves. You definitely don't want different clients seeing each other's data.

If you're asking if the admin account should be able to see all websites, I think that can be possible. But other accounts should only see their own websites.

**Comment by joshinat0r** [comment]
My specific use case would already be solved if the admin-account could view all sites regardless of who created it. Haven't thought about that at all.

The goal is to use Umami for different 3 sites (+ subdomain), which means I would create 3 different users and create with every one of them the necessary sites.
But right now I as the admin have no access to any of those sites because the admin account didn't create a website. Which means if I want to look at the stats I need share the login details.

With a `.env` param I could spin up 3 instances of Umami where every user can see all sites.  
Like I said, not a great solution but it'd be quite a bit easier than a fully fledged permission system.

Anyway, just giving the admin access to all sites would do the trick for me.

**Comment by mikecao** [comment]
But why are you creating separate accounts instead of having all websites under a single account?

**Comment by joshinat0r** [comment]
Like I said: `Those sites are for clients, and ideally they'd get access to the dashboard.`

If the admin creates those sites then no other user can see any stats. If the users create those sites then the admin has no access to any of the sites.
Giving the admin the ability to view all sites regardless of who created them would fix this.

**Comment by mikecao** [comment]
Got it. Ok I can update it so the admin can access other websites. Will probably need to make it a different screen so you don't get mixed up with your own sites.

**Comment by mikecao** [comment]
@joshinat0r This is now available in the `dev` branch. Under `Accounts` there is a new button that let's you jump to an account's dashboard.

**Comment by joshinat0r** [comment]
Thanks for resolving this so quickly.
Personally would've preferred it if they all showed up on the admins dashboard, but I get why they are separated like they are.
Can bookmark the different users dashboards anyways, so it's not like I need to make several clicks every time I want to check all sites.

**Comment by MrChadMWood** [comment]
Is this available in Main?

**Comment by joshinat0r** [comment]
Yes, in Umami v1 the admin could just view a users complete dashboard.

In v2 that changed, the admin can't jump to a users dashboard anymore, but you can still view all sites.  
Just go to `Settings > Users > Edit-Button > Websites-Tab > View-Button`. Easier to just bookmark the URL if you need to visit them often.

v2 also has Teams. The owner of a website can create a team, add their websites to it and then share an access code.  
Other users can use that access code to join the team which allows them to view those shared websites.
