### ISSUE TITLE
trackEvent not working with window.location.assign

### ISSUE THREAD

**Issue by Olakeen** [mikecao/umami#1187]
Hello,

I want to track a custom event when users click on an href javascript link but I realized that is not working with :

window.location.assign
window.location.replace
window.location.href

The only way to track my event is with window.open which open a new tab but I don't want that.

Here my code :

-> not working
```
function MyFunction() {
umami.trackEvent('href click', 'signup');
window.location.assign("myUrl");
}
```
Strange fact, if I remove the window.location.assign, event is recorded.

-> working
```
function MyFunction() {
umami.trackEvent('href click', 'signup'');
window.open("myUrl");
}
```

I also tested with a .when.then and it's not working either (page is correctly loaded so umami.trackEvent is recognized)

`$.when(umami.trackEvent('href click', 'signup')).then("myUrl");`

Did I miss something or it's a bug ?

EDIT : same for umami.trackView

**Comment by mikecao** [comment]
It is because you are redirecting the page and umami didn't finish recording the data before the page unloaded. I would suggest you put a delay in there before the navigation.
