### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by nayakayp** [mikecao/umami#1188]
I install this in Vercel by using free mysql database from clever-cloud.com.

But when the site is deployed, I keep redirect to /login pages instead of /dashboard page. And the pages saying 403 forbidden.

Here's the website https://nayakayp-com-analytics.vercel.app
And here's the screenshot:
![image](https://user-images.githubusercontent.com/24706517/172986620-7d9f9f3b-9bdb-4142-b266-ac1c5d69c3b7.png)

**Comment by mikecao** [comment]
I'm running into this too on my dev branch in Vercel. It must be something wrong on their end. I will keep investigating.

**Comment by mikecao** [comment]
@nayakayp I just redeployed on vercel and it seems to be working again
