### ISSUE TITLE
Interface stops working after adding a website

### ISSUE THREAD

**Issue by Dinip** [mikecao/umami#12]
Hi again,

As soon as I add a website the interface stops working...
Error in command line:
![image](https://user-images.githubusercontent.com/8941012/90575314-0ce5be00-e1b3-11ea-9d1a-ca7826096aef.png)
Error in interface:
![image](https://user-images.githubusercontent.com/8941012/90575354-1b33da00-e1b3-11ea-81b4-4fa1e840df8b.png)
Database entry:
![image](https://user-images.githubusercontent.com/8941012/90575543-8e3d5080-e1b3-11ea-91ae-425b327a4a5f.png)

**Comment by mikecao** [comment]
Ok I just pushed out a fix. Try pulling the latest.

**Comment by Dinip** [comment]
Seems ok
