### ISSUE TITLE
[feature request] Offline/PWA support 

### ISSUE THREAD

**Issue by saschwarz** [mikecao/umami#120]
For PWAs that work offline, it would be great if the client would cache pages/events and send them when a connection is restored.

**Comment by mskian** [comment]
Yes Progressive web app support much-needed one
also responsive mobile layout for realtime stats, views, visitors, bounce rate, average visit time
chats are only responsive and adapted to the screen

**Comment by mikecao** [comment]
I think this would require a separate, more advanced tracker. I wouldn't want to add all that logic in the default tracker since it's not a common use case.

**Comment by mikecao** [comment]
Probably won't pursue this anytime soon. Closing for now.
