### ISSUE TITLE
Could not login - PrismaClientUnknownRequestError

### ISSUE THREAD

**Issue by ndaidong** [mikecao/umami#1202]
Hello, I'm trying the new versions with docker:

- `ghcr.io/mikecao/umami:postgresql-v1.32.1`
- `ghcr.io/mikecao/umami:postgresql-v1.32.0`

 and facing the following problem:

![Screenshot from 2022-06-12 12-04-45](https://user-images.githubusercontent.com/1809619/173215682-4ff7e8ef-5a31-459a-b796-311c30c2a6c8.png)

which leads to an `Internal Server Error` shows at login page.

Database is already imported and the connection looks good:

![Screenshot from 2022-06-12 12-09-56](https://user-images.githubusercontent.com/1809619/173215996-828774c3-0ff3-45c9-bda9-a650f0fdcd42.png)

Anybody get the same issue? how to fix it?

**Comment by Erreur32** [comment]
I have the same with a fresh install BUT with git also

**Comment by mikecao** [comment]
The error says the user does not have permissions to the tables. You need to update your permissions.
