### ISSUE TITLE
Incorrect links in demo/share

### ISSUE THREAD

**Issue by MoltenCoffee** [mikecao/umami#121]
Back again with another something I noticed..
In the live demo (which I assume is the view you get when sharing a URL to the data), when clicking on any of the `-> more` buttons, you'll go a page with some more details.  On this page, in the little selection menu on the left, the `referrers` link will lead to the `browsers` tab and vice versa.

I believe this is caused by rows 51 through 60 in `/components/WebsiteDetails.js`:

```jsx
{
  label: <FormattedMessage id="metrics.browsers" defaultMessage="Browsers" />,
  value: 'referrer',
  component: ReferrersTable,
},
{
  label: <FormattedMessage id="metrics.referrers" defaultMessage="Referrers" />,
  value: 'browser',
  component: BrowsersTable,
},
```

**Comment by mikecao** [comment]
Fixed in #123
