### ISSUE TITLE
Change the date formats to local

### ISSUE THREAD

**Issue by rohandebsarkar** [mikecao/umami#1221]
The dates are not shown according to local formats:

![Screenshot 2022-06-25 at 09-30-26 umami](https://user-images.githubusercontent.com/50144004/175757373-f4fad1d4-5838-44a8-b1f3-a0971cc42c0e.png)

It would be better if the dates were formatted according to local formats.

**Comment by mikecao** [comment]
They should already be formatted according to your selected locale.

**Comment by rohandebsarkar** [comment]
Can you tell me how to change the locale?

**Comment by mikecao** [comment]
The locale is tied to the language you select. Either use the globe icon in the top right or under settings.

**Comment by rohandebsarkar** [comment]
In that case, I would like to use English as my language but would want to use the Indian date format. But there is no option for English (India).

Moreover, even if I am using native language like Hindi, the date formats do not seem to be changed. See my screenshot below.

![Screenshot 2022-06-27 at 09-43-09 umami](https://user-images.githubusercontent.com/50144004/175858703-31dfa0c8-80f2-4df9-bb77-a5029d37866f.png)
