### ISSUE TITLE
Two CSS bugs in settings

### ISSUE THREAD

**Issue by MoltenCoffee** [mikecao/umami#128]
While translating, I noticed two bugs in the styling of the `Settings` page:

- In the `websites` subitem, between screen widths 770px and 1200px, the buttons to `edit`, `share` etc will flow beyond their parent `div`, overlapping the domain URL next to it in German and Dutch. These languages (and probably others) use more characters than their counterparts in Chinese and English;
- When below 990px in width, the submenu with `websites`, `accounts` and `profile` will have a higher z-index than the dropdown-menu for language selection, overlapping it.

**Comment by mikecao** [comment]
Thanks, will take a look

**Comment by mikecao** [comment]
Fixed in #130
