### ISSUE TITLE
[Feature Request] Allow serving umami.js and the collect api under a base path

### ISSUE THREAD

**Issue by simcop2387** [mikecao/umami#13]
It should be possible to configure umami to serve everything from a base path, so that sites that use /api/collect can still serve umami on the same domain

**Comment by mikecao** [comment]
No sure what you mean. Can you provide an example?

**Comment by simcop2387** [comment]
Sure, I've hacked it in place for my use on https://perl.bot/ right now it's serving up https://perl.bot/umami/umami.js and hitting the api under https://perl.bot/umami/api/collect, this is so that it can be on the same domain easily without causing any conflicts as the site itself uses /api/ on the same domain for it's own internal use.

**Comment by mikecao** [comment]
I see. Curious how you got it to work. Did you do something like this? https://nextjs.org/docs/advanced-features/multi-zones

But I think it would be possible to pass a hostname to the tracking script instead of defaulting to the current hostname. Then you can host the script wherever you want.

**Comment by simcop2387** [comment]
Nothing quite that fancy, I've just edited the tracking script to always assume the api is under /umami/api/collect for now, and then done some fun with the nginx reverse proxy.  The actual admin page I've put under another unrelated domain

**Comment by snibbo71** [comment]
Hi there,
    I second this one - I want to be able to setup an NGINX ProxyPass directive so that I can make the script look like it's hosted on the same server as my WordPress installation (so browsers know it's just a local script).

I've tried Location /dashboard and Location /_next with ProxyPass but can't get the _next ones to work - not sure if I've misunderstood Nginx ProxyPass directives but it's not working. If I could set a base path I could just Proxy the entire basepath to Umami

At least I think I should be able to...

Unless you have an example set of Nginx ProxyPass rules that you know do work?

Ta for this by the way, it looks really, really good so far

**Comment by jensao** [comment]
I am also interested in a solution to this since I have spent some time to try to achieve the same thing as @snibbo71 without luck.
Would also be great with deployment examples somewhere, e.g. under the Deployment section on the wiki?

Maybe off topic (sorry) but I provide a basic snippet of a Nginx configuration that I hope could be useful for others if you setup umami behind Nginx reverse proxy. 


        # The POST request back from the web page to umami
        location /api/collect {
            proxy_pass http://umami:3000;
            proxy_redirect http://umami:3000/ /;

            # May not need or want to set Host. Should default to the above hostname.
            proxy_set_header          Host            $host;
            proxy_set_header          X-Real-IP       $remote_addr;
            proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # Fetch umami.js from umami so it dosn't need to be stored together with the webpage
        location ~ ^.*(umami.js)$ {
            proxy_pass http://umami:3000/$1;
        }

**Comment by mikecao** [comment]
This commit 78888c3728fe2cbfe363486839f88bfc3f29df3f should enable you to run umami under a subfolder. Can you test if it works?

**Comment by mikecao** [comment]
Ok, in the latest release you can add `data-host-url` to your script and it will use that value instead.
