### ISSUE TITLE
api/collect returns http error 500

### ISSUE THREAD

**Issue by adoris123** [mikecao/umami#131]
if i try to send data via curl, a http error 500 will be returned, at server there are no visible logs.
how to get logs to understand why error 500 occurs?

 curl -v -d @1.json -X POST http://localhost:3000/api/collect

* upload completely sent off: 179 out of 179 bytes
< HTTP/1.1 500 Internal Server Error

root@test  cat 1.json
{"type":"pageview","payload":{"url":"/","referrer":"","website":"5dfde102-948b-45ea-9012-1b8304e116da","hostname":"test123.org","screen":"2560x1440","language":"en-US"}}

**Comment by mikecao** [comment]
Run in dev mode if you want to see logs, `npm run dev`
