### ISSUE TITLE
[Feature Request] Exclude bots from stats

### ISSUE THREAD

**Issue by pschoenmakers** [mikecao/umami#132]
To be a real alternative to other analytics solutions at least traffic from bots should be filtered out of the statistics. It appears right now all traffic is counted as a visitor.

**Comment by MoltenCoffee** [comment]
In my experience, [gorangajic/isbot](https://github.com/gorangajic/isbot) is quite a decent `bot detector`!

**Comment by pschoenmakers** [comment]
https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml

This is a pretty extensive list of bots.

**Comment by mikecao** [comment]
I suppose we can add bot filtering on `/api/collect` but definitely not in the tracker. I would want to make it configurable though since it's introducing extra load. It's not like 90% of your traffic is going to come from bots.

**Comment by MoltenCoffee** [comment]
The thing is that the less traffic you have, the larger the fraction of bots will be. I suppose another option would be to not necessarily block bots from being logged, but reporting them as another "device"?

**Comment by pschoenmakers** [comment]
Well, I'm running umami on a site now together with another paid analytics alternative. 

It's quite a difference. 
![See image](https://user-images.githubusercontent.com/15877946/92798483-46c17300-f3b3-11ea-9ed7-d56df75950d5.jpg)

**Comment by mikecao** [comment]
Ok I can add the feature

**Comment by mikecao** [comment]
@pschoenmakers Added to the latest release. Please verify.

**Comment by pschoenmakers** [comment]
@mikecao it's working, list of bots is not really comprehensive, but for me this is better as no blocking!
