### ISSUE TITLE
[Feature Request] Page specific average times

### ISSUE THREAD

**Issue by voidspacexyz** [mikecao/umami#133]
While Umami currently displays the overall average time users have spend on the website, It would be useful for me as a website owner to drill down on page specific average times. 

Good usecase are blogs, where I estimate a specific blog would take about 5 - 7 mins to read, but on an average users only spend about a minute.

**Comment by mikecao** [comment]
Tracking page time is actually very difficult. The calculation now takes the first pageview and the last pageview and finds the difference in time. If the user visits a single page and then leaves, there is no way to find the time. This is the same way that Google Analytics counts average time.

If anyone knows of a better solution that doesn't involve tracking cookies, I'd like to know.

**Comment by mikecao** [comment]
You can now track individual page metrics.

**Comment by jcuenod** [comment]
Is it possible to view more than just the average visit time? I am interested to know standard deviations / median...
