### ISSUE TITLE
Uncaught TypeError: n.startsWith is not a function

### ISSUE THREAD

**Issue by martin-ro** [mikecao/umami#137]
Not a javascript expert myself, but i see this in the console:

```
Uncaught TypeError: n.startsWith is not a function
    E umami.js:1
    p umami.js:1
    update turbolinks.js:5
    replace turbolinks.js:5
    startHistory turbolinks.js:5
    start turbolinks.js:5
    start turbolinks.js:6
    <anonymous> app.js:4
    js app.js:462
    __webpack_require__ app.js:20
    0 app.js:495
    __webpack_require__ app.js:20
    <anonymous> app.js:84
    <anonymous> app.js:87
umami.js:1:5208
    E umami.js:1
    p umami.js:1
    update turbolinks.js:5
    replace turbolinks.js:5
    startHistory turbolinks.js:5
    start turbolinks.js:5
    start turbolinks.js:6
    <anonymous> app.js:4
    js app.js:462
    __webpack_require__ app.js:20
    0 app.js:495
    __webpack_require__ app.js:20
    <anonymous> app.js:84
    <anonymous> app.js:87
```

Commenting out the tracking script solves it so I think it's umami related.

**Comment by mikecao** [comment]
Are you using a single page application? Looks like it's having an issue loading the url from the history object.

**Comment by mikecao** [comment]
Looks like `startsWith` is not widely supported on all browsers. Are you using IE? Either way I will update the tracker to use a different method.

**Comment by mikecao** [comment]
Should be fixed in latest release

**Comment by martin-ro** [comment]
> Looks like `startsWith` is not widely supported on all browsers. Are you using IE? Either way I will update the tracker to use a different method.

Using Firefox 80.0.1 on MacOS



> Are you using a single page application? Looks like it's having an issue loading the url from the history object.

No SPA but turbolinks. Don't think thats the reason though.



> Should be fixed in latest release

Will give it a try later. Thanks!!

**Comment by martin-ro** [comment]
Seems to work now 🥳
