### ISSUE TITLE
Serve Umami over SSL?

### ISSUE THREAD

**Issue by vicemond** [mikecao/umami#138]
Running into issues trying to run this on a server with SSL. It is installed just fine and I can see the dashboard (via regular http), but the site I want to install the snippet on is accessible via https. How can this be served via https? I'm assuming it may have something to do with setting up a proxy, but I'm lost. Is there a way to configure this to run on port 443?

**Comment by mikecao** [comment]
Say your website is on `mywebsite.com` with SSL. You would then create a `umami.mywebsite.com` also with SSL that proxies requests to the umami app running on localhost:3000. The SSL part is handled by your webserver hosting `umami.mywebsite.com`. The web server is just proxying requests to umami.

You can proxy with Nginx, https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
or Apache, https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by vicemond** [comment]
Thanks. I'm definitely closer. I had to use Passenger, since my current set up at my host doesn't allow reverse proxy, nor do I have access to my httpd.conf file to change any directives to allow it. I can now get to the umami.js script over https (https://stats.netingredients.com/umami.js) just fine, and I can (still) view my dashboard at http://stats.netingredients.com:3000/dashboard (however, note that I can't get to it via https).

I see this in the console on of the site I'm trying to collect stats from (netingredients.com - same domain):
```
[Error] Origin https://www.netingredients.com is not allowed by Access-Control-Allow-Origin.
[Error] Fetch API cannot load https://stats.netingredients.com/api/collect due to access control checks.
[Error] Failed to load resource: Origin https://www.netingredients.com is not allowed by Access-Control-Allow-Origin. (collect, line 0)
[Error] Unhandled Promise Rejection: TypeError: Origin https://www.netingredients.com is not allowed by Access-Control-Allow-Origin.
```

And for the record, I added this to an .htaccess file on both ends (since I'm confused about which end CORS is having the issue):
```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
</IfModule>
```

The tech at my host said, "If you use "Passenger" you just need to configure your "APP" to support "HTTPS" and it should work as long as a SSL certificate is installed." I'm wondering if this has anything to do with the issue? How can I configure Umami to support HTTPS? Does it?

**Comment by mikecao** [comment]
What kind of access do you have on your machine that you can install Passenger? Umami itself can't do SSL, it needs a webserver in front to proxy the requests.

Honestly, I think the easiest thing to do is just host the app on Vercel. They support SSL and you don't have to manage anything. And it's free.

**Comment by vicemond** [comment]
Good to know. Thanks, Mike.

My host offers Passenger as a one-click option within a domain set-up. I'll give Vercel a try. Thanks, again.

**Comment by ayewo** [comment]
To @vicemond or anyone else who wants to install Umami on Vercel, the project provides setup instructions here: https://umami.is/docs/running-on-vercel 

But to get it to work without granting Vercel's GitHub app access to all my repos, I had to first fork the repo into my GitHub account before attempting the https://vercel.com/import/ step.

Although setup steps 1-3 on https://umami.is/docs/running-on-vercel currently read as:
> 1. Create an account on Vercel.
> 2. From the dashboard page click Import Project.
> 3. Enter https://github.com/mikecao/umami as the Git repository. This will fork the project on your Github account.

.. the actual steps I used were swapped around a bit to use my fork:
> 1. Fork the https://github.com/mikecao/umami project to your Github account.
> 2. Create an account on Vercel. 
> 3. From the dashboard page click Import Project. This will be the URL to your fork of the project on Github.

BTW, kudos to @mikecao for making such an awesome product 👍!

**Comment by mikecao** [comment]
@ayewo Can you create a PR to update the steps on the website? 🙏

**Comment by ayewo** [comment]
@mikecao Done. 

Please see https://github.com/mikecao/umami.is/pull/8
