### ISSUE TITLE
E-Commerce Tracking

### ISSUE THREAD

**Issue by schmidsi** [mikecao/umami#141]
Amazing project. Is something like [E-Commerce tracking](https://matomo.org/docs/ecommerce-analytics/#ecommerce-tracking) on your roadmap?

The easiest way would be to extend the [event-tracking](https://umami.is/docs/track-events) with an option to provide value (money). Then we could have a super simple event like:

```ts
umami('CheckOut', { value: { amount: 10000, currency: 'EUR' }});
```

Later, it could be extended to products, like:

```ts
umami('CheckOut', {
  "value": { amount: 10000, currency: 'EUR' },
  "transaction_id": "24.031608523954162",
  "affiliation": "Google online store",
  "currency": "USD",
  "tax": 1.24,
  "shipping": 0,
  "items": [
    {
      "id": "P12345",
      "name": "Android Warhol T-Shirt",
      "list_name": "Search Results",
      "brand": "Google",
      "category": "Apparel/T-Shirts",
      "variant": "Black",
      "quantity": 2,
      "itemPrice": {
        "amount": 1000,
        "currency": "EUR"
      }
    },
    {
      "id": "P67890",
      "name": "Flame challenge TShirt",
      "list_name": "Search Results",
      "brand": "MyBrand",
      "category": "Apparel/T-Shirts",
      "variant": "Red",
      "quantity": 1,
      "itemPrice": {
        "amount": 1000,
        "currency": "EUR"
      }
    }
  ]
});
```

_[Inspired from Google Analytics E-Commerce Tracking](https://developers.google.com/analytics/devguides/collection/gtagjs/ecommerce)_

**Comment by mikecao** [comment]
Something like this should be possible. I just need to add an extra column or table and update the tracker. But I need to be careful not to expand the scope of the product too much. It's not meant to be a full analytics suite with segmentation, campaigns, advanced tracking, etc.

The problem with storing this data is how do you display it. The data is ad-hoc so not useful in the UI without advanced reporting. If the data is just meant to be stored for analysis later, I'm not sure how valuable that is.

But it is a feature that several people have asked for. Open to discussion.
