### ISSUE TITLE
Support Japanese language

### ISSUE THREAD

**Issue by rluisr** [mikecao/umami#142]
I'm developing for supporting Japanese language but I don't understand `combined` on filter.
What does it mean?
![](https://f.easyuploader.app/eu-prd/upload/20200911213614_546b344c3259524e7452.png)

**Comment by mikecao** [comment]
Combined means we join the URL by path:

**Raw**
a.com/path/?q=123
a.com/path/?q=456
a.com/another/
b.com/path/

**Combined**
a.com/path/ = 2
a.com/another/ = 1
b.com/path/ = 1

**Domain only**
a.com = 3
b.com = 1

**Comment by rluisr** [comment]
Thanks, I'll send PR.

**Comment by mikecao** [comment]
Thanks for the PR.
