### ISSUE TITLE
Is it a translation bug?

### ISSUE THREAD

**Issue by ym-project** [mikecao/umami#144]
I noticed one thing. On the page [https://app.umami.is/share/8rmHaheU/umami.is](https://app.umami.is/share/8rmHaheU/umami.is) you can see different metrics such as: browsers, devices, etc. All metrics are plural except "operating-system".
https://github.com/mikecao/umami/blob/661e54153870c40432f0cbf83b687e7b7626d544/lang/en.json#L173-L175

Is it a bug?

**Comment by mikecao** [comment]
Yes, probably. I can fix it in the next update.

**Comment by mikecao** [comment]
Fixed in latest update.
