### ISSUE TITLE
Language is not reflected.

### ISSUE THREAD

**Issue by err931** [mikecao/umami#146]
**Confirmed version: mysql-681852b**

The following bug was found.
![Screenshot (1)](https://user-images.githubusercontent.com/67395018/92990426-80ab8a00-f517-11ea-8fe1-f2b2ffd3937d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/67395018/92990427-81dcb700-f517-11ea-870b-81ff4398a912.png)

## :bug: Bug
- Account list
- Change Password

We have confirmed that the same problem occurs in all added languages.

**Comment by mikecao** [comment]
Thanks for reporting. Will fix.

**Comment by mikecao** [comment]
Fixed in latest update.
