### ISSUE TITLE
Feature request: UI improvement - select for detail view

### ISSUE THREAD

**Issue by martin-ro** [mikecao/umami#147]
It would be great to have a select dropdown (even better with a search filter) on the dashboard to jump directly to a detail view of a website. Main reason being that with a lot of websites it's either scrolling or using the browser text search. Also once found I cant CMD+Click for a new tab but have to visit detail view and when I go back I jumped right back to the top and the scrolling begins anew. 

Here is a mock-up of what I mean:
![Screen Shot 2020-09-12 at 5 33 57 PM](https://user-images.githubusercontent.com/10107779/92992688-5231ad00-f51f-11ea-9622-a33443bd4972.jpg)

Would be a great feature to have..

**Comment by mikecao** [comment]
I need to change the View Details from a button into a link. That should allow you to CMD+click it.

**Comment by martin-ro** [comment]
> I need to change the View Details from a button into a link. That should allow you to CMD+click it.

That would help navigating around. A quick navigation to the detail view of a website would be ideal in the end. Sorry I can't help out here with a PR.. react and next is just not my field of expertise.

**Comment by mikecao** [comment]
Not sure about the drop down. But I think a search box can be useful. Also adding a button or link on the website settings page could help as well.

**Comment by mikecao** [comment]
Fixed in #167
