### ISSUE TITLE
Unique constraint failed on the constraint: `session_uuid`

### ISSUE THREAD

**Issue by martin-ro** [mikecao/umami#149]
Getting

`500 Internal Server Error POSThttps://xxx.xxx.tld/api/collect`
`Unique constraint failed on the constraint: `session_uuid` 

very randomly. But tracking seems to work.

**Comment by mikecao** [comment]
It's probably a race condition where the session hasn't been logged to the database yet and another view comes in with the same id. Worse case you lose one page view.
