### ISSUE TITLE
Set default timeframe per site

### ISSUE THREAD

**Issue by PSNick** [mikecao/umami#153]
I have added umami to 3 of my sites so far, and I love it. One thing I'd love though is to be able to select the default timeframe per site (or globally). At the moment every site always loads with the "Last 7 days" setting; I tend to check daily, and having to select "Today" on each site every time I check can become pretty tedious, especially after adding another bunch of sites to umami.

**Comment by mikecao** [comment]
This is now covered by this issue #156
