### ISSUE TITLE
[Roadmap] Session caching

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#155]
This was originally in the first release but I removed it due to GDPR concerns because it uses localStorage. However it is a useful feature that is helpful for performance. So I'd like to add it back in and make it opt-in via an environment variable.

**Comment by fvsch** [comment]
Hi @mikecao and thanks again for Umami! Happy to contribute a bit of help on the UI/React/accessibility front if that's useful.

Can you explain what you mean by "Session caching"?
I noticed that some settings like the selected time range are not persisted when refreshing the page. Is this part of "Session caching" or a different issue maybe?

**Comment by mikecao** [comment]
No this is a different issue. What I mean by session caching is when you make a request to `/api/collect`, it needs to compute your unique session id every time. If we keep this in localStorage it will save some computation time.

For remembering the selected date time ranges, we just need to switch from using redux to localStorage. You can tackle that if you want.

**Comment by mikecao** [comment]
Done in #268
