### ISSUE TITLE
Calendar for custom range is not correct

### ISSUE THREAD

**Issue by ddeimeke** [mikecao/umami#158]
![image](https://user-images.githubusercontent.com/1115364/93081001-d35b8200-f68e-11ea-8784-c40327ef1ffa.png)

**Comment by ddeimeke** [comment]
Monday is the 14th, not the 13th. - v0.32.0

**Comment by mikecao** [comment]
Fixed in the latest #161

**Comment by tairosonloa** [comment]
Just realized this happens to me too on latest version (1.24.1). Using locale English/UK.
Can you, please, reopen the issue @mikecao ?

![image](https://user-images.githubusercontent.com/14878189/145611501-bb92b4dc-dafb-441e-9d2a-675a8c3fdee6.png)

**Comment by mikecao** [comment]
@tairosonloa Your issue is related to the locale, so can you create a new issue?
