### ISSUE TITLE
[Feature request] Please make the "Pages" clickable, like the "Referrers" are

### ISSUE THREAD

**Issue by ddeimeke** [mikecao/umami#159]
It would be nice to have a consistent experience.

**Comment by mikecao** [comment]
Actually this can't be done because I have no idea if the domain is http or https.

**Comment by ddeimeke** [comment]
In this case it would be nice to have that as configuration item with a default to use https.

![image](https://user-images.githubusercontent.com/1115364/93167441-efa7ff00-f720-11ea-9953-b5b66305c5af.png)

**Comment by mikecao** [comment]
Trying not to add any new fields to the database tables unless absolutely needed.
