### ISSUE TITLE
[Feature request] Start application using PM2

### ISSUE THREAD

**Issue by mihha** [mikecao/umami#16]
Hi,

it would be great if you can provide details how to start application using PM2 

https://www.npmjs.com/package/pm2
https://pm2.keymetrics.io/

That way, we could start the application automatically in case a server is rebooted

Thank you very much in advance!

Regards,
Igor

**Comment by mihha** [comment]
Replying to my self and giving the solution to the community

If you want to start application using PM2, you can use the following command

`pm2 start npm --name "next" -- start`

**Comment by nodesocket** [comment]
Add a PM2 specific file `ecosystem.config.json` like below. @mikecao maybe add to the root of the repo here? Then just run `pm2 start`. _Note: the `ecosystem.config.json` is doing a bit of tricky to actually invoke `npm start` instead of the standard invoking of a Node.js script directly._

```
'use strict';

const pkg = require('./package.json');

module.exports = {
    apps : [{
        name: pkg.name,
        script: 'npm',
        args: 'start',
        interpreter: 'none',
        watch: false,
        autorestart: true,
        exec_mode: 'fork',
        instances: 1,
        merge_logs: true,
        env: {
            NODE_ENV: 'production'
        }
    }]
};
```
