### ISSUE TITLE
Any logged-in user can access each other's statistics.

### ISSUE THREAD

**Issue by love4taylor** [mikecao/umami#166]
As long as the user knows the website id, he can access the statistics page, even if he is a normal user accessing the administrator's website page.

![image](https://user-images.githubusercontent.com/6081912/93456256-fea0d400-f90f-11ea-9eed-899c940a5dce.png)
![image](https://user-images.githubusercontent.com/6081912/93456341-22641a00-f910-11ea-8260-32424f3e9b59.png)

![image](https://user-images.githubusercontent.com/6081912/93456546-66efb580-f910-11ea-8dfe-ee1341f845ae.png)

**Comment by hugomd** [comment]
I can probably raise a fix for this over the weekend ✨

**Comment by mikecao** [comment]
Beat you to it @hugomd 😄 Fixed in #167

**Comment by hugomd** [comment]
So fast @mikecao ! ⚡
