### ISSUE TITLE
Allow website domains of the form `localhost:xxxx`

### ISSUE THREAD

**Issue by rendall** [mikecao/umami#172]
Currently, when adding a website (from the umami page `http://localhost:3000/settings` for example), a domain in the form `localhost:<port>` will fail to validate, because it expects a domain as a url, e.g. "github.com". However, it is useful for developers to have a project running locally and to test its tracking feature on the local version of umami. I recommend changing the `DOMAIN_REGEX` constant in the [`constants.js`](https://github.com/mikecao/umami/blob/master/lib/constants.js) file to allow `localhost:xxxx` domains

**Comment by mikecao** [comment]
PR merged
