### ISSUE TITLE
Allow programmatic event types other than 'custom'

### ISSUE THREAD

**Issue by rendall** [mikecao/umami#174]
Currently, **umami** allows event types to be only user interaction events (e.g. `click`) via CSS events, or `custom` _only_ via javascript call `umami("some event")` which will track as `{event_type:'custom', event_value"some event"}`

However, it would be useful to have event types other than `custom`. I recommend a minimal, non-breaking modification to `https://github.com/mikecao/umami/blob/master/tracker/index.js` to allow the developer to track other event types, with `custom` as default.

**Comment by rendall** [comment]
I did submit a PR against this issue, but please feel free to chat with me about it or reject the PR. No pressure! 

It's just that I modified the code when evaluating *umami* for myself, and decided to help out where I personally found it useful.  Same goes for issue #173

**Comment by mikecao** [comment]
Ok, this is now available in the latest version. You'll need to use the new `pageEvent` method:

```javascript
window.umami.trackEvent('my event', 'my event type');
```
