### ISSUE TITLE
[Feature Request] Web Vitals integration

### ISSUE THREAD

**Issue by bosskopp** [mikecao/umami#176]
[Web Vitals](https://web.dev/vitals/) are key performance indicators for websites:

> Web Vitals can help you quantify the experience of your site and identify opportunities to improve

Luckily, they can easily be integrated:
https://github.com/GoogleChrome/web-vitals#send-the-results-to-an-analytics-endpoint

Providing Web Vitals support sets umami further apart from its competition and provides valuable information for website owners / developers.

**Comment by mikecao** [comment]
This sounds like a tool for measuring page performance more than visitor metrics. Wouldn't these metrics always be the same unless the page changes?

The problem now is umami doesn't handle storing metadata. It only knows about pageviews and events, but this could be the enhancement you're looking for.

**Comment by bosskopp** [comment]
Web vitals are directly collected from visitors for each single page. So, a mobile visitor on 3G likely gets another score than a desktop user on broadband. Also, a user near to an edge will get better results than one far away (latency). Thus, web vitals are an important mix-up of site performance and visitor metrics. They fit well into web analytics setups.

I think umami wouldn't need to do much more than enrich calls & data models with web vitals values.

This getting started guide tells a bit more: https://web.dev/vitals-measurement-getting-started/

**Comment by mikecao** [comment]
May consider doing this in the future. Will need to rethink the back-end a bit and how to store/display the data.
