### ISSUE TITLE
[Feature request] parse get parameters for events

### ISSUE THREAD

**Issue by hemorej** [mikecao/umami#177]
Similarly to how we can use CSS classes as events, I'm proposing to be able to interpret specific URL parameters as tracking events. 

The use case I have in mind for this is incoming links from emails or other places where we can't embed the script tag. For example the URL `https://example.com?src=email&type=fall-newsletter` would count this as a custom event with referrer "Email" and event name "Fall newsletter"

GA has a complicated URL builder for campaign tracking with UTM tags, this would be a simpler version of the same idea.

**Comment by mikecao** [comment]
The example.com in this case is your website right? Even if the traffic comes from an email it would still hit your site and run the script. You can then just run a custom javascript function to check the url and create an event.

**Comment by hemorej** [comment]
Yes true, but the method to check for the GET params and send the event would have to be loaded and run on every page. Since I'm already loading and running `umami.js` on every page I thought it would be more practical.

**Comment by mikecao** [comment]
There's no practical way to determine which query parameters you want converted into events. You would have to write your own function to do it using `window.umami`. See https://umami.is/docs/tracker-functions. Another person may not want the same params as events.

**Comment by hemorej** [comment]
No of course not, I just gave an example with arbitrary parameters for illustration. Umami would determine which specific parameters it monitors, kind of like how GA reserves `utm_` for a similar purpose.

**Comment by mikecao** [comment]
Won't be adding this to the main functionality. You can always write your own functions if needed. See https://umami.is/docs/tracker-functions
