### ISSUE TITLE
0.37.0 canno open modal on firefox

### ISSUE THREAD

**Issue by tim-hub** [mikecao/umami#180]
- Add website
- Change passwords
- Add accounts

When click these 3 buttons, the modal does not show up, but it do it on chrome, everthing is fine, but not sure whether this is from nextjs or umami?

## Reproduce
- open umami in firefox
- click either of these three buttons

**Comment by mikecao** [comment]
Can you try pulling the latest commit? I tried in Firefox and it works for me.

**Comment by tim-hub** [comment]
> Can you try pulling the latest commit? I tried in Firefox and it works for me.

No it does now work for me.

the modal somehow opened but hidden, like another layer above all other elements.

**Comment by mikecao** [comment]
This still a problem? I used Firefox 81 on a mac with no issue.

**Comment by tim-hub** [comment]
> This still a problem? I used Firefox 81 on a mac with no issue.

Still not work on me, even in private mode, I do not know why.

But I think we can close it for now, it seems like something different with my firefox config

**Comment by meirroth** [comment]
@mikecao Can confirm I am seeing the same issue on Firefox 85.0 with umami v1.10.0
These modals all have opacity: 0 set when opened.
- Add website
- Change passwords
- Add accounts
- Custom range
