### ISSUE TITLE
Unable to login after installation

### ISSUE THREAD

**Issue by snird** [mikecao/umami#19]
I followed https://umami.is/docs/login but the login credentials does not work.

I guess this is a bug, as I looked at the postgres insert script: https://github.com/mikecao/umami/blob/d3514cfc5f20966612c277a5885356fa220a5ddd/sql/schema.postgresql.sql#L72

It is hardcoded for the password hash there, it does not consider the SALT we chose in the config.
So this salt won't work with the hardcoded hash...

I did not validate this yet, but I guess this is the issue here

**Comment by martin-ro** [comment]
Same problem here

**Comment by snird** [comment]
I'm actually confused, the code here that created password seems to not use the SALT at all:
https://github.com/mikecao/umami/blob/b392a51676fc314df7b338bf790c8af8fc64fd6c/lib/crypto.js#L28

it just pass salt rounds, let bcrypt use a random SALT.
maybe I miss something here so I'll wait for the author (:

**Comment by mikecao** [comment]
The password function does not consider the HASH_SALT in your .env file. It chooses a random salt. Can you try updating the password in the database to another value and see if that works?

**Comment by snird** [comment]
Yes.
I manually generated a pass using `bcrypt.hash()` and set it on the database.
This allowed me to connect.

**Comment by jkyngan** [comment]
i execute the following sql and it works
`insert into account (username, password, is_admin) values ('admin', '$2b$10$BUli0c.muyCW1ErNJc3jL.vFRFtFJWrT8/GcR4A.sUdCznaXiqFXa', true);
`
found in the last line of schema.mysql.sql

**Comment by mikecao** [comment]
Latest push updated the hashes in the sql files just in case, though the original ones should have worked.

**Comment by SoftCreatR** [comment]
I'm still unable to login, even with a self generated hash.

**Comment by mikecao** [comment]
@SoftCreatR can you try pulling the latest version? It was incorrectly reporting invalid login/password when it could be due to some other issue.

**Comment by SoftCreatR** [comment]
Nope, no success.

![image](https://user-images.githubusercontent.com/81188/90709764-3713aa80-e29d-11ea-84a6-8af66a943216.png)

**Comment by mikecao** [comment]
@SoftCreatR you have a typo, it's u**m**ami not unami

**Comment by SoftCreatR** [comment]
Oh god... 😸
