### ISSUE TITLE
ISO 8601 for date-time in charts

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#193]
Is it possible to use ISO 8601 notations for date and time in the charts?

I am a firm believer in being able to avoid any "freedom" units, am/pm, nine/elevens or Pi-days and instead use standard ISO units and ways to describe date-time etc.

My programming knowledge is rusty to say the least but point me in a direction and I can always mimic others.

Best regards
//A

**Comment by mikecao** [comment]
I actually prefer the friendly format. They get localized into the proper format depending on your locale anyways.

**Comment by andlil** [comment]
Sure, just a suggestion :-)

However they don't get localized for me with sv_SE-settings, it still shows 1PM and not 13.

**Comment by mikecao** [comment]
Hmm, it should localize, this is what I see

![image](https://user-images.githubusercontent.com/477975/93733726-6f075980-fb8b-11ea-8ae1-fb95cc9d09d3.png)

Maybe wait for the next release

**Comment by andlil** [comment]
Now I see, it looks like that for me too. I thought the charts would localize without changing language, my bad.
