### ISSUE TITLE
[Roadmap] Dark mode

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#195]
This is already available in the `dev` branch. Just waiting on a few things to do a new release.

![image](https://user-images.githubusercontent.com/477975/93733283-bbea3080-fb89-11ea-9e5c-a61abab317b5.png)

**Comment by mikecao** [comment]
Released in #199

**Comment by hugomd** [comment]
Great work on this release @mikecao! 👏🏻

**Comment by MoltenCoffee** [comment]
Awesome!
