### ISSUE TITLE
No data in charts in Safari on MacOS/iOS in today and 24 hr view

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#198]
No data is shown in the charts when using Safari on MacOS/iOS and using today or 24 hr view, if I change to "this week" or any other time span there is data shown.

iOS 14 and Safari Version 14.0 (15610.1.28.1.9, 15610) on MacOS Catalina 10.15.6 (19G2021)

I can't see anything wrong in Safaris console when loading the page.

![Skärmavbild 2020-09-21 kl  17 21 49](https://user-images.githubusercontent.com/10003475/93786197-4c2e8100-fc2f-11ea-9006-770f7b5d0b7e.png)
![Skärmavbild 2020-09-21 kl  14 25 12](https://user-images.githubusercontent.com/10003475/93786239-5badca00-fc2f-11ea-8578-6991dbb8741e.png)

**Comment by mikecao** [comment]
Looks like Safari date handling is a bit different.

**Comment by mikecao** [comment]
Pushed out a fix. Can you try the latest?

**Comment by andlil** [comment]
All good now!
