### ISSUE TITLE
Netlify support

### ISSUE THREAD

**Issue by HassanCorrigan** [mikecao/umami#203]
Reading through the [docs](https://umami.is/docs/hosting) I noticed Netlify is listed as one of the sites available to host Umami. I've tried a few times now and cannot seem to get it up and running with Netlify. I've tried running it directly and using the [next-on-netlify](https://github.com/netlify/next-on-netlify) package but keep running into errors.

Just wondering if there is actually a way to host Umami on Netlify, I've tried Vercel and everything works fine but all my other projects are hosted with Netlify and would like to keep things together.

Using next-on-netlify gave me an error related to a missing aws-sdk package, installing netlify-cli as a dependency to Umami allowed me to bypass that and build the site but once I try to login I get an error related to a missing /package.json file. Not sure if I'm doing things wrong as this is my first time using a Next JS project, any help would be appreciated.

Really love the project and great work in such a short time.

**Comment by mikecao** [comment]
There is a problem with Next.js at the moment. I filed a bug here https://github.com/vercel/next.js/issues/16618

**Comment by HassanCorrigan** [comment]
> There is a problem with Next.js at the moment. I filed a bug here [vercel/next.js#16618](https://github.com/vercel/next.js/issues/16618)

Thanks for the update Mike, good to know it’s not just me. Appreciate the hard work.

**Comment by the-mcnaveen** [comment]
Following this issue.

**Comment by meirroth** [comment]
News: Next.js on Netlify, now with zero configuration required.
Source: https://www.netlify.com/blog/2021/03/16/try-the-new-essential-next.js-plugin-now-with-auto-install/

@mikecao, Does this change anything in regards to running umami on Netlify?
