### ISSUE TITLE
Docker image size is 1.17 GB

### ISSUE THREAD

**Issue by hugomd** [mikecao/umami#204]
The docker image size is 1.17 GB, which seems pretty huge!

I've inspected the image, and it looks like 411 MB is yarn cache, so I'll raise a PR to clean that up.

These are the larger dependencies in `node_modules`:
```
 10M    ./next
 13M    ./timezone-support/util
 13M    ./timezone-support/util/data
 15M    ./@formatjs/intl-displaynames/locale-data
 17M    ./rxjs
 20M    ./date-fns
 21M    ./@formatjs/intl-numberformat/locale-data
 22M    ./@formatjs/intl-numberformat
 22M    ./timezone-support
 28M    ./@formatjs/intl-displaynames
 49M    ./typescript/lib
 52M    ./typescript
 55M    ./@formatjs/cli
 55M    ./@formatjs/cli/node_modules
 55M    ./@formatjs/ts-transformer
 55M    ./@formatjs/ts-transformer/node_modules
 57M    ./@prisma/cli
 58M    ./@prisma
 73M    ./geolite2-redist/dbs
 74M    ./geolite2-redist
170M    ./@formatjs
```

I think most of them are required, but I wonder if there's some that could be replaced with smaller counterparts. `formatjs` in particular takes up a lot of space 🤯 

I just wanted to open this for discussion, I think removing the yarn cache will be worthwhile though! ✌🏻

**Comment by hugomd** [comment]
I've done some more digging and I think there's some more space saving to be made by excluding dev dependencies from the Docker image, although they're required to build. I've started working on a multi-stage image which should hopefully take this into account!

**Comment by mikecao** [comment]
`formatjs` is what runs the translations. But the `cli` is only required to build the language files. After that it's not needed.

`geolite-2-redist` is needed for the country IP lookup

`prisma` is database access. Not sure about the `cli` in this case though.

Everything else is probably needed in some way.
