### ISSUE TITLE
Umami  doesn't capture search term of search route.

### ISSUE THREAD

**Issue by kwstaskara** [mikecao/umami#208]
So I have a react-router route like this :
`<Route path="/search" element={<Results/>}/>`
So if I search let's say for the term "news" the route is exactly this "/search?q=news" but umami logs only "/search" without "?q=news"  on page section.
Versions
"react": "^16.13.1"
"react-router": "^6.0.0-beta.0"
Umami v0.48.0
If I find some time i will test this locally to find out what the problem might be.

**Comment by mikecao** [comment]
You need to go to `More` then click on the `Raw` filter.

**Comment by kwstaskara** [comment]
> You need to go to `More` then click on the `Raw` filter.

There isn't "More" button 
![Screenshot 2020-09-23 211505](https://user-images.githubusercontent.com/18183813/94052665-edf5cf80-fde1-11ea-8efb-7c2e7c061d16.png)

**Comment by mikecao** [comment]
The raw filter will show you that. By default it show you the combined view. I need to make the More button always appear.

**Comment by mikecao** [comment]
Try pulling the latest. The More button should appear now.

**Comment by kwstaskara** [comment]
Yes everything is fine now 😊 so only the button was missing.
