### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by jkyngan** [mikecao/umami#21]
currently it only load from http://.
please add https support.

**Comment by mikecao** [comment]
See https://github.com/vercel/next.js/discussions/10935

**Comment by nodesocket** [comment]
You'll want to have a web server like NGINX or even easier [Caddy](https://caddyserver.com/) in front of umami. Those can serve https and terminate SSL and then reverse proxy pass to umami over http.

**Comment by SoftCreatR** [comment]
https://www.digitalocean.com/community/tools/nginx?domains.0.php.php=false&domains.0.reverseProxy.reverseProxy=true&domains.0.routing.root=false

Works well.

**Comment by martin-ro** [comment]
@SoftCreatR thanks, that saved me some time. Works like a charm on the standard DigitalOcean LEMP droplet.
