### ISSUE TITLE
Storing search term analytics from search engines

### ISSUE THREAD

**Issue by parthp1808** [mikecao/umami#211]
Other analytics also show which terms are most popular among traffic from search engines and other related metrics. That would be very helpful in Umami.

**Comment by parthp1808** [comment]
Thanks for the detailed response. I now get it why it's not possible. I read how matomo is doing it and realised that there is a way to connect Google Search console via api and fetch data. I guess not 100% accurate but still somewhat reliable and helpful

**Comment by mikecao** [comment]
Won't be pursuing this for now.
