### ISSUE TITLE
[Question] What is counted and what is displayed?

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#215]
In the statistics below the sum of known metrics is 63 for each type, how does that relate to the number of visitors (in this case 124)?
Are three visitors on ios using safari counted as one of 63 and not three of 63? Beacuse according to other sources of statistics around 75% of my visitors use ios, not 43%

![Skärmbild 2020-09-24 112242](https://user-images.githubusercontent.com/10003475/94127804-a6ab2580-fe59-11ea-9002-4d6c19cd1e72.png)

**Comment by mikecao** [comment]
It looks like the query is not correct. This is a bug.

**Comment by andlil** [comment]
After starting with a clean database the numbers do add up.
