### ISSUE TITLE
Update postgresql database to support ver 13

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#218]
Logs from postsgresql (postgres:alpine)

 `PostgreSQL Database directory appears to contain a database; Skipping initialization`
`2020-09-25 05:21:26.011 UTC [1] FATAL:  database files are incompatible with server`
`2020-09-25 05:21:26.011 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0.`

Temporary fix for docker users is to stay on 12 #217

**Comment by mikecao** [comment]
Not sure what the solution is here since the user would have to dump all their data and re-import into 13. We may have to stay on 12.

**Comment by hugomd** [comment]
I think it's best to pin it to 12. If users want to use 13, they can choose to manually migrate.

I see the `docker-compose.yml` file as an easy way to spin up Umami to test it out, and potentially to deploy as well, but it's up to the user to manage that deployment.

**Comment by MonksterFX** [comment]
Yeah this is a standard deployment task to pin versions.

**Comment by andlil** [comment]
Sure, I only have 5 days worth of data so I will most likely dump the database and spin up a completely new based on version 13. Hopefully there are not too many docker users experiencing this who can't either pin to 12 or upgrade to 13. Time will tell...
