### ISSUE TITLE
502 Error at /api/collect

### ISSUE THREAD

**Issue by ShubhamVerma1811** [mikecao/umami#229]
![Screenshot (207)](https://user-images.githubusercontent.com/25576658/94357030-e0c33400-00b2-11eb-94b8-252dffe6380b.png)

**Comment by mikecao** [comment]
Coincidentally, I was just working on this. Try pulling the latest from master.

**Comment by ShubhamVerma1811** [comment]
> 
> 
> Coincidentally, I was just working on this. Try pulling the latest from master.

Looks like its working. 👍

**Comment by mikecao** [comment]
I don't get that error at all. What is the entire stack trace?

**Comment by ShubhamVerma1811** [comment]
What is that?
How do I check stack trace?

**Comment by mikecao** [comment]
Click Show Details and copy the entire error.

**Comment by ShubhamVerma1811** [comment]
I am getting second error sometimes and there is no option to view its details.

![Screenshot (218)](https://user-images.githubusercontent.com/25576658/94508887-9d8ecf80-0230-11eb-8a6a-f34257b329b4.png)

**Comment by mikecao** [comment]
The browser won't show you the error, you have to do it in Vercel

![image](https://user-images.githubusercontent.com/477975/94509785-f9723d80-01c9-11eb-858c-d8c14b6bf299.png)

**Comment by ShubhamVerma1811** [comment]
It says "Awaiting new response" and show details button is disabled.
Also, there are many deployments with different names but I don't see deployment for my production URL.

**Comment by mikecao** [comment]
Then you need to send a response to trigger an error.

**Comment by ShubhamVerma1811** [comment]
![image](https://user-images.githubusercontent.com/25576658/94514308-80f99400-023e-11eb-89e2-64c513ca8e14.png)
![image](https://user-images.githubusercontent.com/25576658/94514262-658e8900-023e-11eb-9cbf-fdb1b757695a.png)

**Comment by mikecao** [comment]
These are all database connection errors. You can try restarting your database. But it's unrelated to the original error you posted.

**Comment by ShubhamVerma1811** [comment]
I get 502 Error too.
I think when the above db error occurs, then I get the 502 Error,
Anyways, If that's the case you can delete/close this issue,
