### ISSUE TITLE
Share websites between accounts

### ISSUE THREAD

**Issue by selcukusta** [mikecao/umami#230]
Hi,

When the new account is created, a unique dashboard is created at the same time. It's OK. But I wonder that, how can I share the website with the new account? For instance, 3 people want to get metrics for the same site. How can we handle that?

**Comment by mikecao** [comment]
https://umami.is/docs/enable-share-url

**Comment by selcukusta** [comment]
But it's creating public sharable url. I just want to share the url with authenticated user who has own dashboard.

**Comment by mikecao** [comment]
The url is random so nobody should be able to guess it. Do you mean you want the website to appear on their dashboard?

**Comment by selcukusta** [comment]
Yes, exactly I mean that.

**Comment by mikecao** [comment]
You'll have to use the share URL, that is it's purpose. Anything else would require too many changes to the back-end.

**Comment by t3brightside** [comment]
I think Share URL is not a safe feature to recommend in hope that nobody else will get their hands on the link.
If something is meant for a certain pair of eyes only it should be protected by authentication.

Understandably lot of work to make user rights handling happen but I don't see the Share URL as an alternative in same sense.

It's and excellent piece of software thou :)
