### ISSUE TITLE
[Performance] Tracking script API responses slow in newer releases

### ISSUE THREAD

**Issue by dakshshah96** [mikecao/umami#235]
I just updated to the latest release (hash: `241156d9eee9f029e4940ed0e6892e538afe6f62`) and noticed that my web app where I've added the Umami tracking script has considerably slowed down. A quick look at the Networking tab in Chrome reveals that the requests made by the tracking script to `https://mywebsite.com/api/collect` now takes around 4-5 seconds to receive a response instead of milliseconds it used to take before.

To test this, I rolled back to a previous commit (hash: `418a24deb762b95ace7d6f963a811d925ea9aee3`) without touching any other server or database settings. The requests immediately sped up and response times changed to less than 100ms.

Sharing some screenshots below of the requests made from the same page on my web app before and after switching to the older release.

**New release**:

![Screenshot 2020-09-30 at 3 09 29 PM](https://user-images.githubusercontent.com/7896438/94670311-0610a600-0330-11eb-8882-b8f5c9c3c45b.png)
![Screenshot 2020-09-30 at 3 09 20 PM](https://user-images.githubusercontent.com/7896438/94670324-090b9680-0330-11eb-98ff-8f050faba24f.png)

**Old release**:

![Screenshot 2020-09-30 at 3 12 28 PM](https://user-images.githubusercontent.com/7896438/94670425-29d3ec00-0330-11eb-843d-ef5597892b1b.png)
![Screenshot 2020-09-30 at 3 12 14 PM](https://user-images.githubusercontent.com/7896438/94670435-2c364600-0330-11eb-9853-96f2c0df86aa.png)

**Comment by mikecao** [comment]
I need more details. What database are you using, where are you hosting, etc.

**Comment by dakshshah96** [comment]
Sorry for the missing details!

**Database**

1 GB RAM, 1 vCPU, 40 GB SSD
PostgreSQL database (12.3)
Amazon Lightsail

**Node.js server**

2 GB RAM, 1 vCPU, 60 GB SSD
Ubuntu
Amazon Lightsail

**Comment by mikecao** [comment]
Only major thing that changed was the upgrade to prisma. You can try this, add `LOG_QUERY=1` to you `.env` file and run in dev mode. It should print out the queries and how long they are taking.

**Comment by mikecao** [comment]
Closing this one. Track in #263
