### ISSUE TITLE
[Update] dotenv prisma generate fails with i/o error

### ISSUE THREAD

**Issue by fvsch** [mikecao/umami#236]
I don't know if updating in place is supported, but I tried updating between v0.54.0 and v0.62.0 via git:

```
$ git pull origin master
$ npm install
$ npm run build
```

The `dotenv prisma generate` failed with:

```
Error: EIO: i/o error, copyfile '/sites/umami/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x' -> '/sites/umami/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
```

File and folder permissions looked alright. It looked like it was failing because the file already exists, and it does not try to clean it up before.

I worked around it with `rm node_modules/.prisma -rf` before running `npm run build`.

Again, I'm not sure updating that way is intended, so feel free to close this issue if it's not.

PS: Thanks for building Umami!

**Comment by mikecao** [comment]
You have to stop the application before running the build. The build replaces the database driver which would be in use if the application was running.

**Comment by fvsch** [comment]
Thanks for the information!
I’m not getting the same error again on subsequent updates, not sure why.

I think it’s safe to close this issue.
To sum up the solutions if someone runs into something similar:

1. You may have two processes running: a Node process running `node_modules/.bin/next start`, and a second one for `node_modules/.prisma/client/query-engine-debian-openssl-1.1.x` (or a similar executable, depending on your platform). You probably need to stop those before running `npm run build` again.
2. Deleting the `node_modules/.prisma` folder seems to work too, though it's not super clean.
