### ISSUE TITLE
TypeScript and/or Tailwind support?

### ISSUE THREAD

**Issue by acoard** [mikecao/umami#238]
Hi Mike,

Really love this repo and can see making some contributions to it.

How do you feel about TypeScript and/or Tailwind support?  I'm willing to put in the time on these, but wanted to check it's okay before investing time and submitting a PR.

Specifically, I'm talking about:

* Converting most the .js files to .ts,  and  adding a  `tsconfig.json`
* Adding TailwindCSS as dependency,  a `tailwind.config.json`
* If you use VSCode, helping you set up TypeScript support, intellense, etc, can configure debugger scripts (if you want).

I wouldn't do this in one go.  Rather, as I add new files, or edit existing ones, I'd convert them from `.js` to `.ts` and add appropriate types.  I'd do the same with CSS classes and Tailwind.  Once it was at a sufficient level, then I'd submit a PR (60.  I wouldn't propose to change every single file.  Build scripts and self-contained files that just work are fine to leave and co-exist with .ts files.  But anything that gets refactored much or deals with state would get typed.

If you're on the fence or wanna hear more, I'm happy to chat; but I figure you already know about TypeScript and TailwindCSS. 
 Though I will mention both  [NextJS](https://nextjs.org/docs/basic-features/typescript) and [prism](https://www.prisma.io/docs/getting-started/quickstart-typescript) have first-class TypeScript support.

So... what do you think?

**Comment by mikecao** [comment]
Hi, I really appreciate the support. To be honest, I haven't used Typescript much. I understand its benefits but I don't have enough experience with it to want to convert over. I'd at least have to try it on another project first. I don't want to sacrifice development velocity at this point.

As for tailwind, I tried it out and it wasn't for me. I prefer just writing my own css classes.

**Comment by acoard** [comment]
Hey Mike, thanks for the quick response.  I get where you're coming from.  To be honest, I'm not sold on Tailwind either, I'm just a fan of how you can easily re-theme.   TypeScript on the other  hand I think is a great benefit for almost every JS project.  I'll make the case for TypeScript below, but at the end of the day I'll respect your decision.

I get your point about  not wanting to sacrifice velocity, but I don't think you'd  sacrifice much. TypeScript is  very low friction and you can use as little or as much as you want. One of TS's main advantages is how you can incrementally adopt it and it co-exists with JS  just fine.  If you get in the flow and just wanna right JS and ignore TS, you can always do that.

I'll give you an example where this benefits.  Right now I'm writing some load-testing tools, we can run a script and get thousands of  requests and monitor performance. (I have issue #66 in mind)  I had to mock out the pageview JSON by looking  at  what is sent and copying it.  With TypeScript, presumably we'd have a type like this:

```ts
interface PageviewPayload {
    type: 'pageview'
    payload: Payload   
}

interface Payload {
    website: string,
    hostname:  string,
    screen:  string,
    url: string
}
```

This is basically the same as `schema.prisma`, just a slightly different syntax.  And this is  basically all you need to know about TypeScript.  There is more to know, but you don't need to worry about it to get value from TS.

Not only are these types a blueprint on how I should implement it, but they help with refactoring and reducing bugs too. Let's say you were to modify the shape of the  payload, adding a new property.  With TypeScript, editor and compiler would automatically tell you every place you need to change and what is missing.  Without TypeScript,  you have to mentally know or just test the application. Types sort of function as unit tests in a way, but they're easier to write and directly hook into your editor.  TypeScript would let the compiler check that the database, server, and frontend all expect the same "shape" of data.  If you deleted a column from the DB, VSCode could point out each place in the front-end which references the now missing field.

And you'd still be completely free to just create a `.js` file and write normal JS there.  They can co-exist in same code-base with 0 problem.  You can import a .ts from a .js file.

Anyways, I understand and 100% respect  if you don't  want to go with TypeScript, but figured I'd make the case before I drop it.

**Comment by mikecao** [comment]
Ok, can you maybe start a small PR with just a few typescript changes so I can try it out?

**Comment by ncovercash** [comment]
It would be awesome to have a typings file that just states what parameters/methods are available in the `umami` namespace.  With this, people who are using typescript would be able to take advantage of all the type-related features (autocompletion, error checking, etc) without umami itself having to convert.

I might take a crack at this and add it to https://github.com/DefinitelyTyped/DefinitelyTyped (the standard repository for type information of non-typescript packages)

**Comment by ncovercash** [comment]
@acoard @mikecao I made a PR to DefinitelyTyped with type declarations for `umami`.  Would one of you please review [the PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49453) to make sure it looks good?
