### ISSUE TITLE
Anti Virus software picking Umami.js as Virus

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#241]
Hello, 

My antivirus just blocked my umami website because they found threat on `umami,js` file. See screenshot. 

What could be the reason? I added the code for two websites of mine so far. 

![image](https://user-images.githubusercontent.com/1884712/94782594-15075f00-03e9-11eb-9227-3f9d67d8f3d9.png)

**Comment by hugomd** [comment]
It sounds like Umami has been added to a deny list somewhere, presumably to disable analytics. 

I'm not sure why Avast would pick that list up though.

It might be worth getting in touch with Avast directly and finding the source list.

**Comment by surjithctly** [comment]
I have asked them to remove from blacklist. Let's see their reply.

**Comment by hugomd** [comment]
@surjithctly Just following up, did you get a response from them?

**Comment by surjithctly** [comment]
Hello,

yes. I received the message. Sorry! Forgot to update here.

> Hello,
> 
> Thank you for reporting this false positive.
> 
> Our virus specialists have now cleared its reputation in our database.
> 
> With URLs this change should be instant, but it might take up to 24 hours with files.
> 
> For future reference you might also find the following article to be useful: Avast Clean Guidelines.
> 
> 
> Best regards,
> 
> Avast Customer Care

Its started working again.
