### ISSUE TITLE
Any way to ignore an IP address or anyway exclude my visits?

### ISSUE THREAD

**Issue by vitobotta** [mikecao/umami#243]
Hi!

I was looking for some self hosted analytics and this looks super cool and was easy to install :)

Is it possible to somehow tell Umami to ignore an IP address, or somehow to ignore my visits? For example Fathom doesn't allow you to ignore an IP explicitly, but it lets you disable tracking for a browser with JavaScript. Is this possible with Umami?

Thanks!

**Comment by mikecao** [comment]
You can disable automatic tracking and send the events yourself in Javascript. See https://umami.is/docs/tracker-config.

In order to ignore an IP, it would have to be done on the server side. I might be possible to do it via an environment variable.

**Comment by vitobotta** [comment]
Hi @mikecao , sorry for the delay. Thanks for adding the IP filter! :)

**Comment by LushawnDev** [comment]
Is there no way to do this if you are hosting with Umami cloud then? As I don't believe there is a way to set environment variables.

It'd be great if there was an easy way to block tracking when I view the site. Maybe a cookie or something I could set in my own browser to say not to track? Any suggestions would be great thank you!

**Comment by mikecao** [comment]
@LushawnDev you set `umami.disabled` in your local storage

**Comment by WayOfTheKatana** [comment]
> [@LushawnDev](https://github.com/LushawnDev) you set `umami.disabled` in your local storage

but I don't see any umami.disabled on my local storage though.

**Comment by LushawnDev** [comment]
> but I don't see any umami.disabled on my local storage though.

@WayOfTheKatana  You create the item in local storage yourself, either

1. Type into a new row of local storage, putting `umami.disabled` in the key column and set it's value column to `true`
2. Run this in the console while on the site you are trying to block tracking, it will set the local storage item for you: `localStorage.setItem("umami.disabled", "true");`

**Comment by WayOfTheKatana** [comment]
> > but I don't see any umami.disabled on my local storage though.
> 
> [@WayOfTheKatana](https://github.com/WayOfTheKatana) You create the item in local storage yourself, either
> 
> 1. Type into a new row of local storage, putting `umami.disabled` in the key column and set it's value column to `true`
> 2. Run this in the console while on the site you are trying to block tracking, it will set the local storage item for you: `localStorage.setItem("umami.disabled", "true");`

Nice, it worked.
