### ISSUE TITLE
Redirect on HTTPS

### ISSUE THREAD

**Issue by KonstantinReido** [mikecao/umami#250]
Is it possible to force Umami to redirect on HTTPS URL when a user visits an insecure HTTP URL?

**Comment by mikecao** [comment]
Umami doesn't know anything about the environment it's hosted on. You will have to configure it on your web server.

**Comment by KonstantinReido** [comment]
Heroku tells that this task should be solved on application level

https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

**Comment by mikecao** [comment]
Maybe something like this will work, https://www.npmjs.com/package/redirect-ssl
