### ISSUE TITLE
Persist the selected time range across page refreshes

### ISSUE THREAD

**Issue by fvsch** [mikecao/umami#255]
See https://github.com/mikecao/umami/issues/155#issuecomment-702391188 for start of discussion.
I’m interested in tackling this.

@mikecao I’m wondering if:

1. The remembered time range should be global (all sites) or per-site?
2. We should remember it invisibly in localStorage, or visibly as a query string parameter (which could help when sharing)?

**Comment by mikecao** [comment]
1. The time range is already per site. It defaults to global if nothing has been set. Take a look at the `useDateRange` hook.
2. Just local storage for now. Pulling from the query string will require a lot more work.

**Comment by fvsch** [comment]
I’m looking at ways to save per-website prefs as a stringified object in localStorage:

```
{
  "1": "1month",
  "2": "2020-09-30T22:00:00.000Z/2020-10-31T22:59:59.999Z"
}
```

To avoid growing this object needlessly, I wanted to use the keys from the `websites` object in the Redux store, but in my tests this object is almost always empty. The `/api/websites` route is called on different views, but the information it returns is not cached in redux and the only time code writes to `state.websites` object is when we save a website's dateRange in Redux.

So in typical usage, `state.websites` will be:

```
{}
```

or If I changed a site's dateRange, it might look like:

```
{
  1: {
    dateRange: {
      startDate: "2020-09-30T22:00:00.000Z",
      endDate: "2020-10-31T22:59:59.999Z",
​​      unit: "day",
​​      value: "1month"
    }
  }
}
```

So getting a list of known `websiteId`s from Redux is not an option.

I could probably ignore that and just write to an object in localStorage, schematically:

```js
const dateRanges = JSON.parse(localStorage.getItem('umami.date-range'));
dateRanges[websiteId] = dateRangeToString(values);
localStorage.setItem('umami.date-range', JSON.stringify(dateRanges));
```

Since the `websiteId` are `"1"`, `"2"`, `"3"`, etc., I guess it wouldn't grow too large.
Does that sound sensible?

I also need to account for the default date range (which can be set in `/settings/profile`), currently stored in `'umami.date-range'`. We probably don't want to overwrite that. So maybe use a different key for per-site configs (e.g. `'umami.website-date-range'`), or migrate it to a `default` key on an object (a bit riskier).

**Comment by mikecao** [comment]
All you need to update is the `useDateRange` hook. Replace all the redux calls with local storage. Instead of this:
```
const dateRange = useSelector(state => state.websites[websiteId]?.dateRange);
...
dispatch(setDateRange(websiteId, values));
```
Instead do:
```
const dateRange = getItem(`${DATE_RANGE_CONFIG}.${websiteId}`);
...
setItem(`${DATE_RANGE_CONFIG}.${websiteId}`, values);
```
So the local storage key will be something like `umami.date-range.1`.

The other piece of logic is if they click the Reset button in Profile, you should delete all the website specific entries.

**Comment by mikecao** [comment]
Closing for now. We can tackle this in the future if needed.
