### ISSUE TITLE
 After deploying 0.67.0 a response time significantly increased

### ISSUE THREAD

**Issue by KonstantinReido** [mikecao/umami#256]
As you can see from the screenshot it changed from millisecond to seconds.

<img width="1197" alt="Screen Shot 2020-10-01 at 23 49 27" src="https://user-images.githubusercontent.com/172571/94899490-1a71b180-049c-11eb-91fd-b5fe3e5228e5.png">

**Comment by mikecao** [comment]
This is likely due to the prisma upgrade. You can try rolling back to pre-v0.62.0. I might have to roll back the upgrade or get rid of prisma altogether and use something else.

**Comment by mikecao** [comment]
See #263

**Comment by mikecao** [comment]
Track discussion in #263
