### ISSUE TITLE
Avoid sending Personally Identifiable Information (PII)

### ISSUE THREAD

**Issue by KonstantinReido** [mikecao/umami#257]
In my case, some URLs contain secret tokens that shouldn't be visible via Umami dashboard

Checkout [Best practices to avoid sending Personally Identifiable Information (PII)](https://support.google.com/analytics/answer/6366371?hl=en) section "Page URLs and titles"

Is it possible to have something like this in umami?

**Comment by mikecao** [comment]
Well you should never be sending secret tokens in the URL. That said, I do need to redo the page queries since it's causing a performance issue.

**Comment by KonstantinReido** [comment]
I think in Umami you also have something like this, it's URLs to share temporary access to some pages of our system. I don't see another solution than using some secret in URL.

Will be good if I can somehow control what umami sends to its backend.

**Comment by mikecao** [comment]
You can do that by writing your own tracker function, https://umami.is/docs/tracker-functions

It's not possible for umami to know what urls to filter or not.
