### ISSUE TITLE
Struggling to set up with Heroku

### ISSUE THREAD

**Issue by sebzapata** [mikecao/umami#259]
Hi,  
I have a website which I would like to use Umami with.   
I have followed [the installation guide](https://umami.is/docs/install) and I am able to get the analytics running locally, but when I attempt to follow [this guide here](https://umami.is/docs/running-on-heroku) to have it running on Heroku, I am struggling.  
I followed the guide and completed the first 'Website' section OK. I believe I have completed the second 'Database' section too, although this is my first time using Postgres and I am not sure how to confirm it is fully set up. I am also confused as to whether I should be cloning the umami repository with the link they give, or the one I forked earlier. When I create the `.env` file, should this be pushed up to git or not?    
In the third 'Build and Deploy' section, this is where it definitely fails. I am able to get a successful deployment, but I get an error stating "An error occurred in the application and your page could not be served." when I try to open it.

Any help would be much appreciated.  
Thanks

**Comment by mikecao** [comment]
Can you try starting with the `start-env` script?

**Comment by sebzapata** [comment]
When I run that, I get  

```
> node scripts/start-env.js

info  - Loaded env from E:\Code\umami\.env
ready - started server on http://0.0.0.0:3000
```

And when I go to that  link, it says "This site can’t be reached"

**Comment by KonstantinReido** [comment]
@sebzapata you don't need to push .env. Add required values as env variables https://devcenter.heroku.com/articles/config-vars

Also, you can find useful my comment https://github.com/mikecao/umami/issues/231#issuecomment-702247661

**Comment by sebzapata** [comment]
The `DATABASE_URL`  & `HASH_SALT` were already added to the Config Vars. Following what you suggested in your comment hasn't fixed it either. 

I started fresh from the "Running on Heroku" guide, in hopes that may help.
I followed the Website section, and that is all fine. The app I created on Heroku, is linked to my forked repository.
I then add on Heroku Postgres via Resources.
From there, I jump straight to the "Create database tables" section of the Install docs.
With the `psql -h hostname -U username -d databasename -f sql/schema.postgresql.sql` step, I am unsure on where to execute this. I originally did it on the locally cloned repository that I forked earlier, but I feel that's not correct. 
Where should this script be run?

Thank you both for your advice, could you please advise if what I have done so far is correct and whether I need to have a local copy of the repo on my computer which I push changes I make from.

Thank you

**Comment by mikecao** [comment]
@sebzapata The sql script can be run from anywhere as long as it can connect to your database and create the tables. It only needs to be done once.

**Comment by KonstantinReido** [comment]
@sebzapata Yes, I also misunderstood this moment and spent some time to find how to do it.

So what you need to do is next:
1) On Resources tab (on Heroku) open Postgres
2) On Postgres add-on page open Settings tab
3) You need `View Credentials…` button

There you can find `hostname`, `username`, `databasename`. So using this information you can locally run `psql` and local SQL script from `sql` folder and apply it on your remove DB.

**Comment by sebzapata** [comment]
Thanks again for your help.
So the first 2 steps of the Heroku setup guide were completed as they should have been. I was doing some additional steps that I didn't need, such as creating a `.env` file, but what the deployment needed was there.
Did the tutorial again, but using Postgres v12 instead of v13 and it's now working. I did have to follow your advice from the comment @KonstantinReido too.

Not sure if changing to v12 is the reason it's working, or if it's because of something else, but thought I would let you know.

Cheers!
