### ISSUE TITLE
Error 502: API Collect

### ISSUE THREAD

**Issue by parthp1808** [mikecao/umami#260]
Umami was working perfectly since last few days but today suddenly it stopped working and I am seeing below error in Vercel.

![image](https://user-images.githubusercontent.com/13503697/94927332-18095a80-0490-11eb-9403-70dcdef72100.png)

I might try rebuilding it but maybe issue is something else?

**Comment by parthp1808** [comment]
I merged few commits from master and rebuild ~ it fixed it. Though I still have no idea what occurred this in first place. Maybe worth checking into.

**Comment by mikecao** [comment]
It's because the older package downloads files, but Vercel is not writable after deployment. If you rebuild it will download the files at build time. Since v0.62.0 umami switch to using local files without the need for download.
