### ISSUE TITLE
[Discussion] Prisma performance

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#263]
A couple users have reported slower performance since the Prisma upgrade to v2.8.0 in the v0.62.0 release. If you are having issues, here is what you can do to troubleshoot.

1. Add `LOG_QUERY=1` to your `.env` file.
2. Run in dev mode, `npm run dev`.

This will print out the queries being run and their times. The logs will look like this:

![image](https://user-images.githubusercontent.com/477975/94963033-544ab400-04ac-11eb-8b3b-c498e8a122e4.png)

You can try rolling back to a previous version and comparing your results.

Another change was disconnects were added since the upgrade. Under `/lib/queries.js` there is this method:

```javascript
export async function runQuery(query) {
  return query
    .catch(e => {
      throw e;
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
```

You can try removing the entire `.finally` block and see if that helps.

Note that I am always using the latest umami version for my own websites. So far I have not encountered any performance issues myself so it is hard for me to troubleshoot.

Since Prisma is out of my control, you can try submitting an issue with them if you find anything specific to your setup. 

https://github.com/prisma/prisma

**Comment by dakshshah96** [comment]
@mikecao I can confirm that removing the entire `.finally` block from the `runQuery` function in `/lib/queries.js` fixes all the performance issues.

Requests are back to a few milliseconds.

**Comment by winterrific** [comment]
Commenting this part out helped also for me. Thank you guys. 

I Upgrades also to the latest postgres:alpine version to figure out if prisma is working better with the newest version. But this has no effect. 

Environment: Ubuntu V-Server, umami und postgres:alpine docker container behind nginx proxy.

**Comment by mskian** [comment]
after removing `.finally` works well
it solves that error page issue #252

**Comment by mikecao** [comment]
Ok, I will probably remove that code in the next release, or at least make it configurable.

**Comment by pantharshit00** [comment]
If you will call `prisma.$disconnect` per request, it will tear the query engine binary and stop the database pool per request.

Starting those again is a very expensive operation, the prisma client will need to spawn the rust binary, acquire a database pool and then serve the request. 

You should probably remove that part completely. 

If you added that code to prevent connection limiting in serverless context, solution for that is using a connection pooler like pgbouncer or rds proxy in front of your database instead of tearing the pool per request.

**Comment by mikecao** [comment]
Ok, removed the disconnect code in the latest release.

**Comment by mikecao** [comment]
@pantharshit00 Is there a way to force prisma to disconnect without tearing down the connection pool and engine? I tried using prisma with pgbouncer but the performance was much worse.

**Comment by pantharshit00** [comment]
@mikecao Were you using pg_bouncer in transaction mode? If not please do that.

We are missing documentation for it right now, so you can refer to this issue: https://github.com/prisma/docs/issues/443

If that still doesn't solve the issue, report back, we can have another look. 


> Is there a way to force prisma to disconnect without tearing down the connection pool and engine?

Hm, I am not sure what you mean. If we don't tear the pool, what we are disconnecting.
