### ISSUE TITLE
Bug/usability language selection on smaller screen 

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#265]
If I change language on a mobile device with a smaller screen not all languages are displayed. This is in landscape, even fewer choices in portrait mode.
![IMG_0129](https://user-images.githubusercontent.com/10003475/94986732-5ae73300-0561-11eb-9e37-dd48bafab1ca.png)

Perhaps rethink #262?

**Comment by mikecao** [comment]
Thanks, will take a look.

**Comment by mikecao** [comment]
Fixed in #268
