### ISSUE TITLE
An Unexpected Error has occured while changing timeline.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [mikecao/umami#269]
I see that there are two closed issues with the same title.
But I am getting this error on version 0.72.0. It was not happening on the prev versions.

I couldn't upload a gif more than 10mb so here it's hosted link
https://we.tl/t-A3Fjr31bW6

**Comment by mikecao** [comment]
You only need to post the error text. But from what I can tell from the gif, your database ran out of connections.

**Comment by ShubhamVerma1811** [comment]
The error messages are the same.
DB error. "Error in the connector: Error querying the database: DB error: FATAL: too many connections for role "ikjadqyajrmprc"
But this time it crashes the website which didn't use to happen in prev versions.

**Comment by mikecao** [comment]
I'll see what I can do about better error handling

**Comment by mikecao** [comment]
Should be fixed in latest release with prisma change.
