### ISSUE TITLE
[Feature request] Opt-Out

### ISSUE THREAD

**Issue by SoftCreatR** [mikecao/umami#27]
Due to the legal situation (GDPR) in europe (especially in germany), we need a way to allow the user to opt out from umami, if there's no way to get rid of the cookie, that is being set upon the first visit.

**Comment by gonerator** [comment]
please somebody confirm as I am not entirely familiar with Umami, but only thing I seen Umami create is "umami.session" item in local storage. But I'm not sure if it resets with every session? Please somebody clarify..

If that's the case, then it may be just ok with GDPR. From what I know, GDPR is ok with anonymous tracking when there is no link of identity *between* the sessions. If each session is identified separately, then you don't need consent, opt-out, etc, because you're not doing individual person analytics, rather you are doing anonymous usage statistics.

**Comment by SoftCreatR** [comment]
It creates a cookie that lasts a year.

**Comment by mikecao** [comment]
@SoftCreatR that cookie, `umami.auth` is only for users of the app itself and only after they have logged in. It is never created for visitors to the website.

The data in localStorage is called `umami.session`. Here's basically how `umami.session` works. When a new user hits your website, they make a call to `/api/collect` which will collect the metrics. It will generate a unique hash based on some info. Currently it's website id +  hostname + ip address + user agent + os. That hash along with some non unique or personal data is stored in the database. This is how umami counts unique users and get device metrics. The `umami.session` is then passed back to the user as a validation token. If they go to another page on the website, they will pass the token back, we verify it and determine they've already been recorded. It's purely a performance technique so we don't have to recompute the hash or do a database lookup. We can simply record the pageview.

**Comment by SoftCreatR** [comment]
@gonerator You are right. I made the wrong assumptions.

Thus, i'll close this issue.

**Comment by WebFreak001** [comment]
is there a reason why localStorage is used over sessionStorage?

**Comment by SoftCreatR** [comment]
Local storage can be used over multiple tabs, while session storage needs some kind of a workaround in order to be usable across multiple tabs.

**Comment by david-mears-2** [comment]
> [@SoftCreatR](https://github.com/SoftCreatR) that cookie, `umami.auth` is only for users of the app itself and only after they have logged in. It is never created for visitors to the website.
> 
> The data in localStorage is called `umami.session`. Here's basically how `umami.session` works. When a new user hits your website, they make a call to `/api/collect` which will collect the metrics. It will generate a unique hash based on some info. Currently it's website id + hostname + ip address + user agent + os. That hash along with some non unique or personal data is stored in the database. This is how umami counts unique users and get device metrics. The `umami.session` is then passed back to the user as a validation token. If they go to another page on the website, they will pass the token back, we verify it and determine they've already been recorded. It's purely a performance technique so we don't have to recompute the hash or do a database lookup. We can simply record the pageview.

This tracks the user, so it requires user consent.
