### ISSUE TITLE
seeing umami.auth cookies on all localhost requests

### ISSUE THREAD

**Issue by cbluth** [mikecao/umami#270]
i am seeing `umami.auth` cookies in my requests when developing on `localhost`.

i access my umami instance at `http://localhost:9999`, but i am seeing the cookie on all requests to `localhost`, how do make umami only set the cookie for `locahost:9999` and *not* for `locahost:*`??

**Comment by mikecao** [comment]
https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific

**Comment by cbluth** [comment]
ok, i see, thanks!

i will probably just edit my `/etc/hosts` file to make a special domain locally.
