### ISSUE TITLE
Tracking campaign data

### ISSUE THREAD

**Issue by tombauer** [mikecao/umami#273]
Is it possible to track campaign data like banner or newsletter clicks in umami? With a custom javascript it would be possible to track the data as event, but then it missing some informations because of the limited two params. It would need more params for proper tracking like in google analytics (utm_source, utm_medium, utm_campaign, utm_content). Is a feature like this planned or how could we handle that in umami?

**Comment by mikecao** [comment]
I'm thinking of adding a meta data table so you can store extra information about pageviews and events. It will just be a JSON blob so you can store anything. But I need to think through how it would work with the UI.

**Comment by tombauer** [comment]
Dear mikecao, thanks for the information - that sounds perfect. I am already looking forward to seeing this feature in a future version of umami :-).

**Comment by vitobotta** [comment]
Hi @mikecao ! Any plans to support tracking campaigns in the near future? Thanks!
