### ISSUE TITLE
Change `webanalytics` github topic to `web-analytics`

### ISSUE THREAD

**Issue by nightvisi0n** [mikecao/umami#276]
After I searched for web-analytic tools on github I noticed, that most other projects use the `web-analytics` topic: https://github.com/topics/web-analytics (92 repos vs 30 on webanalytics).  
I therefore propose to change the topic to `web-analytics`, or at least to add this additional topic so umami is appearing next to the other popular projects.

**Comment by mikecao** [comment]
Thanks, I made the change.
