### ISSUE TITLE
How can I reset the admin password from the console?

### ISSUE THREAD

**Issue by SigmundurMorkore** [mikecao/umami#280]
I've lost access to my password due to travelling and switching computers.

Is there a way to change the admin password via the console?

**Comment by mikecao** [comment]
You'll have to update the database directly:

```sql
UPDATE account
SET password = '$2b$10$BUli0c.muyCW1ErNJc3jL.vFRFtFJWrT8/GcR4A.sUdCznaXiqFXa'
WHERE username = 'admin'
```

**Comment by mikecao** [comment]
But it might be a good idea to have a script to do this as well.
