### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by vitobotta** [mikecao/umami#287]
Hi! I saw another couple of closed issues about CORS but I am not sure they are related. Page view seems to be working fine (I can see growing stats etc), but I see this in the console:

```
Access to XMLHttpRequest at 'https://stats.dynablogger.com/api/collect' from origin 'https://www.dynablogger.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

However I have configured all the CORS headers in the web server configuration. What can I do? Does this affect tracking in any way?

Thanks in advance!
Vito

**Comment by vitobotta** [comment]
Forgot to mention that the container's log only shows this:

```
2020-10-09T10:39:07.954377412Z yarn run v1.22.4
2020-10-09T10:39:08.004942908Z $ next start
2020-10-09T10:39:08.217511383Z ready - started server on http://localhost:3000
```

**Comment by vitobotta** [comment]
I have a doubt.... is this because I have set IGNORE_IP to my IP address?

**Comment by vitobotta** [comment]
I tried with a VPN to change the IP address and I don't see the error. So I guess the IGNORE_IP is the reason?

**Comment by hemorej** [comment]
I'm having a similar issue but with only one of my sites tracking with umami, the local development site. The production sites don't have this issue. I'm also using IGNORE_IP

**Comment by mikecao** [comment]
The IGNORE_IP code shouldn't affect anything. But it might be the order of the CORS middleware. Let me try something.

**Comment by mikecao** [comment]
Can one of you try this? In `/pages/api/collect.js`, move the line `await useCors(req, res);` to the top of the function.

**Comment by vitobotta** [comment]
@hemorej I only have one installation of Umami.
@mikecao I am using the Docker version in Kubernetes. I can't find how to edit the file since it's read only and I can't use sudo etc... any suggestions?

**Comment by vitobotta** [comment]
NVM it was a stupid question. I am building the image with the change and will try that way.

**Comment by vitobotta** [comment]
@mikecao It works! I've opened a tiny PR. Thanks for making Umami!
