### ISSUE TITLE
Error on : Could not fetch checksum for GeoLite2-Country

### ISSUE THREAD

**Issue by haryoa** [mikecao/umami#291]
# Description

I suddenly got this error when running umami on production. 

![image](https://user-images.githubusercontent.com/44270140/95674297-64177600-0bd9-11eb-85cf-3d4715874a9b.png)

Then the umami suddenly crashed and it got turned off :(

## How to Reproduce

- I run umami by using docker-compose. 
- I use nginx image to forward HTTPS request (I think it has no effect for this problem. But, I will put this for clarity)

## Suggestion

I think it is caused by using other service. Mind to handle it if it failed to fetch the request?

Thank you :).

**Comment by mikecao** [comment]
You are several versions behind. We no longer use that package.

**Comment by haryoa** [comment]
Ah I see. I will update it then..

Thanks for the answer.
