### ISSUE TITLE
Reset site statistics

### ISSUE THREAD

**Issue by NuroDev** [mikecao/umami#292]
A small but nice quality of life improvement would be to able to reset a websites statistics data.
While yes you can simply delete the site and re-add it to Umami, this will generate a new website ID and require an update and redeployment of the website in question 🙂

**Comment by ShubhamVerma1811** [comment]
> 
> 
> A small but nice quality of life improvement would be to able to reset a websites statistics data.
> While yes you can simply delete the site and re-add it to Umami, this will generate a new website ID and require an update and redeployment of the website in question 🙂

A simple workaround for this can be to truncate DB tables.

**Comment by bokub** [comment]
> A simple workaround for this can be to truncate DB tables.

Unless you have multiple sites and you only want to clear data for one of them

Also, it would be great to have an option to clear old data only. For example:

> Clear data for the following period: 
> - All data
> - Older than X days

**Comment by ncovercash** [comment]
Another option that I would love is the ability for umami to auto-clear data after a week/month/other timeframe and only keep the recent amount of time.  I primarily use umami for its real-time/short-term analytics and have no need for anything longer than that, therefore, would like to save space/database overhead in the long run with something like this.

**Comment by ncovercash** [comment]
> > A simple workaround for this can be to truncate DB tables.
> 
> Unless you have multiple sites and you only want to clear data for one of them

A `DELETE FROM `table` WHERE `website_id`="your-id-here"` would do the job for just one domain, where you would delete from all the tables you want to clear.  You could even get really fancy and JOIN with the `website` table to make comparisons to `domain`, avoiding the extra step of finding the website ID.

**Comment by mikecao** [comment]
Available in v1.22.0
