### ISSUE TITLE
nodejs 12.19.0 : crash node process

### ISSUE THREAD

**Issue by brocorp-dev** [mikecao/umami#293]
Hi everyone, 

OS: Ubuntu 18.04.5
npm version: 6.14.8
nodejs version: 12.19.0

I performed an apt upgrade this morning and an Umami upgrade too, from 0.74 to 0.80 :

`
git pull
npm install
npm run build
npm run start
`
Since this update, we're not able to log in : 
![image](https://user-images.githubusercontent.com/46473786/95731651-d8612080-0c90-11eb-9ccf-57888818e3cd.png)

nginx generate a 502 error. This is the error from terminal output:

`
node[2270]: ../src/node_http_parser_impl.h:529:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
`

nodejs 12.19.0 seems guilty, works perfectly on 12.18.4. 

Be careful!

**Comment by misostc** [comment]
Looks like its related to https://github.com/prisma/prisma-client-js/issues/907

**Comment by misostc** [comment]
Tested now and issue goes away when using Prisma Client version: 2.9.0-dev.66

**Comment by mikecao** [comment]
Yes, for now you will need to downgrade Node until Prisma releases a fix.
