### ISSUE TITLE
WordPress Plugin for Umami

### ISSUE THREAD

**Issue by fransallen** [mikecao/umami#294]
I created a [WordPress plugin](https://github.com/fransallen/umami-wp) for Umami with the aim of integrating its analytics into website easily. And I plan to publish this plugin in the WP Plugins directory. I need suggestions for: features and name.

**features:** what features should this plugin have?
**name:** can I use the name "Umami" or "Umami Analytics" to refer to this project?

Also, what do you think about making this plugin the official WP plugin for Umami?

**Comment by mikecao** [comment]
Yes you can use the name Umami. Official would mean I would have to support it and I don't have the time. But you can add your plugin to the list of links here, https://umami.is/docs/useful-links

**Comment by fransallen** [comment]
Hi Mike, that's very cool!

I'll add the link once it's approved by wp.org
