### ISSUE TITLE
Event Tracking Error - Events not being tracked.

### ISSUE THREAD

**Issue by 9ntonio** [mikecao/umami#295]
I've added click tracking per your documentation where I've added the following to link classes:

<img width="398" alt="Screen Shot 2020-10-13 at 1 30 32 PM" src="https://user-images.githubusercontent.com/2566895/95913269-d4003a80-0d58-11eb-95dc-bdd0269dd538.png">

<img width="444" alt="Screen Shot 2020-10-13 at 1 30 57 PM" src="https://user-images.githubusercontent.com/2566895/95913277-d6629480-0d58-11eb-849c-71a3edebe87d.png">

I am not able to see the tracking on my admin console. Is there something I am missing?

**Comment by 9ntonio** [comment]
My links are anchor tags with href links. I see that your docs reference the use of a button element. Is this an issue of using a `button` vs `a` ?

**Comment by mikecao** [comment]
Looks like this is a bug. The tracker is not allowing uppercase letters in the event name.

**Comment by 9ntonio** [comment]
@mikecao Ahhh makes sense. Sounds like the quick fix is to [86](https://en.wikipedia.org/wiki/86_(term)) any capital letters until the regex is fixed?

**Comment by mikecao** [comment]
I'll try and get a release out tonight with the fix

**Comment by 9ntonio** [comment]
@mikecao Thank you for the fix.
