### ISSUE TITLE
[Translations] Updated strings

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#297]
I will update this wiki page https://github.com/mikecao/umami/wiki/Missing-translations after every release with any missing translation strings. If you would like to contribute any translations for the listed languages it would be greatly appreciated! 🙏

**Comment by acesaft** [comment]
I can have a look at the German translations

**Comment by mikecao** [comment]
Ping @kwstaskara @djrasmusp @SigmundurMorkore @endormi @err931 @rubjo @Leonard1980 @diogotcorreia @dector

**Comment by djrasmusp** [comment]
@mikecao i get to it over the weekend 👍🏼

**Comment by SigmundurMorkore** [comment]
@mikecao I made a PR #323 with new strings

**Comment by AndreasAdler** [comment]
I noticed that the tooltip in the world map is partly untranslated. It always states "{translated country name}: {visitor count} visitors". There is not translation string in the JSON files, so it can't be fixed becaus it's hard-coded. Also, correct pluralization would be nice here, too.
