### ISSUE TITLE
Realtime - how long is a visitor considered "current"?

### ISSUE THREAD

**Issue by vitobotta** [mikecao/umami#302]
Hi! Awesome stuff with the new release. Love it.  I am confused by the visitors counter. For example now on a low traffic site I see from the realtime logs that the last two visits were at 10:18 and 10:19. It's 10:35 now and the visitors count still says 2. 

How long is a user considered "Current"?

Thanks for the awesome project!

**Comment by vitobotta** [comment]
I forgot to mention that the current visitors counter on the normal dashboard gives a different number than that on the realtime view, and seems more realistic/accurate.

**Comment by vitobotta** [comment]
I think I found it - REALTIME_RANGE seems to be set to 30 minutes. Isn't it a bit long? Would it be possible to reduce it and have the client send a ping request every minute or so to signal that the client is still active? I wish I could help but I am not too familiar with JS and the framework in use :(

Thanks!

**Comment by mikecao** [comment]
Current visitor count is visitors in the last 5 minutes. In the realtime dashboard, it's visitors in the selected time range, which now is 30 minutes. Next update you will be able to change the time range for realtime.

**Comment by vitobotta** [comment]
Awesome, thanks!
