### ISSUE TITLE
[ Feature request ] Show favicons next to the referrers

### ISSUE THREAD

**Issue by bokub** [mikecao/umami#311]
Hi,

What do you think about displaying favicons next to the referrers ?

I may be able to work on this if you think the idea is good.

Example screenshot from Plausible Analytics:

![image](https://user-images.githubusercontent.com/17952318/96249956-4ddd3180-0fae-11eb-9af0-613e9983fb6a.png)

**Comment by mikecao** [comment]
I personally don't like the interface cluttered with icons, but it may be something we can make configurable. How would this work? Would you pre-download the icons or do it at runtime?

**Comment by bokub** [comment]
It's true that it would make the UI less minimalist.

What about favicons just next to the sites we own ?

Like this:

![image](https://user-images.githubusercontent.com/17952318/96366849-8c0f5800-114a-11eb-8c4e-8d6d351e3e28.png) 

![image](https://user-images.githubusercontent.com/17952318/96366758-0f7c7980-114a-11eb-9030-adb5bbbba4e0.png)

Icons would be downloaded at runtime using a duckduckgo feature: `https://duckduckgo.com/ip3/${DOMAIN}.ico`

For example:
- <img src="https://duckduckgo.com/ip3/umami.is.ico" height="20"/> `https://duckduckgo.com/ip3/umami.is.ico`
- <img src="https://duckduckgo.com/ip3/microsoft.com.ico" height="20"/> `https://duckduckgo.com/ip3/microsoft.com.ico`
- <img src="https://duckduckgo.com/ip3/github.com.ico" height="20"/> `https://duckduckgo.com/ip3/github.com.ico`

**Comment by mikecao** [comment]
Yea that could work. Just need to create a Favicon component. Do you want to submit a PR?

**Comment by bokub** [comment]
I've never tried React before, but I'll give it a try.

I'll keep you updated in case I change my mind.
