### ISSUE TITLE
[Feature Request] Open Registration

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#325]
Currently, We can add new users from Dashboard. 

I'd like to see a possibility for open registration. So that users can signup and login without admin interruption. 

Discuss!

**Comment by mikecao** [comment]
Not sure that's a good idea. Why would you want just anyone to use your resources? Unless you're planning to charge for it, which is fine, but will require a lot more work than just open registration.

**Comment by surjithctly** [comment]
I'd like to open it for my clients so that they can register by sending them a link. So i don't have to manually add everyone. 

In case of 100 users, it will be hard. Since Umami already supports registration, enabling this as a configuration option won't be a big problem I guess. 

Payment integration is not required I think. (may be in the future)

**Comment by MoltenCoffee** [comment]
To be honest myself don't really see the point of this either, I think the options of adding accounts and providing a URL to view data cover pretty much all use cases.
The only thing I could imagine in line with @surjithctly their comments is some feature where the admin provides a unique url/token or temporary account details, after which a user can use this to create an account. Basically the admin gives permission to add an account beforehand, after which the person in question fills in the account details (username and password). However, as this is an analytics suite, I personally don't really see a need for this, I think.

**Comment by migo315** [comment]
I do not think that a large number of users need this. Especially since you already can share your stats without registration.

Umami is a very cool tool because it is simple and focuses on basic needs and does not come with a thousand settings. I would prefer it to stay that way. :-)

Just my 2 cents as user.

**Comment by mikecao** [comment]
Closing. Won't be developing this feature.
