### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by hokkqi** [mikecao/umami#331]
Would you consider having API Docs?

I just started using Umami and love it already, though for me I'd need to send custom requests if someone visited `example.com/twitter`, which is currently handled by a express `res.redirect()` and a rendered page.

If those'd exist, I'd consider writing a express middleware so that it could be used similar to:

```js
let umami = require('express-umami')

let stats = new umami({
   host: "url",
   website_id: "id"
})

app.use(stats)
```
IMO this'd make it easier to implement it into more websites and quite possibly even a lot easier for someone to collect usage stats for their API

**Comment by mikecao** [comment]
Sure, I can work on adding some docs.

**Comment by hokkqi** [comment]
Tysm!

**Comment by hokkqi** [comment]
Bump for info?

**Comment by hokkqi** [comment]
Any updates on this, by any chance?

**Comment by mikecao** [comment]
@hokkqi I'm working on the docs now. They will be available on the website.

**Comment by hokkqi** [comment]
Thanks!

**Comment by mikecao** [comment]
@hokkqi https://umami.is/docs/api

**Comment by hokkqi** [comment]
Thanks!
