### ISSUE TITLE
Graph display bug when DST change

### ISSUE THREAD

**Issue by andlil** [mikecao/umami#333]
Early this morning most of Europe changed back from summer time to standard time. This broke Umamis graph display in today and 24h view.
![Skärminspelning 2020-10-25 kl  08 42 50](https://user-images.githubusercontent.com/10003475/97101538-b4dda300-169e-11eb-8874-fe174be32d01.gif)

**Comment by vitobotta** [comment]
I came to report this :)

**Comment by diogotcorreia** [comment]
Can confirm it's happening here as well:
![image](https://user-images.githubusercontent.com/7467891/97108615-ad31f480-16c6-11eb-8e3c-e660c342b426.png)

**Comment by shu8** [comment]
Does going to Settings > Profile > Timezone and (re-)choosing the correct timezone fix this?

I was also just having this issue but realised I didn't have the latest version, so after upgrading my docker image and saving the new settings in Profile, it seemed to get fixed!

**Comment by mikecao** [comment]
Can someone post the requests being made? Specifically to `/stats` and `/pageviews`

**Comment by andlil** [comment]
Is this what you are looking for?

For this request `.../api/website/1/stats?start_at=1603573200000&end_at=1603659599999`

I get the following answer
`{"pageviews":265,"uniques":74,"bounces":110,"totaltime":26197}`

And for 
`.../api/website/1/pageviews?start_at=1603573200000&end_at=1603659599999&unit=hour&tz=Europe%2FStockholm`

the response is 

`{"pageviews":[{"t":"2020-10-24 23:00:00","y":10},{"t":"2020-10-25 00:00:00","y":6},{"t":"2020-10-25 01:00:00","y":9},{"t":"2020-10-25 02:00:00","y":6},{"t":"2020-10-25 03:00:00","y":1},{"t":"2020-10-25 05:00:00","y":3},{"t":"2020-10-25 06:00:00","y":10},{"t":"2020-10-25 07:00:00","y":11},{"t":"2020-10-25 08:00:00","y":18},{"t":"2020-10-25 09:00:00","y":16},{"t":"2020-10-25 10:00:00","y":21},{"t":"2020-10-25 11:00:00","y":8},{"t":"2020-10-25 12:00:00","y":17},{"t":"2020-10-25 13:00:00","y":15},{"t":"2020-10-25 14:00:00","y":6},{"t":"2020-10-25 15:00:00","y":10},{"t":"2020-10-25 16:00:00","y":12},{"t":"2020-10-25 17:00:00","y":26},{"t":"2020-10-25 18:00:00","y":32},{"t":"2020-10-25 19:00:00","y":11},{"t":"2020-10-25 20:00:00","y":15},{"t":"2020-10-25 21:00:00","y":2}],"sessions":[{"t":"2020-10-24 23:00:00","y":7},{"t":"2020-10-25 00:00:00","y":3},{"t":"2020-10-25 01:00:00","y":4},{"t":"2020-10-25 02:00:00","y":3},{"t":"2020-10-25 03:00:00","y":1},{"t":"2020-10-25 05:00:00","y":2},{"t":"2020-10-25 06:00:00","y":8},{"t":"2020-10-25 07:00:00","y":9},{"t":"2020-10-25 08:00:00","y":10},{"t":"2020-10-25 09:00:00","y":13},{"t":"2020-10-25 10:00:00","y":9},{"t":"2020-10-25 11:00:00","y":6},{"t":"2020-10-25 12:00:00","y":10},{"t":"2020-10-25 13:00:00","y":8},{"t":"2020-10-25 14:00:00","y":4},{"t":"2020-10-25 15:00:00","y":6},{"t":"2020-10-25 16:00:00","y":9},{"t":"2020-10-25 17:00:00","y":16},{"t":"2020-10-25 18:00:00","y":18},{"t":"2020-10-25 19:00:00","y":10},{"t":"2020-10-25 20:00:00","y":10},{"t":"2020-10-25 21:00:00","y":2}]}`

**Comment by andlil** [comment]
> Does going to Settings > Profile > Timezone and (re-)choosing the correct timezone fix this?
> 
> I was also just having this issue but realised I didn't have the latest version, so after upgrading my docker image and saving the new settings in Profile, it seemed to get fixed!

Nope, it changes nothing for me.

**Comment by mikecao** [comment]
It looks like the you are getting data back, just the graph is not rendering. I will see what I can find, but it's hard for me to debug since I can't replicate it.

**Comment by andlil** [comment]
Interesting thing is that it won't render the graph on your demo-page for me either [https://app.umami.is/share/8rmHaheU/umami.is](https://app.umami.is/share/8rmHaheU/umami.is) so something is wrong...

**Comment by diogotcorreia** [comment]
@mikecao Maybe it gets fixed once 24 hours have passed? We'll find out very soon.
Meanwhile, here is a screenshot of the inspector on the data. I can see that there are multiple timezones here, maybe that's the issue?
(data from the umami.is website as andlil shared above)
![image](https://user-images.githubusercontent.com/7467891/97122129-5d314d00-171b-11eb-992f-d1778981df51.png)
And this is for the x-axis:
![image](https://user-images.githubusercontent.com/7467891/97122181-c6b15b80-171b-11eb-9b82-2065894685d2.png)

**Comment by andlil** [comment]
As expected, when 24 hours has passed since the changeover, everything is back to normal. @mikecao will experience it for himself on sunday ;-)

**Comment by mikecao** [comment]
Ran into this issue myself. Looks like a problem with Chart.js. As far as I can tell all the correct data is being passed to the chart. 🤷‍♂️

**Comment by mikecao** [comment]
Closing since this is an issue with Chart.js.
