### ISSUE TITLE
Not tracking country data

### ISSUE THREAD

**Issue by johnyburd** [mikecao/umami#339]
I have umami running in docker behind nginx with the example configuration:
```
server {
  server_name umami.yourdomain.com;

  location / {
    proxy_pass http://localhost:3000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

Here is the share link to my site:
https://umami.archit.us/share/QJYNnlV3/archit.us

everything seems to be working perfectly except country tracking.  I've tested accessing from other countries using Opera's built in VPN, but neither they nor my native country are showing up in the list.

**Comment by mikecao** [comment]
The country lookup is entirely dependent on the IP address. Can you check your nginx logs and see if you are recording IPs? Another thing you can do is run the `build-geo` script to rebuild the IP lookup database.

**Comment by shotor** [comment]
I have the same issue. I can't run build-geo because I'm running it in docker and only have the public and node modules folders.

app is running as static page on netlify, havent done anything special on nginx.

**Comment by johnyburd** [comment]
yeah, I just spent the entire day debugging iptables and yes, I can confirm that umami is getting passed a local ip for every user, so I guess I'll close this. 😕 ty for the help
