### ISSUE TITLE
Discussion about database size

### ISSUE THREAD

**Issue by Mokkapps** [mikecao/umami#340]
Hi, 

first thanks for this nice project, I really like it so far and I plan to totally migrate from GA to umami to track analytics on my portfolio website 🚀.

Currently, I have deployed the application to Heroku and my current DB resources after running for two days are: 

<img width="1453" alt="Screenshot 2020-10-28 at 08 28 19" src="https://user-images.githubusercontent.com/3127210/97405221-9de5bd80-18f7-11eb-8aa6-668149b6f89e.png">

It looks like umami creates about 1000 rows per day on my website. So even if I would pay for the 100.000 rows plan I could only run it for 100 days. The [standard tier](https://elements.heroku.com/addons/heroku-postgresql#pricing) without row limitations costs 50$/month which is a lot of money for a private project website.

How are you guys handling this problem for your private websites?

**Comment by mikecao** [comment]
I personally don't use Heroku but I know a couple users here do. It's not the cheapest option for sure. For my setup I host the database on DigitalOcean on a $10/month server and then host the app on Vercel which is free. Then I just have the the app connect to my database remotely.

There are a couple guides on the website if you want to run the same setup.

https://umami.is/docs/running-on-digitalocean
https://umami.is/docs/running-on-vercel

**Comment by Mokkapps** [comment]
> I personally don't use Heroku but I know a couple users here do. It's not the cheapest option for sure. For my setup I host the database on DigitalOcean on a $10/month server and then host the app on Vercel which is free. Then I just have the the app connect to my database remotely.
> 
> There are a couple guides on the website if you want to run the same setup.
> 
> https://umami.is/docs/running-on-digitalocean
> https://umami.is/docs/running-on-vercel

Thanks, that sounds like a good and cheaper alternative!

**Comment by bokub** [comment]
I personally use the server included in the GCP free tier (550MB RAM, 1vCPU, 30GB HDD), and it works like a charm for $0/year

**Comment by Mokkapps** [comment]
I ended up hosting Umami on DigitalOcean & Vercel: 
https://www.mokkapps.de/blog/how-i-replaced-google-analytics-with-a-private-open-source-and-self-hosted-alternative
