### ISSUE TITLE
What are the config requirements for running dockerized with external db?

### ISSUE THREAD

**Issue by roncanepa** [mikecao/umami#343]
The readme is very vague.  I tried looking at the compose file and the Dockerfile to untangle it but so far, no luck.

Can you please clarify what config I need to pass in and what the volume mountpoints should be?

Thank you.

**Comment by mikecao** [comment]
@hugomd ☝️ ?

**Comment by adroste** [comment]
@roncanepa No mountpoints are needed as umami uses an external database to store its data.

Summary of the setup process:

First prepare your db. Just login to your database-instance and create a user and a corresponding database. For example - user: umami, password: xyz, database: umami.
Afterwards run the sql statements to create the tables on the created database (https://github.com/mikecao/umami/tree/master/sql) 

Finally you can setup umami. If you run a mysql database use this image => `docker pull ghcr.io/mikecao/umami:mysql-latest` for postgres this one => `docker pull ghcr.io/mikecao/umami:postgresql-latest`.
You must inject some infos as environment vars into your umami container.
_assuming your using mysql and your mysql container is reachable in your internal network as "mysql" it could look like this:_
```
DATABASE_URL=mysql://umami:xyz@localhost:3306/umami
HASH_SALT=my-very-secret-secret
```

Afterwards you just login to your web-interface with the user admin and password umami.
If your login does not work, check that the admin account was inserted correctly and fix it if necessary:
```sql
insert into account (username, password, is_admin) values ('admin', '$2b$10$BUli0c.muyCW1ErNJc3jL.vFRFtFJWrT8/GcR4A.sUdCznaXiqFXa', true);
```

**Comment by roncanepa** [comment]
Hi @adroste , thanks for the great write-up.  I'm running mysql on the host (not dockerized) and so it looks like I'm running into a few extra issues.  I'll see what I can do and then report back.
