### ISSUE TITLE
Feature Request: Link the eye icon to actual site url in Realtime logs

### ISSUE THREAD

**Issue by Sushubh** [mikecao/umami#344]
Or the link bit itself since it is not linked to anything at the moment. Just to quickly access the page directly.

**Comment by mikecao** [comment]
The problem is we don't know if the site is http or https. Also, it's just a link to your own website, so not sure what value there is to that.

**Comment by navjotjsingh** [comment]
It is useful for a forum like site which has thousands of pagges but you are only able to see a random url like /t/387463 in the logs so you have to manually type out the full url everytime to see which post or thread is getting more views. Having a direct link in the dashboard would reduce a lot of labor.

**Comment by Sushubh** [comment]
Yup. And as for http and https... You can use //domain.tld/url-part-from-logs that would automatically pick the protocol used by the stats page. Thanks.

**Comment by mikecao** [comment]
The url is now clickable.

**Comment by Sushubh** [comment]
Ok. So I updated the installation... and the links [are pointing to](https://i.imgur.com/H85IVp4.jpg) `https://ibf/t/197163/` style structure. ibf is the site id. it is not using domain in these links. 

also if possible, add a similar link to the pages tab in realtime view (the second tab besides referrers)! 

also had another request though i imagine i should post it separately... if there is just one domain configured... avoid using all websites as default view. this setting affects the pages view in realtime panel where domain name [takes up all the space](https://i.imgur.com/Qfe69Ys.jpeg) in the column. 

thanks for this lovely piece of software!

**Comment by mikecao** [comment]
@Sushubh Can you file a separate issue so I can track it?
