### ISSUE TITLE
Proposal: Opt-Out method needed as 'Do Not Track' is deprecated

### ISSUE THREAD

**Issue by adroste** [mikecao/umami#347]
Hey,

I just found out that Apple removed the DNT feature from Safari (macOS, iOS, iPadOS).
This concludes that there is no easy way to opt-out for users anymore from umami's tracking.

Proposal:
Add a function to the JS-interface like
```js
umami.enableTracking = function(enabled) {
  if (enabled)
    localStorage.removeItem('doNotTrack');
  else
    localStorage.setItem('doNotTrack', 1);
}
```

Then we could easily put a link in our privacy policies like this
```html
<p>
  bla bla we bla your data bla bla eu bla 
  <a href="#" onclick="umami.enableTracking(false); return false;">Opt-Out</a>
</p>
```

**Comment by mikecao** [comment]
The script will now check for `umami.disabled` to disable tracking. I didn't want to add the functionality to the script so you could set it without loading the script.
