### ISSUE TITLE
Can't get page's url in SPA

### ISSUE THREAD

**Issue by yili1992** [mikecao/umami#36]
My project is SPA project,  I found that umami get url always is /

**Comment by yili1992** [comment]
> How do you change the url in your app? Are you using history state push?

I using a workaround solution
in umami.js  
 `m,w=""+a+c+i.hash`,
in my react SPA project  
```
const Umami = (props) => {
  let children = props.children;
  let _hmt = _hmt || [];
  (function() {
    var hm = document.createElement("script");
    hm.src = "http://xxxx/umami.js";
    hm.dataWebsiteId = "f2ef3237-764a-4f2f-99a3-5245f661fe89";
    hm.async = true;
    hm.defer = true;
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(hm, s);
  })();
  return children;
};
    <Router>
      <Switch>
        <Umami>
          <Route path="/xxx" component={xxx} />
                 ...```

**Comment by mikecao** [comment]
The umami script needs to be in the head section of the document, not inside your react app. You can use [react-helmet](https://github.com/nfl/react-helmet) to do this.
