### ISSUE TITLE
Add option to build locally and deploy remotely

### ISSUE THREAD

**Issue by acagastya** [mikecao/umami#363]
Hi, I was trying to set up this on Ubuntu 20.04 with 1GB RAM, and the build process took on forever, with 100% CPU utilisation.  However once set up, the CPU utilisation is not much.

Does the build process require some minimum system requirements?

Could you please add some provision the build process can be done remotely and the uploaded on the server?  That would avoid servers to be resized for the build process.

Is something like that possible?

**Comment by mikecao** [comment]
You can just FTP the build result to your server and it should work.

**Comment by acagastya** [comment]
All right.  Just to be clear, when building it locally, the `DATABASE_URL` should be changed to `mysql://username:mypassword@REMOTE-HOST:3306/mydb`, right?  Does the build process try to connect to the database?  Do I need to allow `3306` in the firewall if that is the case?

**Comment by mikecao** [comment]
The `DATABASE_URL` determines which database client to build, but it doesn't try to connect.

**Comment by acagastya** [comment]
All right -- that makes things easier!
