### ISSUE TITLE
Next basePath duplicated with <Link /> elements

### ISSUE THREAD

**Issue by bastidest** [mikecao/umami#366]
### Info
Version: umami 1.5.0 @ 024e7c1942117205b8c9564c4d0f91903a3f0564
Environment: docker
Reverse-Proxy: can be reproduced with and without

### Description
I am serving umami at `mydomain.foo/umami-admin`.

As described in #237, I added the `basePath: '/umami'` attribute to `next.config.js`. After compilation I am able to access umami at `/umami-admin` as expected.

Some links (for example all "More" links in `MetricsTable`s) interpret the `basePath` in a wrong way. Those links are prefixed by `basePath` twice.

### Expected
1. `/umami-admin/website/1/mydomain.foo?view=url`
1. `/umami-admin/website/1/mydomain.foo?url=%2F`

### Actual
1. `/umami-admin/umami-admin/website/1/mydomain.foo?view=url`
1. `/umami-admin/umami-admin/website/1/mydomain.foo?url=%2F`

**Comment by nullifye** [comment]
same issue here. waiting for the fix. thanx
