### ISSUE TITLE
What happens if I forget the SALT?

### ISSUE THREAD

**Issue by acagastya** [mikecao/umami#368]
Hi, I have been using umami since yesterday, and I have been thinking -- what happens if I lose my `HASH_SALT` somehow?  Do I lose the previous data?  Is there a way one could login to the database to manually update the password?

**Comment by mikecao** [comment]
The salt has nothing to do with the password. It is used for two things 1) generating unique ids for your data and 2) encrypting your login cookie. So if you change it, you have to log back in and some of your data might be duplicated but you won't lose any data.

**Comment by acagastya** [comment]
All right, thanks!
