### ISSUE TITLE
Event type/value are too constrained

### ISSUE THREAD

**Issue by ncovercash** [mikecao/umami#369]
I would like to suggest changing the types of `event.event_type` and `event.event_value` in the database to a `mediumtext` or at least a longer `varchar` – the initial values of 50/100 do not last very long, particularly in a large application that tracks complex events (where the value could contain several parameters/data points or an entire JSON blob).

**Comment by mikecao** [comment]
You are free to change it to suit your needs, but the general use case is limited. The events chart displays these values and it doesn't make much sense to chart a blob of text.

![image](https://user-images.githubusercontent.com/477975/99212301-99d2f000-277f-11eb-9bef-f97bf196a4e6.png)

**Comment by ncovercash** [comment]
Fair - just thought it would be easier to change the initial parameters by default than have users have to find the issue of it themselves and, in many cases, storage as `mediumtext` can also better optimize the database's memory and store the text buffer in a way that is more efficient for writing (as would likely be desired for faster page views on the measured site, as events there are happening far more often than an administrator loading the dashboard); SO has some good threads on this.

If you don't want to add this feature I completely understand, just thought I'd share my reasons for versatility!  I wanted umami to be more the engine for the analytics themselves and storage while my own logic could parse statistics from the database and, so far at least, I've done this by making the event value a comma separated blob with multiple fields I needed for my usage

**Comment by sneyed** [comment]
For any fellow googlers, I was also wanting to store JSON data instead of a 50 character string

I applied this patch to my fork and all worked well: https://github.com/sneyed/analytics/commit/d5400a5691fe931dc42a01716ce0dd394bf97821
