### ISSUE TITLE
Bounce Rate calculation issues

### ISSUE THREAD

**Issue by SoftCreatR** [mikecao/umami#37]
I know that I'm not running the most interesting website, but this is kinda depressing 😁

![Screenshot_20200821-162935_Brave](https://user-images.githubusercontent.com/81188/90901686-95d74200-e3cb-11ea-9068-ef6abbe8dc08.jpg)

**Comment by selcukusta** [comment]
We are using PostgreSQL but facing this problem.

![image](https://user-images.githubusercontent.com/15161296/91025298-da4c2300-e601-11ea-9d82-641e876cda63.png)

**Comment by mikecao** [comment]
This should be fixed now.
