### ISSUE TITLE
How to integrate with plain HTML/CSS website?

### ISSUE THREAD

**Issue by BraydenTW** [mikecao/umami#370]
Hi,

I was wondering **how I could integrate Umami with my plain HTML/CSS portfolio**: https://braydentw.github.io

I know that it only works with Node apps but I was wondering if you could make it possible to be compatible with simpler web pages.

Please let me know of your thoughts.

**Comment by mikecao** [comment]
What do you mean by integrate? You can already track stats for any website. All you need is the tracker script which is just javascript. But you need to send the stats somewhere, which is umami the node app.

**Comment by BraydenTW** [comment]
@mikecao, so does that mean I only need a <script> tracker to see my stats and share them? I don't need to use NodeJS?

Thanks for your help.

**Comment by BraydenTW** [comment]
What is the tracking script? Is it similar to Google Analytics?

**Comment by BraydenTW** [comment]
@mikecao , nevermind. I just looked through the docs and found the part about the tracker tag.

I will close this issue now.
