### ISSUE TITLE
Links under Realtime dashboard > Pages section are broken

### ISSUE THREAD

**Issue by navjotjsingh** [mikecao/umami#377]
Issue: https://i.imgur.com/3I3XQrK.png

Realtime Dashboard > Pages

I am using v1.6.0.

**Comment by mikecao** [comment]
You don't have a domain defined for your website?

**Comment by navjotjsingh** [comment]
I do have. https://i.imgur.com/DEeUSSv.png

**Comment by mikecao** [comment]
Do you only have one website setup?

**Comment by navjotjsingh** [comment]
Yes. I do have a second account set up for a friend from the same installation and it has the same bug though.
