### ISSUE TITLE
Collect data like GA's measurement protocol 

### ISSUE THREAD

**Issue by loguu** [mikecao/umami#382]
Could we collect data by sending HTTP requests to umami server, just like google analytics‘ [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/reference)? This way we don't need to insert `umami.js` into the website and we can freely decide which links should be tracked.

**Comment by mikecao** [comment]
Yes, you can send data directly to the API endpoints.

**Comment by loguu** [comment]
Thanks, I've got it working.
