### ISSUE TITLE
Bounce rate more than 100%

### ISSUE THREAD

**Issue by Tobishua** [mikecao/umami#387]
Hi there!
Maybe I'm wrong, but I think the bounce rate shouldn't be more than 100%. In Release 1.6.0 I have a bounce rate of 117% for one of the websites.
 [Image with that bounce rate](https://imgur.com/rNqrO6y)

**Comment by andlil** [comment]
Yeah, I have 143% and 168% on two sites, I really don't care personally since I'm not that interested in bounce rate but something seems wrong.
