### ISSUE TITLE
A way to differentiate between domains for pages using multiple domains.

### ISSUE THREAD

**Issue by simbo** [mikecao/umami#392]
Hey,

I have a small webspace where I got some unused domains parked and use umami for tracking.

Apparently, there are a lot of requests ongoing but I can not see for which domains.

Is there a way to display with which domain the page was opened?

I already found out, I could do something like this:

```
<script async defer src="http://mywebsite/umami.js" data-website-id="id-domain1" data-domains="domain1.com"></script>
<script async defer src="http://mywebsite/umami.js" data-website-id="id-domain2" data-domains="domain2.com"></script>
<script async defer src="http://mywebsite/umami.js" data-website-id="id-domain3" data-domains="domain3.com"></script>
...
```

Would probably work, but seems a bit over-the-top for me. I would have to add ~10 script tags.

Any suggestions?

Simon

**Comment by mikecao** [comment]
I wouldn't put multiple tags on the same page like that. You might end up with a lot of duplicated stats.

You have a few options though. If you can dynamically generate the script, then you generate a single script for the specific domain.

Your other option is to disable automatic tracking, and send the events yourself, https://umami.is/docs/tracker-functions

**Comment by simbo** [comment]
Alright, thanks!
I went for a small php switch. It works.

If anyone needs this:
```
<?php
// remove subdomain from domain
$domain = preg_replace('/^[a-z0-9.]*([a-z0-9]+\.[a-z0-9]+)$/iU', "$1", $_SERVER['HTTP_HOST']);
// switch umami id based on domain
switch ($domain) {
  case 'domain3.com':
    $umami_id = '12345';
    break;
  case 'domain2.com':
    $umami_id = '54321';
    break;
  case 'domain1.com':
  default:
    $umami_id = '67890';
    break;
}
?><script async defer data-website-id="<?php echo $umami_id; ?>" src="https://myserver.com/umami.js"></script>
```

**Comment by simbo** [comment]
Thanks for the hint with the tracker functions!
This is much easier and elegant:
```
<script data-website-id="12345" src="https://myserver.com/umami.js" data-do-not-track="true"></script>
<script>umami.trackView(location.hostname.replace(/^www\./, '') + location.pathname);</script>
