### ISSUE TITLE
basePath as .env variable

### ISSUE THREAD

**Issue by Milchreis** [mikecao/umami#400]
Hi,

I want to use umami with the comfortable docker-compose command, but in my enviroment I have to use the basePath property of next.config.js. It there a way to setup the basePath in an evironment variable which propagates this configuration inside the docker container?

Thanks for the great software :-)

**Comment by mikecao** [comment]
The `next.config.js` is already importing environment variables via `dotenv`, so I think you can just add

```
basePath: process.env.BASE_PATH
```
