### ISSUE TITLE
[Feature] Track new or returning users

### ISSUE THREAD

**Issue by patrickxchong** [mikecao/umami#404]
Is there a way to track new or returning users? Perhaps something like storing the session_uuid on the client (or create a new unique identifier) which is re-used when a user returns to the same page after a few days? 

I understand if this against the privacy-focused principle that umami is built on and hence this feature is not built in, I was just wondering if it's something that has been considered before.

**Comment by mikecao** [comment]
umami doesn't store tracking cookies on principle, but it's session calculation is good enough for most cases. If the same user comes back, it will calculate the same `session_uuid`, assuming they are using the same browser. If they switch browsers it will count as another unique. Also, unique values are rotated monthly, so uniques are only unique up to a month.

**Comment by nsursock** [comment]
How can you query the `session_uuid` from the API? I need to display new vs returning users %...

**Comment by LushawnDev** [comment]
Revisting this, I wonder is reporting "Returning users" possible now? Given the sessions tracking and retention graphs, it seems that Umami is already natively tracking whether the anonimised user has visited the website before or not. 

Would it not be possible to use this data to differentiate new/returning users? 

E.g. Say our of our total visitors
For each visitor, if the visitor has a previous sessions, mark them as a returning visitor, if there are no recorded previous sessions, mark them as a new visitor.
