### ISSUE TITLE
custom port does not work as adviced

### ISSUE THREAD

**Issue by pefman** [mikecao/umami#413]
using a custom port as documented in https://umami.is/docs/environment-variables does not work, even if the script is run with the "npm run start-env" it does not pick the variable up and the script fails to launch.

**Comment by mikecao** [comment]
Yes, looks like a bug.

**Comment by mikecao** [comment]
In the meantime you can change the `start-env` script to this:

```
"start-env": "node -r dotenv/config scripts/start-env.js"
```

in the `package.json`.

**Comment by mikecao** [comment]
Fixed in https://github.com/mikecao/umami/pull/431
