### ISSUE TITLE
User visit statistics area distribution problem.

### ISSUE THREAD

**Issue by movecat** [mikecao/umami#414]
Hello, the current statistics are based on user countries.
Can you count the detailed area information of users?
This allows you to see the geographical distribution of users in more detail.

**Comment by mikecao** [comment]
No, we only track by country at most due to privacy concerns.

**Comment by movecat** [comment]
If the IP address is not recorded, user privacy is still guaranteed.
The statistical city is mainly to better know the detailed distribution of website users.

**Comment by mikecao** [comment]
We are not looking to add information beyond country at this time.
