### ISSUE TITLE
Unique Visitor Discrepancies & No Location Data

### ISSUE THREAD

**Issue by adudeongithub** [mikecao/umami#415]
Disclaimer: I am just a blogger; I hired help to get Umami up and running.

I am still using Google Analytics for the purpose of comparing stats with those from Umami. Umami is suggesting I have about half the pageviews and a mere fourth of the Unique Visitors. How differently are these counted between the two platforms? These discrepancies are not exactly minor and insignificant.

Also, I am getting next to nothing in terms of location data:
https://i.ibb.co/Yd9wmQY/umami-locdata.jpg (24 hour span)

Thanks in advance for any help or insights.

**Comment by mikecao** [comment]
umami should actually show more stats than google analytics because it shouldn't be as widely blocked. Are you sure you have the tracking script installed on every page of your blog?

As for location data, do you have access to your database? You can query your session records to see why country is coming up blank.

**Comment by adudeongithub** [comment]
> Are you sure you have the tracking script installed on every page of your blog?

According to the theme I use, "We can no longer offer an option to inject code into the head due to security reasons. The easiest way to do it is to install a plugin that allows you to do that or copy/paste this [code] into your child theme's function.php file (which is what I subsequently did and that's where I inserted Umami tracking script).

> As for location data, do you have access to your database? You can query your session records to see why country is coming up blank.

I have access to everything. Unfortunately, as initially mentioned, I hired help to get this up and running and have no clue how to carry out such a task myself. The guy who installed this for me says he followed all the instructions precisely.

**Comment by rubybb** [comment]
> > Are you sure you have the tracking script installed on every page of your blog?
> 
> According to the theme I use, "We can no longer offer an option to inject code into the head due to security reasons. The easiest way to do it is to install a plugin that allows you to do that or copy/paste this [code] into your child theme's function.php file (which is what I subsequently did and that's where I inserted Umami tracking script).
> 
> > As for location data, do you have access to your database? You can query your session records to see why country is coming up blank.
> 
> I have access to everything. Unfortunately, as initially mentioned, I hired help to get this up and running and have no clue how to carry out such a task myself. The guy who installed this for me says he followed all the instructions precisely.

Certainly this seems to be a problem of the platform you use, and not Umami itself, are I'd suggest viewing pages, and seeing if they are logged, if any are missed, there's your problem.

**Comment by adudeongithub** [comment]
> I'd suggest viewing pages, and seeing if they are logged, if any are missed, there's your problem.

There are thousands of pages on my website. It seems like they are all being logged just fine. Still, as mentioned above, I'm seeing half the pageviews on Umami compared to on Google Analytics, and a mere 25% of the Unique Visitors. Honestly have no clue what could be causing this discrepancy.

**Comment by smartpunter** [comment]
No location data is probably because you didn't forward necessary headers through nginx or other proxy you might use.

For nginx just add thi to "location" block

proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by adudeongithub** [comment]
> No location data is probably because you didn't forward necessary headers through nginx or other proxy you might use.

You're on it! Thanks so much, man. This was the problem all along. I appreciate it.
