### ISSUE TITLE
Events action percentage show by event type

### ISSUE THREAD

**Issue by spacemonkey92** [mikecao/umami#417]
[Question] Ive been using umami to track my webpage and it works well. Now I want to track a particular event of “Task Completed” so I can view everyday that 30% of my visitors have “Task Completed”. For this I have added a custom tracker with event type “task” and event value as “task completed”, But this is now mixed with all the other events like clicks other custom types. 

Is there a way I can view this visually where I can see that 30% of my visitors have “task completed”

**Comment by mikecao** [comment]
You can click on the labels in the chart to hide them, leaving only the stats you want to see. As for comparing with visitor count, that would have to be a new feature.
