### ISSUE TITLE
Base Path ignored in some Locations

### ISSUE THREAD

**Issue by Lucas-Steinmann** [mikecao/umami#419]
Hi,

at some positions the base path is not considered. 
I've set the ``basePath: '/umami'`` in ``next.config.js``.
The umami dashboard is served and works for 90% of the functionality when I go to ``example.com/umami/``.

I'm no javascript developer, so I don't know how to fix most of the problems, but I'll point out the positions, where I think the error lies, if I was able to find it.
The following functionalities do not work:

 1. Tracking code omits the base path, i.e. only shows: ``<script async defer data-website-id="omitted" src="https://example.com/umami.js"></script>``. [Code which probably has to be adapted](https://github.com/mikecao/umami/blob/1bb46f1d42f7b27312de98b110523cf7f3478339/components/forms/TrackingCodeForm.js#L25). When I fixed the tracking code manually, it worked fine.
 2. Sharing code also misses base path. [Code position](https://github.com/mikecao/umami/blob/1bb46f1d42f7b27312de98b110523cf7f3478339/components/forms/ShareUrlForm.js#L26). Also unrelated, but in the same file, why is ``TrackingCodeForm`` [exported](https://github.com/mikecao/umami/blob/1bb46f1d42f7b27312de98b110523cf7f3478339/components/forms/ShareUrlForm.js#L7) and not ``ShareUrlForm``? (Sorry for my confusion, I have really no idea how javascript works).
 3. When fixing the share URL manually and directing my browser to it, the site stays blank. My browser displays a CORS error. I think this is also due to a missing base path, since it tries to load ``https://www.example.com/api/share/omitted/`` (instead of ``https://www.example.com/umami/api/share/omitted/``), which fails because of the CORS error. But I can't point you to the wrong code, since I don't really understand how the routing system works.
 4. Favicon. [Maybe here?](https://github.com/mikecao/umami/blob/fe084756b2ebfc1b3f54bf0e6d5064f377fe9b99/pages/_app.js#L33)

For completeness, I serve umami from a docker container and use nginx as proxy by including
```
server {
    server_name example.com www.example.com
    ...
    location /umami/ {
        proxy_pass http://127.0.0.1:3210/;
    }
    ...
}
```

This is not a really high priority issue, since tracking already works, when fixing the URL manually.

Thanks for this project.

**Comment by mikecao** [comment]
Thanks for the detail report. I think we should be able to fix these issues,

**Comment by mikecao** [comment]
Fixed in https://github.com/mikecao/umami/pull/431
