### ISSUE TITLE
sql: create table if not exists

### ISSUE THREAD

**Issue by cbluth** [mikecao/umami#422]
I am trying to script the process for sql initialization, and i am changing the sql from:
```
drop table if exists my_table;
create table my_table (...);
```
then, i am removing the drop statement, and doing something like this:
```
create table if not exists my_table (...);
```

i am taking this approach because i expect this script to execute everytime my container starts.

my script effectively does something like this:
```
< <(curl -s -o - https://raw.githubusercontent.com/mikecao/umami/master/sql/schema.postgresql.sql) \
    grep -iv "DROP TABLE IF EXISTS" | \
    sed 's/CREATE TABLE /CREATE TABLE IF NOT EXISTS /gi' | \
    sed 's/CREATE INDEX /CREATE INDEX IF NOT EXISTS /gi' 
```
and then mounts the resulting sql file in the `/docker-entrypoint-initdb.d` directory of postgres.

i am not an sql expert, does anyone see any drawbacks from doing it like this?

**Comment by cbluth** [comment]
i have uploaded an example of using upserts here:

https://github.com/cbluth/umami/commit/9dd47b8fbf100c6efe748aa1b8f31f5f4d6e483b

**Comment by mikecao** [comment]
The script shouldn't run every time the container starts right? You should only have the create the database once. But then again I'm not a docker expert so someone else will have to chime in.
