### ISSUE TITLE
Missing pageviews

### ISSUE THREAD

**Issue by gabrielbc** [mikecao/umami#425]
We installed umami at our company a few weeks ago, and ran a series of validations against our own custom analytics platform data, primarily pageviews. 

It's not expected to obtain 1:1 results, however we found differences about 5% to 20% of missing pageviews on higher traffic hostnames (few million pageviews in 30 days).

Our best guest right now is some kind of scalability issue. Debugging is starting, and any tips are welcome.

We are open to post our data, logs files or any information needed to work out this issue.

**Comment by mikecao** [comment]
It's probably a scaling issue if you are getting millions of pageviews. Every pageview requires a calculation and lookup of the user session id. If your database is overwhelmed it could be dropping requests.

Enabling data caching may help in your situation, https://umami.is/docs/tracker-config
