### ISSUE TITLE
Make the Title clickable and let navigate to /detail page

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#426]
As you can see in the following screenshot, One needs to click the View Details link to navigate to the detail page. 

But most of the time, I tend to click on the Left Title instead hoping it would go, Even I know this won't work, when I revisit after 2-3 days, I tend to click the Title, because that's how it works on most of the apps. 

So I suggest you to add a link for Title as well which also leads to the detail page. 

![image](https://user-images.githubusercontent.com/1884712/103742785-63984b00-5021-11eb-96a4-44842e0906c0.png)

**Comment by meirroth** [comment]
+ 1 on this. I was thinking the same thing.
