### ISSUE TITLE
Query String Support

### ISSUE THREAD

**Issue by sarthaktexas** [mikecao/umami#427]
Google Analytics has custom query strings that allow it to detect where specific traffic came from. Umami does not appear to support this but it would be very helpful and not that difficult to implement.

**Comment by mikecao** [comment]
You can click on the `More` button below the urls and filter by `Raw`. That will show you the query strings.

**Comment by sarthaktexas** [comment]
What I'm asking is if I can provide custom query strings at the end of my links in newsletters and such. If so, what would be the template for this?

**Comment by mikecao** [comment]
There is no reporting based on query string parameters if that's what you mean.

**Comment by jnaklaas** [comment]
This is something that I think should really be added. Knowing where visitors come from is quite essential to measure which campaign or medium generates the most traffic / leads. Which is essential to know where to invest your money for future campaigns.

The referrer is not always known by the browser. For example in newsletters, or when the referrer uses http and the website uses https (or vice versa), or when the referrer data is blocked by the referrer (our main advertising platform blocks it and they refuse to change it for some reason - I suspect laziness). From what I can tell, these visitors are just not shown in umami under "Referrers". In Google analytics the referrer source would then be shown as "direct", as if the visitor entered the url directly in the address bar.

Google analytics solves this by using the `utm_source` query parameter as referrer (when available). Ackee analytics does the same using the `source` query parameter. I don't really see an alternative in umami, nor a reason why it would not be an essential feature.

**Comment by mikecao** [comment]
All urls are already being collected. If you pass in `utm_source` it will be recorded. The only thing missing is there's no way to report on the parameters. It's something we can look into.

**Comment by jnaklaas** [comment]
What I'm primarily suggesting is that there could be a query parameter that overwrites the referrer value that is sent to umami. Reporting wouldn't have to change that way. 

This would fix so many situations where the referrer is not collected by the browser.
