### ISSUE TITLE
[FR] Domain blacklist

### ISSUE THREAD

**Issue by kiprasmel** [mikecao/umami#429]
We have `data-domains` [1] for whitelisting specific domains and ignoring everything else.

I wanted to black-list only my localhost domain, and thus thought that perhaps having a blacklist would be useful?

Thank you for the great tool btw!

[1] https://umami.is/docs/tracker-config

**Comment by mikecao** [comment]
@kiprasmel You can do that by setting the `IGNORE_IP` environment variable, https://umami.is/docs/environment-variables

**Comment by kiprasmel** [comment]
Oh that's great, thanks. I guess we can close this.

I now realize that anyone could just take your website's tracking script and add it to theirs and spam your analytics with useless data -- is that right? Might be an issue 😅
