### ISSUE TITLE
Difficulty configuring reverse proxy

### ISSUE THREAD

**Issue by wgmyers** [mikecao/umami#433]
Really looking forward to using umami - it looks great.

I've followed the installation instructions and (after some adventures, I'm on FreeBSD) it seems to run ok. I've set up a reverse proxy on Apache 2.4 with a subdomain and get the login page fine on https://my-subdomain.example.com/ . However, I can't log in - mysql refuses all requests from the reverse proxy with the following:

```
PrismaClientInitializationError2 [PrismaClientInitializationError]: Error querying the database: Server error: `ERROR HY000 (1130): Host '[EXTERNAL_IP]' is not allowed to connect to this MySQL server'
```

Apache, mysql and umami are all installed on the same machine.

My Apache proxypass config is like so:

```
<VirtualHost *:443>
  ServerName my-subdomain.example.com
  ...
  ProxyPass "/" "http://localhost:3000/"
  ProxyPassReverse "/" "http://localhost:3000/"
</VirtualHost>
```

Various places suggested setting `bind-address` in the mysql config to `0.0.0.0`, but this a) seems wrong and b) doesn't make any difference.

I tried setting my umami user in the mysql db to be `umami-user@EXTERNAL_IP` instead of `umami-user@localhost`, changing the value of `DATABASE_URL` accordingly, and setting mysql's bind-address to `0.0.0.0`, but without result.

Kind of tearing my hair out after several straight hours tinkering with various Apache config tweaks, none of which made any difference. I am obviously doing something extremely stupid but can't see it.

Any help would be much appreciated.

**Comment by mikecao** [comment]
The error looks like it's related to mysql and not apache. The app is making the database connection, not the user. Maybe this will help, https://stackoverflow.com/questions/19101243/error-1130-hy000-host-is-not-allowed-to-connect-to-this-mysql-server

**Comment by wgmyers** [comment]
Thank you!

This fixed it - I had set the umami user in the database to be `'my-user'@'localhost'` and not `'my-user'@'%'`. Making that change solved the problem, and umami is now working fine.

Given that the database url specifies localhost and that my-sql is bound only to localhost according to bind-address, it was not obvious (to me, anyway) but a fix is a fix. Maybe worth noting in the docs?

Anyway, thank you once again.
