### ISSUE TITLE
[Feature request] multi user websites

### ISSUE THREAD

**Issue by Zajozor** [mikecao/umami#434]
In a multi-user, multi-website environment, we would like to share a website between multiple accounts.

Judging from the schema (https://github.com/mikecao/umami/blob/master/sql/schema.postgresql.sql) websites are currently linked to a single user, which means it can be pretty difficult to introduce this as a non-breaking change, so I'd like to open up a conversation on whether you can imagine a change like that sometime in the future.

---
suggestion: 

we could remove user_id from the website table and using another table like:
```
create table account_websites {
   user_id int not null references account(user_id) on delete cascade,
   website_id int not null references website(website_id) on delete cascade,
}
```
and adjust the rest of the code accordingly.

On the frontend, when you are on the websites page in settings, we could have another "access" button, where you could see users and add/remove them from the website.
Probably fine if only admin can do this.
<img width="497" alt="CleanShot 2021-01-15 at 11 47 55@2x" src="https://user-images.githubusercontent.com/1835434/104715987-86181b80-5727-11eb-99c5-d0e53911574a.png">

I believe there shouldn't be a large performance hit, as auth queries aren't that frequent.

---

If you are ever open to this change (or some version of it), i'd be willing contribute.

Thanks for your time and an awesome app!

**Comment by mikecao** [comment]
The app was purposefully built to not have a complex role and permission system. If you want to share data among different accounts, that's what the share url feature is for. Just give the url to all the people you want to share with. Also, the admin account is able to see stats for all accounts in the system. This should cover most cases.

The problem with multiple owners is then any account can delete the website. Probably not what you want. And if you want to control who get to edit what, you're back to creating a bunch of new tables and forms to handle all that.

**Comment by Zajozor** [comment]
@mikecao thanks for the reply. I guess we'll manage or do some minor adjustments on our local installation.

If you believe that this would go against the "purpose" or "mission" of how umami is currently built,  please feel free to close this.

**Comment by mikecao** [comment]
Another thing you can do is simply grant admin to every user then everyone would be able to see all websites in the system. But you would have to manually update it in the database.

**Comment by ashwind-19** [comment]
> Another thing you can do is simply grant admin to every user then everyone would be able to see all websites in the system. But you would have to manually update it in the database.

I tried updating all users in the database to be an admin but they still can't see the sites.

**Comment by mikecao** [comment]
@ashwind-19 You need to go through Settings -> Accounts -> Dashboard link to see the other websites.

**Comment by ashwind-19** [comment]
ah got it... Thanks

**Comment by mikecao** [comment]
@ashwind-19 Looks like a bug. I never expected multiple admins to be a use case. Will fix.

**Comment by ashwind-19** [comment]
Thanks @mikecao. I forked this repo and added a new query to fetch all the websites if the user is an admin. I would be happy to PR if you want that to be included.
