### ISSUE TITLE
Geo at city level?

### ISSUE THREAD

**Issue by gabrielgggg** [mikecao/umami#437]
Hello!
Any way to report at the city or region rather than country level?
Thank you!

**Comment by mikecao** [comment]
No, we don't collect data beyond the country level.

**Comment by laurisvan** [comment]
@mikecao Sorry about bothering this one, but I'd like to know more about the design decision of restricting to country level access? Our service is highly local and would benefit from city level tracking. I doubt it is hardly a privacy concern, so what is it?
