### ISSUE TITLE
MongoDB Database Support

### ISSUE THREAD

**Issue by AkashRajpurohit** [mikecao/umami#439]
Hi @mikecao 
Thanks for creating this awesome project. I am planning to switch from GA to open source solution for basic analytics for my personal wesbite and landed on this amazing product.

I had one question, if there is any plan on roadmap to add support for mongodb database as well along with MySQL and PostgreSQL.

I have some credits already available on the mongodb atlas and would love to try it for shared database solution.

**Comment by mikecao** [comment]
The app uses prisma for database connections. It will depend on whether that project supports it in the future. You can follow the progress here, https://github.com/prisma/prisma/issues/1277#issuecomment-624532966

**Comment by mikecao** [comment]
Will revisit in the future. Closing for now.

**Comment by adityatelange** [comment]
Hello @mikecao, greetings of the day..

Its been a while and as per this PR https://github.com/prisma/prisma/issues/1277#issuecomment-624532966 MongoDB is now supported in Prisma :tada:  https://www.prisma.io/mongodb

Can we reopen this?
