### ISSUE TITLE
Integrate with Gridsome

### ISSUE THREAD

**Issue by buildingisfun** [mikecao/umami#443]
Hi @everyone,

I would like to integrate umami with Gridsome:
https://gridsome.org/

Just adding the tracking code in this format did not work:
<script async defer data-website-id="xxx-xxx-xxx-xxx" src="https://xxx.com/umami.js"></script>

Any help is welcome!

**Comment by mikecao** [comment]
The app is built with Next.js which is React based. It's not a Vue app.

**Comment by buildingisfun** [comment]
Sorry for the confusion.

I would like to know how to integrate the tracking code in Gridsome.
Tracking code:
<script async defer data-website-id="xxx-xxx-xxx-xxx" src="https://xxx.com/umami.js"></script>

Does anyone know how it works?

**Comment by jeferson-sb** [comment]
@buildingisfun you can just add script into the <head> of the [index.html](https://gridsome.org/docs/overriding-index/#overriding-indexhtml)
or add with `vue-meta` in the `main.js` like so:
```js
export default function (Vue, { head }) {
 head.script.push({
    src: 'https://xxx.com/umami.js',
    dataWebsiteId: 'xxx-xxx-xxx',
    defer: true,
    body: true,
  })
}
```

**Comment by buildingisfun** [comment]
umami is installed and works fine.
umami analyzes sites where the script is added into the <head> of the index.html.

@jeferson-sb thank you for your response!
My gridsome project does not have an index.html.
Therefore I added the following in the main.js (as suggested):

export default function (Vue, { head }) {
 head.script.push({
    src: 'https://xxx.com/umami.js',
    dataWebsiteId: 'xxx-xxx-xxx',
    defer: true,
    body: true,
  })
}

Unfortunately, umami does NOT recognize the site built with Gridsome.

What am I missing? Any idea?

**Comment by jeferson-sb** [comment]
@buildingisfun hmm the script tag is being renderer with the correct id (`data-website-id`)?

**Comment by buildingisfun** [comment]
@jeferson-sb yes, the id is correct.

Maybe it is because of 
data-website-id ... umami tracking code.
vs
dataWebsiteId ... your suggestion for Gridsome.

What do you think?
How could you implement 'data-website-id' in Gridsome?

**Comment by jeferson-sb** [comment]
@buildingisfun I guess instead of using the `head.script.push` command you can create a new index.html in your `src` directory and paste the script tag directly

```html
<!DOCTYPE html>
<html ${htmlAttrs}>
  <head>
    <script async defer data-website-id="YOUR_WEBSITEID_GENERATED_ON_UMAMI" src="UMAMI_URL/umami.js"> </script>
    ${head}
  </head>
  <body ${bodyAttrs}>
    ${app}
    ${scripts}
  </body>
</html>

```

If that didn't work, then it is most likely to be an error within your umami setup or project

**Comment by buildingisfun** [comment]
@jeferson-sb I created a new index.html and used the code provided in your last comment. This way it works! Thanks a lot!

Now, I am curious why it did not work in main.js with the code @jeferson-sb provided above. Does anyone know why?
