### ISSUE TITLE
Countries name is not show, using docker

### ISSUE THREAD

**Issue by sicenul** [mikecao/umami#444]
![image](https://user-images.githubusercontent.com/64000634/105794434-a1074d00-5fbd-11eb-9f2b-67fdcd651032.png)
As seen above, the country name's did not show at all.
How to fix and trace this? Please help.
I'm using docker-compose with PostgreSQL.

**Comment by mikecao** [comment]
Make sure your server is passing along the correct IP information. See, https://github.com/mikecao/umami/issues/415

**Comment by sicenul** [comment]
I have test using simple php code on my server, detecting `$_SERVER['REMOTE_ADDR']` and `$_SERVER['HTTP_X_FORWARDED_FOR']`. And the result is:
```
1. REMOTE_ADDR = 172.19.0.1
2. HTTP_X_FORWARDED_FOR = 172.16.20.3
```
It looks like the ip address of my vm (1) and my router (2). Looks like the problem is my router didn't forward public ip of visitor.
But I'm curious, how did you detect visitor's IP?

**Comment by mikecao** [comment]
The IP just needs to be passed along by your webserver. I am hosting on Vercel so they pass along the IP information correctly.

**Comment by sicenul** [comment]
Thank you for the time you spend to answer this issue. I'm closing it.

**Comment by frapa** [comment]
I had this issue as well, maybe it's worth mentioning it in the documentation?
