### ISSUE TITLE
[Enhancement] collect method should use Beacon API

### ISSUE THREAD

**Issue by marswong** [mikecao/umami#446]
Once window `unload` event is triggered, all requests would be aborted.

**Comment by mikecao** [comment]
I think this is more an enhancement than a bug. Only place I can think it would be useful is in tracking time spent on the page.

**Comment by marswong** [comment]
> I think this is more an enhancement than a bug. Only place I can think it would be useful is in tracking time spent on the page.

you're right. not just staytime, assume there are amounts of event, they could be collected asynchronously after user left the page, which would not hurt user experience.

**Comment by mikecao** [comment]
May need to do this to resolve issues with Firefox not firing events before page unload.

**Comment by AkashRajpurohit** [comment]
Is anyone working on this, if not, let me know if I try to put an MR for this @mikecao

**Comment by foosinn** [comment]
Thanks for fixing!
