### ISSUE TITLE
Pjax seems broken

### ISSUE THREAD

**Issue by hurui200320** [mikecao/umami#447]
Hi, I just switch to umami from matomo. And I suddenly found that pjax on my website seems broken. [Website Link](https://skyblond.info)

Here are some details:
by removing umami's tracking code, clicking on passages would generate a GET request to following URL:
```
https://skyblond.info/archives/422.html?_pjax=%23body
```

And requests are logged continually in chrome's network panel without checking `Preserve log`, which means the pjax kicks in and load the content.

After adding umami's tracking code, clicking on passages would generate a GET request to following URL:
```
https://skyblond.info/archives/422.html
```

There are no pjax suffix and earlier requests were flushed, I inferred pjax is broken after adding umami's tracking code.

Since I am a backend developer with zero experience in frontend, that's the limited information I can provide, but I'm glad to corporate and follow your instruction to fix this issue.

P.S: My blog framework allow me to execute some JavaScript code when pjax reload, I think that might be a solution?

**Comment by mikecao** [comment]
Can you post the network logs for those requests?

**Comment by hurui200320** [comment]
Do you mean the whole log from loading the website to clicking a page should have pjax, or just the requests on pages which should have pjax kicks in?

**Comment by mikecao** [comment]
I'd like to see the request stack with umami loaded to see what it's doing with the url.

Also, is your app using `pushState`? That is how it tracks url in dynamic apps. If it doesn't, then you might have to send the data yourself using tracker functions, https://umami.is/docs/tracker-functions.

**Comment by hurui200320** [comment]
I dump the logs into a `har` file using Chrome's DevTools export function: [har with umami.zip](https://github.com/mikecao/umami/files/5891961/har.with.umami.zip), where the `422.html` is the page which should have pjax kicks in. The pjax should be loaded and function before that request.

My website is based on a php blog framework `typecho`, it's a much simpler version of WordPress. And I just paste the umami's tracking js code `<script async defer data-website-id="31c91e76-****-****-****-47ed8f3d2483" src="https://****/umami.js"></script>` into `<header>` section.

With pjax enbaled, maybe I need use those tracker functions when pjax reload? But when including umami's js code, pjax seems not working anymore.

**Comment by hurui200320** [comment]
When clicking a link, there is a  error in console then being flushed very fast:
![image](https://user-images.githubusercontent.com/8587572/106244621-28ff8800-6246-11eb-811e-af2aaceb0b9b.png)

![image](https://user-images.githubusercontent.com/8587572/106244926-9ca19500-6246-11eb-868f-d648d692e339.png)

**Comment by hurui200320** [comment]
Looks like my blog framework is calling `window.history.replaceState(C.state, document.title)` to do pjax things (I guess), then umami is invoked by browser (I'm not sure how js work). Umami caused an exception at `return n.apply(null, e),`, where `n` is exactly the function `R`:
```javascript
R = function(t, e, n) {
    H(),
    L = I;
    var a = n.toString();
    I = "http" === a.substring(0, 4) ? "/" + a.split("/").splice(3).join("/") : a,
    P(I, L),
    setTimeout(A, 300)
};
```

Since it only provides `t` and `e` for function `R` by invoking `R.apply()`, thus parameter `n` is `undefined`. 

I **infer** that trying to invoke `toString()` on `undefined` cause this exception thus interrupt the pjax reloading, then something kicks in and fall back to default loading process, that's the one without pjax.

**Comment by hurui200320** [comment]
After a quick learning of nodejs, seems like codes in `hook` function https://github.com/mikecao/umami/blob/fe084756b2ebfc1b3f54bf0e6d5064f377fe9b99/lib/web.js#L38

is the `R.apply()`, where R is defined as `handlePush` in
https://github.com/mikecao/umami/blob/fe084756b2ebfc1b3f54bf0e6d5064f377fe9b99/tracker/index.js#L135

in this situation, `handlePush` need `(state, title, url)`, where `hook` invoked as `null, args`, corresponding as `state, title`, and then url is `undefined`.
By the definition  of `replaceStatus`, `url` is not guaranteed, thus url could be undefined. Calling `undefined.toString()` might throw an exception and break the pjax process.
