### ISSUE TITLE
[Bug] session_uuid conflict

### ISSUE THREAD

**Issue by marswong** [mikecao/umami#448]
the current `session_uuid` is easy to meet a conflict:

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: Unique constraint failed on the constraint: `session_uuid`
    at PrismaClientFetcher.request (/home/debian/umami/node_modules/@prisma/client/runtime/index.js:78130:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2002',
  clientVersion: '2.14.0',
  meta: { target: 'session_uuid' }
}
```

**Comment by mikecao** [comment]
When did you run into this error? There are checks to make sure the session_uuid already exists or not. Unless it's some race condition.

**Comment by andlil** [comment]
I get the same sometimes

today at 11:25  PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: Unique constraint failed on the fields: (`session_uuid`)
today at 11:25      at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:78130:15)
today at 11:25      at runMicrotasks (<anonymous>)
today at 11:25      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
today at 11:25    code: 'P2002',
today at 11:25    clientVersion: '2.14.0',
today at 11:25    meta: { target: [ 'session_uuid' ] }
today at 11:25  }

**Comment by marswong** [comment]
> When did you run into this error? There are checks to make sure the session_uuid already exists or not. Unless it's some race condition.

@mikecao  the records of `sessions` table is over 500,000 and it's easy to get this error for new users

**Comment by mikecao** [comment]
The collision rate of uuid is extremely high (2^61) so that's not likely to be the case. It's probably a session record hasn't been created yet and the same user already performed another action (race condition). I can look into some solutions to prevent it, but worse case you miss out on one record until the db has caught up.

**Comment by mikecao** [comment]
Tracking in #523
