### ISSUE TITLE
Internal Server Error for login. Used Docker

### ISSUE THREAD

**Issue by someuser8080** [mikecao/umami#449]
When I try Login in web-form, I receive errror: "Internal Server Error".

It from logs file:

$ next start
ready - started server on http://localhost:3000
PrismaClientInitializationError2 [PrismaClientInitializationError]: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   |
 6 |   provider = "mysql"
 7 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:78136:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.14.0'
}
____________________________________________

If database is postgresql:

PrismaClientInitializationError2 [PrismaClientInitializationError]: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   |
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:78136:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.14.0'
}

____________________________________________

I need to know. Please tell me.

In which directory to create the .env file? (If I use Docker)

Env file must be inside or outside Docker?

If the .env file should be inside Docker, how do you put the .env file inside Docker?

**Comment by someuser8080** [comment]
etc/bash.bashrc

I added these strings:

**Comment by someuser8080** [comment]
/root/umami/docker-compose.yml


version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
volumes:
  umami-db-data:

**Comment by mikecao** [comment]
I'm not that familiar with docker, but how are you starting up, using `docker-compose up` or running one of the images?

**Comment by someuser8080** [comment]
I started app so.

**Comment by sicenul** [comment]
Using docker-compose.yml as provided, it should work just fine as I did it.
```
$ cat docker-compose.yml
---
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
volumes:
  umami-db-data:
```
Then execute using:
```
$ docker-compose up -d
$ docker ps
NAMES               IMAGE                                     STATUS                 PORTS
umami_umami_1       ghcr.io/mikecao/umami:postgresql-latest   Up 56 seconds          0.0.0.0:3000->3000/tcp
umami_db_1          postgres:12-alpine                        Up About a minute      5432/tcp
```
Then open: `http://ip-server:3000`
Done

**Comment by EvidenceAdrien** [comment]
Have you dropped the tables in your DB ?

**Comment by adrianvillanueva997** [comment]
I also had this issue, you have to create a folder in the same folder as your docker compose, name it sql, after it, you have to download the postgresql schema from this repo and it just works. By default the docker-compose file just creates a folder inside the sql folder named schema.postresql.sql

**Comment by Linecutterx** [comment]
I can't tell from here what actually fixed it, but after making sure that the permissions for the directory were Ok I opened a console within the umami-db container & ran ```psql -h 127.0.0.1 -U umami -d umami -f /docker-entrypoint-initdb.d/schema.postgresql.sql```
After making sure that the sql file had been copied properly into the schema.postgres.sql file from the github repository (I actually used nano (+ cut&paste) to ensure that the format & permssions were OK)

**Comment by gnarlex** [comment]
@someuser8080 any updates on your end? Has your issue been resolved with the help of the others?
