### ISSUE TITLE
[Troubleshooting] Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by benricok** [mikecao/umami#450]
Hi,
I've been struggling to setup umami the past few days. I've tried it with both supported databases with no luck in displaying data in the dashboard. I've setup a test site and can see the currently active viewer count, but no data is displayed. 

When checking the console log, I'm receiving numerous type errors:
![umami error](https://user-images.githubusercontent.com/62467535/106139257-1e20f680-6165-11eb-841f-18aabdf20c04.png)
The last few errors (502) can be ignored because its gateway errors from my reverse proxy when I restarted the containers.

Here is the mysql docker compose file:
[docker-compose.yml (mysql).txt](https://github.com/mikecao/umami/files/5887084/docker-compose.yml.mysql.txt)

**Comment by mikecao** [comment]
Have you tried building the app without docker? Then you can eliminate if it's a docker issue or some other connection issue.
