### ISSUE TITLE
Auth/SSO options?

### ISSUE THREAD

**Issue by MACscr** [mikecao/umami#454]
I would love to use this with some of my clients, but the last thing i want to do is give them another login to manage. If there isn't any type of api to create accounts and websites, I am sure i could just do that direct through the database. My next concern though would be handling the authentication and sessions. I know its probably not supported, but any direction/suggestions you could give me?

**Comment by MACscr** [comment]
Actually this other issue https://github.com/mikecao/umami/issues/372 helps quite a bit. I am going to leave this open for any other suggestions though. Thanks!

**Comment by kieron** [comment]
+1 would also greatly appreciate SSO support.

**Comment by mikecao** [comment]
@MACscr The app uses the internal API for everything. I really need to get it documented. But basically you can create accounts, login, etc through the REST api endpoints.

**Comment by joshinat0r** [comment]
I wanted to get access to the JSON data a while ago and wrote myself a small API wrapper in JS
https://gist.github.com/joshinat0r/8f3428ab0a1de834d07efd29703c2c3f

Just a matter of looking at what umami does and then emulating the requests.

**Comment by mikecao** [comment]
Don't plan to add SSO anytime soon. It is possible to call the API endpoints directly to do this.
