### ISSUE TITLE
Hard-coded umami subdomain?

### ISSUE THREAD

**Issue by jallbrit** [mikecao/umami#457]
I followed the docker installation and nginx reverse proxy setup. However, I wanted to use my own subdomain (`analytics.mydomain.com`) instead of the default `umami.mydomain.com`. 

I figured that just changing the `server_name` in the nginx config file would allow me to set up any subdomain I wanted, like so:

```
server {
        server_name umami.mydomain.com;
```

However, if I tried to set up any subdomain other than `umami.mydomain.com`, the application failed to load (strangely, it sent me to the root domain `mydomain.com`). Changing the subdomain to `umami` fixed the problem immediately, with no other changes.

Is this subdomain somehow hard-coded, and could that be changed?

**Comment by mikecao** [comment]
Which docker setup are you referring to? It sounds like an issue with your nginx setup. There should be no defaults because it all depends on how you configure your domain at the DNS level.

**Comment by jallbrit** [comment]
Turns out, my browser (Firefox) was keeping some sort of cached version of `analytics.mydomain.com`, which made this very very hard to debug, because I was convinced the server was not configured properly. Once I wiped my browser cache for my domain, the subdomain works just fine. Thanks for your help, closing now.
