### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by slomchinskiy** [mikecao/umami#460]
[Screenshot 1](https://drive.google.com/file/d/1IHnN-xMT4z2nHMFpbe65Cbko1GSuh_zB/view?usp=sharing) / [Screenshot 2](https://drive.google.com/file/d/1KBYAcG_3greCV2iP839wy7ED7W6zZhZ_/view?usp=sharing)
Chrome 88.0.4324.93 / Android 11 / 1560x720 / vercel.com (deploy from Git).

**Comment by andlil** [comment]
Might as well add the realtime view on an iPhone.

My skills with mobile css and formatting is unfortunately rather limited.

![umami](https://user-images.githubusercontent.com/10003475/107019913-88a7e700-67a2-11eb-8a8c-bd810d24950d.png)

**Comment by nickradford** [comment]
@mikecao would you accept a PR to help fix this? Love the project and would be happy to help with the mobile rendering issues.

**Comment by andlil** [comment]
> @mikecao would you accept a PR to help fix this? Love the project and would be happy to help with the mobile rendering issues.

I think we all would appreciate your help!
