### ISSUE TITLE
Use third party ip geolocation api

### ISSUE THREAD

**Issue by sicenul** [mikecao/umami#461]
To easily get visitor ip address and detail geo location (country name, city name, lat, lng position, etc).

Is it possible to add (optionally) third party ip geolocation API, such as [ipgeolocationapi.com](https://ipgeolocationapi.com/) or [ipify.org](https://www.ipify.org/)
(psst... the ipify has node.js library)

Maybe it can answer #437 dan #444 :smiley:

**Comment by mikecao** [comment]
The app already uses an internal lookup database. That's how it's able to determine the country from the IP address. It's a design decision not to collect more data than just country.
