### ISSUE TITLE
Need unminified version of umami.js for submitting Firefox browser add-on

### ISSUE THREAD

**Issue by akash-wap** [mikecao/umami#462]
I tried to look everywhere I could. I am looking for the unminified version of umami.js file as Firefox does not allow minified or non-human-readable files because they need to review the content of all the files in the add-on. The tracker we get has minified JS. Will it be possible to point me to the unminified tracker that I can add to my add-on?

**Comment by mikecao** [comment]
This is the source code of the tracker, https://github.com/mikecao/umami/blob/master/tracker/index.js

**Comment by akash-wap** [comment]
Hi Mike. Thanks for replying. Will resolve this issue as soon as Firefox reviewers approve the source code.

**Comment by akash-wap** [comment]
I heard back from the Firefox add-on reviewers. Since this is a source code file so they need a compiled version that can be tested against the minified one https://app.umami.is/umami.js.
So we need to submit either a publicly-hosted compiled and minified file OR a human readable compiled and unminified file. If there are no options available then I can try to beautify the above link and submit that.

**Comment by mikecao** [comment]
I don't really understand what this add-on is supposed to do. Also what do you mean by compiled? It's just javascript, as either source or minified.

**Comment by akash-wap** [comment]
What I meant was the link you shared ( https://github.com/mikecao/umami/blob/master/tracker/index.js ) is importing some libraries and they are further importing some more files.

We added the umami.js inside our add-on locally so replacing the minified local file's content with this file won't help us as other libraries won't be available.

Anyway thanks for your help. I will just beautify the minified file.
