### ISSUE TITLE
Need custom event

### ISSUE THREAD

**Issue by saiftheboss7** [mikecao/umami#463]
Would love to get custom event support if possible. 

Found that they Gingertag[](https://gingertag.com/?ref=producthunt)  doing it nicely despite being a privacy friendly tracker

**Comment by mikecao** [comment]
What do you mean? All events are custom.

**Comment by saiftheboss7** [comment]
I mean I should be able to track custom events.

For example, I have a website that has a radio button. Once a user clicks the radio button - I send a custom event to umami and get analytics data from those custom events

**Comment by saiftheboss7** [comment]
Check the custom event tracking from here https://gingertag.com/

**Comment by mikecao** [comment]
https://umami.is/docs/track-events

**Comment by saiftheboss7** [comment]
Thanks very much. Didn't know about it. Closing the thread.
