### ISSUE TITLE
Table prefix support?

### ISSUE THREAD

**Issue by skoshy** [mikecao/umami#464]
Wanted to see if there's support to use a table prefix with Umami so I can use an existing database for multiple installations. Would this be possible via an ENV variable?

**Comment by mikecao** [comment]
It should be possible now with Prisma. You can remap the tables to different table names, https://www.prisma.io/docs/concepts/components/prisma-client/generating-prisma-client/customizing-the-prisma-client-api

However if you don't want to mess around with it, we can consider adding an .env variable.

**Comment by mikecao** [comment]
After reviewing, it looks like this only possible using mapping in prisma. When prisma builds the client, it doesn't recognize the .env variable.
