### ISSUE TITLE
Time notation is different between pages

### ISSUE THREAD

**Issue by reithose** [mikecao/umami#465]
v1.12.0
The realtime page uses 24 hour time notation. Dashboard and detailspage use 12 hour notation (am/pm). A setting in the profile menu could solve this issue.

**Comment by andlil** [comment]
Defintely, I think the default should be full ISO8601 #193

**Comment by reithose** [comment]
I discovered the realtime page doesn't use 24 hour time notation. This is around noon:
![image](https://user-images.githubusercontent.com/6649052/107361266-66ca9f00-6ad7-11eb-9a80-a2f58acfd647.png)
