### ISSUE TITLE
Filter events by their event type

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#466]
First of all: Great work on this project, love it ❤️ 

Umami allows to create events with a custom type. It would be awesome if the dashboard allows the user to filter events of a website by their type.

Currently, the view looks something like this:

<img width="731" alt="Screenshot 2021-02-06 at 11 26 35" src="https://user-images.githubusercontent.com/24435169/107115677-962aa300-686e-11eb-8acb-b27750df21ae.png">

Adding a filter selection above it would be a great addition for analyzing sites with a lot of event traffic.

**Comment by bayerlse** [comment]
Hey there! Are filters deleted in the latest version?
When having a look at [v1.39.0](https://github.com/umami-software/umami/releases/tag/v1.39.0) there should be the possibility to filter events, but not in the current version v2.3.0 ?

**Comment by vashchukmaksim** [comment]
Any updates? I can't see that functionality either...
