### ISSUE TITLE
Installing tables for umami database - mysql

### ISSUE THREAD

**Issue by stamatim** [mikecao/umami#468]
I have created a database table called 'umami' on my Ubuntu server. 

When entering in the command `mysql -u username -p databasename < sql/schema.mysql.sql`, I get the following error message:

`-bash: sql/schema.mysql.sql: No such file or directory`

Any idea what is wrong?

**Comment by mikecao** [comment]
Where are you running the command from?

**Comment by stamatim** [comment]
I am running it from `/var/www/html`. I also tried to run it from `/etc/mysql` and I got the same error. Am I not running it in the correct place?

**Comment by mikecao** [comment]
You need to run it from the umami root, where `sql/schema.mysql.sql` exists.

**Comment by stamatim** [comment]
I see. I tried that and it worked, thanks!
