### ISSUE TITLE
Documentation: Duplicate page views when using Next.js

### ISSUE THREAD

**Issue by nickradford** [mikecao/umami#471]
I'm opening this issue (and will close it) to document something I came across when using the tracking code in the `<head>` of a Next.js app. There's nothing actionable here, just want this to be a resource should someone else come across this.

## Problem
If you have *both* a custom `_app.js` and `_document.js`, and you put the tracking script in the `<head>` of the `_app.js`, you will get duplicate page views in umami.

## Fix
Put the tracking script in your `_document.js`. 

I'm not 100% sure what happens when rendering the document and app within Next.js, but having the script in the `_app.js` seems to trigger page views twice, possibly due to remounting the component returned from `_app.js`.

**Comment by mikecao** [comment]
Probably related to this, https://github.com/vercel/next.js/issues/9070

**Comment by nickradford** [comment]
Oh, interesting. I'll have to try changing `<script async ...>` to `<script async='async' ...>` and see if that works. Good find!
