### ISSUE TITLE
Help: Connecting Umami to Supabase

### ISSUE THREAD

**Issue by ShubhamVerma1811** [mikecao/umami#474]
Hey,
I needed help with Supabase connection.
I copied the DB connection string and pasted it in vercel's .env but it didn't work.
A dedicated doc on the website might be useful.

**Comment by mikecao** [comment]
Did you follow this? https://umami.is/docs/running-on-vercel

**Comment by ShubhamVerma1811** [comment]
Yes i did, pasted the connection string from Supabase into that Envs. I threw 502 error while login in with default creds.

**Comment by ShubhamVerma1811** [comment]
I found this blog today
https://dev.to/jakobbouchard/setting-up-umami-with-vercel-and-supabase-3a73
It helped me, but I had to manually create the tables first.
You can maybe add to the docs and close this issue?

**Comment by mikecao** [comment]
Create database tables is the second step of the install, https://umami.is/docs/install
