### ISSUE TITLE
Add PropTypes to components

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#475]
Hey there! ✌️😁

Is there a plan to add [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) to this project's React components?

Currently I'm working on a possible solution for https://github.com/mikecao/umami/issues/466 and I noticed that none of the components I've encountered have typed properties. Per the discussion in https://github.com/mikecao/umami/issues/238 I figure that Typescript won't be added anytime soon, so my question is if `prop-types` will be added at least.

I hear your [concerns regarding development velocity](https://github.com/mikecao/umami/issues/238#issuecomment-701779943). But untyped components slow adoption rate and development speed of (new) contributors (a much greater source of development velocity, if I might say so 😅).

Let me know what you think ✌️

**Comment by mikecao** [comment]
Now that the components are more stable it should be easy to do. I'll gladly take a PR if anyone wants to do it.
