### ISSUE TITLE
Domain input allows scheme prefix

### ISSUE THREAD

**Issue by marcauberer** [mikecao/umami#479]
Hi,
first of all thanks for your work to build this awesome tool!
I found a bug on the realtime page and potentially on other pages.
I've registered my websites in the settings with attached scheme (for instance: `https://www.example.com`).
On the realtime page, the subpages are displayed correctly, but when clicking it to open the website, it results in something like this: `https://https//www.example.com/en/`.

It's not the worst bug, but without it, your tool would be perfect ;)

**Comment by mikecao** [comment]
I think the real bug is it allowed you to enter the scheme in the domain name field. It should only allow just the domain name.
