### ISSUE TITLE
Unable to "npm run build"

### ISSUE THREAD

**Issue by helterskelter01** [mikecao/umami#480]
Hello, I am trying to install this software. 

I have nodejs v12.20.1 and npm 7.5.4. 

Was following this information:
https://umami.is/docs/install

Steps: 
1. git clone https://github.com/mikecao/umami.git - OK
2. cd umami - OK
3. npm install - OK
4. mysql -u username -p databasename < sql/schema.mysql.sql - OK
5. create .env -OK
6. npm run build - ERROR :

Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
Emitted 'error' event on Gunzip instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Gunzip.onerror (_stream_readable.js:754:7)
    at Gunzip.emit (events.js:314:20)
    at Zlib.zlibOnError [as onerror] (zlib.js:185:8) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
npm ERR! code 1
npm ERR! path /tmp/umami
npm ERR! command failed
npm ERR! command sh -c node scripts/build-geo.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-16T10_37_12_652Z-debug.log
ERROR: "build-geo" exited with 1.
npm ERR! code 1
npm ERR! path /tmp/umami
npm ERR! command failed
npm ERR! command sh -c npm-run-all build-tracker build-lang build-geo build-db build-app

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-16T10_37_12_670Z-debug.log

**Comment by mikecao** [comment]
Try running `npm run build-geo` by itself and see if it errors out.

**Comment by helterskelter01** [comment]
npm run build-geo

> umami@1.12.0 build-geo
> node scripts/build-geo.js

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
Emitted 'error' event on Gunzip instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Gunzip.onerror (_stream_readable.js:754:7)
    at Gunzip.emit (events.js:314:20)
    at Zlib.zlibOnError [as onerror] (zlib.js:185:8) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
npm ERR! code 1
npm ERR! path /tmp/umami
npm ERR! command failed
npm ERR! command sh -c node scripts/build-geo.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-17T09_00_44_807Z-debug.log

**Comment by mikecao** [comment]
All the script does it download a zip file and try to extract it. Are you on a shared environment? It seems like `/tmp/umami` has some permissions issues.

**Comment by helterskelter01** [comment]
No /tmp/ is a local directory if that is what you are asking for. I have full permissions since I am doing this as root.

**Comment by mikecao** [comment]
Then I'm not sure what is going on. Maybe you need zlib installed at the OS level?

**Comment by helterskelter01** [comment]
zlib is installed. I am using RHEL 7.9. Which OS was this tested on?

root@du-umami-test:~/umami# rpm -qa | grep zlib
zlib-ada-devel-1.4-0.5.20120830CVS.el7.x86_64
zlib-static-1.2.7-19.el7_9.x86_64
zlib-devel-1.2.7-19.el7_9.x86_64
zlib-ada-1.4-0.5.20120830CVS.el7.x86_64
zlib-1.2.7-19.el7_9.x86_64

**Comment by mikecao** [comment]
I've tested on Windows and Ubuntu. Are there are files inside of your `/tmp/umami`? It first downloads the file then tries to extract it.

**Comment by helterskelter01** [comment]
I am using RHEL 7 and RHEL 8. 

Got it working by removing the build-geo steps from package.json. Downloaded the Geolite-Contry package myself and extracted to ./public/geo/. 

Then I ran "npm run build" and now it works.

**Comment by mikecao** [comment]
Glad it worked for you now. I still wonder why the script wouldn't work if you were able to manually do the same thing 🤷
