### ISSUE TITLE
Only one registered browser and OS, but 4 visitors?

### ISSUE THREAD

**Issue by NoLooseEnds** [mikecao/umami#482]
Any input on why I can just see one browser and one OS, but have 4 visitors. 

I'm also a bit curious about the bounce rate, when I know for a fact (since one of those visitors is me) that I did not bounce, but browsed the site rather extensively. 

<img width="1139" alt="Screenshot 2021-02-17 at 22 04 29" src="https://user-images.githubusercontent.com/4103531/108267922-1e148500-716c-11eb-8831-0103b3ff1e40.png">

Appreciate all the good work that went into this. Exactly what I was looking for. :)

**Comment by mikecao** [comment]
Unknown browsers and OSes are not listed. Can you query the database and see what are in those columns?

**Comment by NoLooseEnds** [comment]
I don't have much experience, but I think I did it correct by using `psql` and issuing `TABLE session;`. It looks empty.

```
umami=# TABLE session;
 session_id |             session_uuid             | website_id |          created_at           |    hostname     | browser |   os   | device  |  screen   | language | country
------------+--------------------------------------+------------+-------------------------------+-----------------+---------+--------+---------+-----------+----------+---------
          3 | bf51c643-6ceb-5f4b-a7e1-6e8d40895632 |          4 | 2021-02-16 23:26:37.443858+00 | domain.com |         |        | tablet  | 800x600   | en-US    | US
          5 | 58c9a7a9-8bff-52ac-a4c5-6bd7493a43ca |          4 | 2021-02-16 23:26:37.769839+00 | domain.com | firefox | Mac OS | laptop  | 1680x1050 | en-GB    | NO
          7 | e37b6f44-1bd0-50eb-badb-32ab59ec6932 |          4 | 2021-02-17 00:49:01.360254+00 | domain.com |         |        | desktop | 1920x1080 | en-US    | FR
          8 | 466f5afb-0409-5826-87c9-f0398d367624 |          4 | 2021-02-17 08:03:36.004034+00 | domain.com |         |        | tablet  | 800x600   | en-US    | US
```

I have a few sites, so I excluded the other domains than the one from the screenshot.

**Comment by mikecao** [comment]
Looks like those fields are blank for 3 visitors so that is why you're not seeing them in the UI.

**Comment by NoLooseEnds** [comment]
Yes, that's what I figured. The question is why? :)

**Comment by gnarlex** [comment]
What if we add unknown browsers/OSs/countries to the UI and group them under the name "Unknown"? That way there would be no confusion due to numbers not adding up.

**Comment by mikecao** [comment]
@NoLooseEnds The browser/os is determined from the user-agent string. If the client sends an unrecognizable string or none at all, it will be unknown.

@gnarlex Yea we can add an unknown count.

**Comment by NoLooseEnds** [comment]
Yes, that would be helpful. :)

If the user-agent string provides a browser and/or OS that is not well known, is it just ignored all together? Or is It put in the db and just not displayed?

**Comment by mikecao** [comment]
The bounce rate has a cut-off factor to decide what is a bounce, I believe it's at 1 hour. Or it could just be a bug...

**Comment by NoLooseEnds** [comment]
Let me know if there is anything I can help with if we were to debug the bounce rate.
