### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by dect0r** [mikecao/umami#49]
Hi there,

i just installed umami and set everything up. After adding the script in a website i get the following error:

`TypeError: undefined is not an Object. (evaluating '"msTrackingProtectionEnabled"in window.external')`

No tracking seems to happen.
Tested with Safari 13.1.2 and Brave on MacOS 10.15.6

Anything I can change to make it work?
Thx

**Comment by mikecao** [comment]
Tracker build is now in the main build.
