### ISSUE TITLE
Feature: Event Funnels

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#493]
Something that would make umami extremely more valuable IMO is the ability to create and analyze event funnels. Something along the lines of [Amplitude's event funnels](https://help.amplitude.com/hc/en-us/articles/360052745632). I remember it was the first thing I was missing, when we introduced it to our team 😄 I think that would draw even more people in.

Unfortunately I'm still not very fond of the inner workings of umami. Is adding an event funnel even possible right now?

Also, I'd say introducing an enhancement that big would be more of a feature-"branch" than a single pull request, as there are many aspects to it.

**Comment by mikecao** [comment]
umami was never meant to be an enterprise level analytics suite. It just collects some basic data and displays it nicely. I think funnels, marketing campaigns, heatmaps, etc all are out of scope for umami.
