### ISSUE TITLE
Bug: "No data available" is not displayed in dashboard

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#498]
In the dashboard, an empty table does not display the "No data available" caption like in the detailed view.

<img height="350" alt="Screenshot 2021-02-21 at 09 47 24" src="https://user-images.githubusercontent.com/24435169/108625382-f151bd80-744a-11eb-8a7e-4aa7d866bf95.png"> <img height="350" alt="Screenshot 2021-02-21 at 09 47 42" src="https://user-images.githubusercontent.com/24435169/108625390-fa428f00-744a-11eb-9194-77c7bb3984e6.png">

**Comment by mikecao** [comment]
Fixed in v1.14.0
