### ISSUE TITLE
Displaying visitor from unknown country in real time log

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#501]
The real time logs have no way of properly captioning a visitor from an unknown country:

<img width="396" alt="Screenshot 2021-02-21 at 15 14 07" src="https://user-images.githubusercontent.com/24435169/108628892-88277580-745d-11eb-8871-1bf0d0cfce77.png">

This affects analytics in a private network.

**Comment by vsolanogo** [comment]
Does umami support country recognition? I get unknown countries for every record

**Comment by gnarlex** [comment]
Do you have a proxy before umami? Had the same problem because I forgot to parse the users IP via the `X-Forwarded-For` header from proxy to umami.

**Comment by vsolanogo** [comment]
> 
> 
> Do you have a proxy before umami? Had the same problem because I forgot to parse the users IP via the `X-Forwarded-For` header from proxy to umami.

thx, my nginx config didn't have it

**Comment by Quin452** [comment]
> Do you have a proxy before umami? Had the same problem because I forgot to parse the users IP via the `X-Forwarded-For` header from proxy to umami.

This is the answer for me.  Perhaps it could be included in the docs?
I'm fairly new to Nginx reverse proxy, so it wasn't obvious for me.

I've used this snippet elsewhere (just after the `proxy_pass` line), so it may be overkill 😛 
```
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
