### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#505]
Some error messages are not descriptive and confuse the user (see #503 for an example). This makes troubleshooting harder and can heavily impact user experience.

Adding descriptive error message can help the user solving problems by themselves and otherwise help developers troubleshooting.

In the case of #503 the error display could for example display an error message sent by the api: "Invalid domain name."

**Comment by mikecao** [comment]
Technically, you should never see the error messages. If they show up, then we have a bug we need to fix. The `Something went wrong` is just a catchall for any errors instead of a blank screen so the use can at least report the issue.

**Comment by mikecao** [comment]
Closing as this has been changed by f7201c9
