### ISSUE TITLE
Prisma fails with 'column is too long' for keycloak oidc referrer

### ISSUE THREAD

**Issue by mgorsk1** [mikecao/umami#509]
We are running web app behind keycloak with oidc. Since oidc referrer sometimes exceeds limit of 500 characters set in referrer column, stats are not collected on front page.

![image](https://user-images.githubusercontent.com/5680655/109125930-f4032a00-774c-11eb-806e-adcdbcaf9e11.png)

**Comment by mikecao** [comment]
I think it may be already too late to update the database for people who already have it installed, unless we create a database upgrade script. But that might be overkill for such a small change most people won't need. Do you actually require the entire length of the url, or is truncated data ok? I am not familiar with keycloak or what is it used for.

**Comment by mgorsk1** [comment]
Indeed people who already created the db would have to migrate to the new schema. This was more of a suggestion for future users. The issue for us is that data is not truncated - it's just not loaded into database when this error occurs.
