### ISSUE TITLE
Question about heroku postgres credential rotation

### ISSUE THREAD

**Issue by jackysee** [mikecao/umami#511]
In the db setting of heroku, it states that
```
Please note that these credentials are not permanent.

Heroku rotates credentials periodically and updates applications where this database is attached.
```
I check the env vars, I think it is `HEROKU_POSTGRESQL_NAVY_URL`. So in order for umami to work, I have:

1. create `DATABASE_URL` var copying the `HEROKU_POSTGRESQL_NAVY_URL`
2. modify the value as it starts with `postgres://` instead of `postgresql://`

Does that mean in case the credential rotates, I need to copy that again?

**Comment by mikecao** [comment]
Not that familiar with heroku, but if the database credentials change, then yes you have to copy the new values to the `DATABASE_URL` and restart the app. However, the app can recognize either `postgres` or `postgresql`.

**Comment by jackysee** [comment]
I found that it should be my mistake in the setting so when it install DB, it uses another env var rather than `DATABASE_URL`.
