### ISSUE TITLE
Theme button "thinner" on mobile

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#514]
Mobile view only: The theme button has width of the containing icon instead of the 50px as planned, resulting in a **smaller tap target**. Like this:

<img width="430" alt="Screenshot 2021-03-01 at 10 35 38" src="https://user-images.githubusercontent.com/24435169/109478830-07c6cd00-7a7a-11eb-952f-3c57dbb9a3a9.png">

After playing around I found out it's due to the container having only class `col-6`. Changing the space distribution of the header between title and buttons from `1:1` to `1:2` would solve it. I.e. apply classes `col-4` and `col-8` respectively.

This is how it would look like:

<img width="389" alt="Screenshot 2021-03-01 at 10 46 11" src="https://user-images.githubusercontent.com/24435169/109480057-59238c00-7a7b-11eb-8df9-a7f91f2e619b.png">

**Comment by mikecao** [comment]
This is no long applicable due to the hamburger menu change for mobile.
