### ISSUE TITLE
Favicons are loaded from wrong path on umami dashboard 

### ISSUE THREAD

**Issue by meirroth** [mikecao/umami#517]
Favicons are loaded from a relative path instead of the root, see code references below:
https://github.com/mikecao/umami/blob/7eb0ca8034374c69f50f2c25126bc866594d3bd1/pages/_app.js#L32-L36
https://github.com/mikecao/umami/blob/0b8336f10354e3c11c0146ef74155cd35fd9085e/components/layout/Layout.js#L11

 Made a quick fix pull request #516

**Comment by mikecao** [comment]
We need to take the `basePath` into account.

**Comment by meirroth** [comment]
Something like this will work? (I am not so familiar with react, this is from what I saw used in other places in the project)
```
import { useRouter } from 'next/router';
...
const { basePath } = useRouter();
...
<link rel="apple-touch-icon" sizes="180x180" href="`${ basePath }`/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="`${ basePath }`/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="`${ basePath }`/favicon-16x16.png" />
<link rel="manifest" href="`${ basePath }`/site.webmanifest" />
<link rel="mask-icon" href="`${ basePath }`/safari-pinned-tab.svg" color="#5bbad5" />
```

**Comment by gnarlex** [comment]
This should work:
```jsx
// ...
import { useRouter } from 'next/router';
// ...

export default function Layout(/* ... */) {
  const { basePath } = useRouter();
  
  return (
    <>
      <Head>
        {/* ... */}
        <link rel="icon" href={`${basePath}/favicon.ico`} />
        {/* ... */}
      </Head>
    </>
 )
}
```

Can confirm that after prepending `basePath` like this, the issue no longer occurs.

**Comment by mikecao** [comment]
@meirroth Can you update your PR #516 with the fix?

**Comment by meirroth** [comment]
Sure!
