### ISSUE TITLE
'Ignore my visits' checkbox for logged in users

### ISSUE THREAD

**Issue by timoschwarzer** [mikecao/umami#519]
First up, thank you for this awesome project! :rocket: 

I'd like an option to disable tracking for logged in users. Primarily I don't want my own visits to be counted when viewing my websites for monitoring/testing purposes. Setting an IP filter each time is not an option because my ISP gives me a new one each day.

If you generally like the idea, I'm happy to put a PR together :)

**Comment by mikecao** [comment]
You can already do that. Just set `umami.disabled` to true in local storage.

**Comment by timoschwarzer** [comment]
I feel dumb now :laughing:.

Would you take a PR that makes this an option in the settings? Manually setting items in local storage on phones is pretty cumbersome...

**Comment by mikecao** [comment]
You would have to add the value to your website, so having it under the admin wouldn't help.
