### ISSUE TITLE
duplicate key value violates constraint "session_session_uuid_key"

### ISSUE THREAD

**Issue by craigconstantine** [mikecao/umami#523]
Umami v1.14.0
Postgresql 12

I'm seeing this error logged from my Postgresql db, roughly, every 10 minutes.

    ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"

I've attached a screenshot of the Umami current activity, in case that helps.

<img width="1195" alt="Screen Shot 2021-03-07 at 08 09 12" src="https://user-images.githubusercontent.com/2278992/110240986-7beeee00-7f1c-11eb-967b-788cb6dee062.png">

Postgres provides more details on the query, syslog entries:

    syslog.1:Mar  6 23:43:46 ns postgres_ns[647043]: [7-1] 2021-03-06 23:43:46.762 UTC [647043] umami@umami ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"
    syslog.1:Mar  6 23:43:46 ns postgres_ns[647043]: [7-2] 2021-03-06 23:43:46.762 UTC [647043] umami@umami DETAIL:  Key (session_uuid)=(ef8f21a3-58ac-53e6-880a-9e3e51ed59ec) already exists.
    syslog.1:Mar  6 23:43:46 ns postgres_ns[647043]: [7-3] 2021-03-06 23:43:46.762 UTC [647043] umami@umami STATEMENT:  INSERT INTO "public"."session" ("session_uuid","website_id","created_at","hostname","browser","os","screen","language","country","device") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "public"."session"."session_id"`

With the syslog stuff trimmed, thats…

    ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"
    DETAIL:  Key (session_uuid)=(ef8f21a3-58ac-53e6-880a-9e3e51ed59ec) already exists.
    STATEMENT:  INSERT INTO "public"."session ("session_uuid","website_id","created_at","hostname","browser","os","screen","language","country","device") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "public"."session"."session_id"`

I see that same set of logs for each of the errors, (with a different value for session_uuid.)

**Comment by mikecao** [comment]
This is likely a race condition where the session id was inserted right because the second insert was run. You are not losing any data. It's a rare occurrence but we will try to fix it.

**Comment by craig-constantine** [comment]
If the INSERT failure is harmless (from Umami point of view) could we just use an

    on conflict do nothing

clause? That's support since Postgres 12 at least, not sure about other db backends though.

**Comment by mikecao** [comment]
yea, that would work for postgres and you're free to change it if you don't like seeing that error. I'd still like to find a more universal solution though.
