### ISSUE TITLE
Occupied and disputed territories on the map

### ISSUE THREAD

**Issue by denysdovhan** [mikecao/umami#525]
First of all, thanks for creating this project!

I've noticed the map displays some disputed territories by _on the ground_ rule, which will eventually violate some local laws and might trigger some people. For example:

 I'm from Ukraine. Russia illegally annexed the Crimea peninsula in 2014. This act was not recognized by almost every country, but your map shows Crimea as a part of Russia:

<img width="457" alt="Screenshot 2021-03-06 at 00 55 48" src="https://user-images.githubusercontent.com/3459374/110249489-ee90b580-7f7e-11eb-9870-5525c334d4b4.png">

This looks offensive and displays support to the Russian war machine. Additionally, this map shows unrecognized [Northem Cyprus](https://en.wikipedia.org/wiki/Northern_Cyprus).

Yes, I know you're using `react-simple-maps` and vector maps by [natural-earth-vector](https://github.com/nvkelso/natural-earth-vector). I just want to let you know, that this map might be offensive. You should [use `admin_0` geojson maps](https://github.com/nvkelso/natural-earth-vector/tree/master/geojson) to avoid this.

You can find additional info about this issue here: https://github.com/nvkelso/natural-earth-vector/issues?q=is%3Aissue+is%3Aopen+crimea

**Comment by denysdovhan** [comment]
I also opened an issue in `react-simple-maps` repo: https://github.com/zcreativelabs/react-simple-maps/issues/251

**Comment by webknjaz** [comment]
> I just want to let you know, that this map might be offensive.

No, not "might be". It **is** offensive and hugely politically incorrect. I think that data source should be switched to something respected.

**Comment by denysdovhan** [comment]
@webknjaz I agree. For me, personally, it is offensive. My eyes are hurting every time I see this map. Though, I'm trying to be as polite as possible.

**Comment by mikecao** [comment]
I don't really have a political opinion on the matter. I will just wait for `react-simple-maps` to make the change and I will gladly update. And switching to `admin_0` does not help because it still lists the territory as Russia.

![image](https://user-images.githubusercontent.com/477975/110269535-cd2ccb00-7f78-11eb-8c09-1ea4a40ff1da.png)

**Comment by webknjaz** [comment]
> I don't really have a political opinion on the matter.

That sounds exactly like a political opinion of continuing to offend Ukrainians.

**Comment by mikecao** [comment]
Will update once the dependencies update.

**Comment by denysdovhan** [comment]
@mikecao I've found a [datamaps]() project which contains a correct map. Would you mind using this instead of the wrong one?

Plausible.io project is using it [like this](https://github.com/plausible/analytics/blob/ff32218bd030f28b0d9ee80dc39952a190d8faab/assets/js/dashboard/filters.js#L146):

```
Datamap.prototype.worldTopo.objects.world.geometries
```

It can also be easily installed via `npm`, so you don't have to update deps manually in the future.

**Comment by denysdovhan** [comment]
Hey @mikecao, I've sent a PR with a fix: #575

Hopefully, we will get this merged soon to resolve this unpleasant mistake.
