### ISSUE TITLE
[Troubleshooting] Could not read from input file: Is a directory

### ISSUE THREAD

**Issue by king-gheedorah** [mikecao/umami#527]
Having an issue with the latest Docker install.

Steps to reproduce:

1. Copy the docker-compose.yml from master
2. docker-compose up -d

The error is listed at the end of this log:

```
db_1                      | server started
db_1                      | CREATE DATABASE
db_1                      |
db_1                      |
db_1                      | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema.postgresql.sql
db_1                      | psql:/docker-entrypoint-initdb.d/schema.postgresql.sql: error: could not read from input file: Is a directory
```
Any idea why this is happening? I've tried removing the Docker volume, removing the containers, deleting the bind folder before reloading. No dice.

**Comment by adrianvillanueva997** [comment]
Hello, I had this issue as well, you have to manually create a folder named sql in the path of the docker-compose.yml file and copy the postgresql file from the sql repository folder

**Comment by linkslegend** [comment]
I added the postgresql file into the sql folder and now I'm getting this error 

`Starting umami_db_1 ... error

ERROR: for umami_db_1  Cannot start service db: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/umami/sql/schema.postgresql.sql" to rootfs at "/docker-entrypoint-initdb.d/schema.postgresql.sql" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/umami/sql/schema.postgresql.sql" to rootfs at "/docker-entrypoint-initdb.d/schema.postgresql.sql" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

**Comment by AryRamires** [comment]
what solution did you arrive at?
