### ISSUE TITLE
running Umami on an Raspberry pi

### ISSUE THREAD

**Issue by Iqwertz** [mikecao/umami#531]
I try to get umami working on an rpi 4b+!
I know it is possible due to Issue #272
In this Issue is an nice explenation how to activate Prisma however I can't find the binaries for ARM and I am unable to compile them! Therefor it would be great if someone could provide binaries that work for a raspberry pie or point me to an location where to find them!

Thanks a lot!

**Comment by mikecao** [comment]
Closing this as an issue. You can use the Discussions tab to ask for help if needed.
