### ISSUE TITLE
Possible to segment data by browser, os, device, country, etc?

### ISSUE THREAD

**Issue by pqvst** [mikecao/umami#533]
I see that I can segment data by page (url) and referrer - but not by the other dimensions (e.g. browser, os, device, and country). It would be nice to be able to segment the data by these dimensions as well. For example, some use-cases might be:

- Show my all traffic from a specific country
- Show me all traffic excluding a specific browser/os/device

**Comment by mikecao** [comment]
Available in v1.30.0
