### ISSUE TITLE
[UI] Scrolling position

### ISSUE THREAD

**Issue by robsontenorio** [mikecao/umami#535]
This is not a bug, but an improvement.

When clicking on every link on dashboard, causes a scroll to top. For better experience, woud be nice to keep scroll position. Here is an example, but aplies to any secction on dashboard.

![image](https://user-images.githubusercontent.com/118955/110640706-e491d100-818f-11eb-90e6-28c869cdfaae.png)

**Comment by mikecao** [comment]
Hmm, I've never noticed that before. I don't think I explicitly force a scroll to top. Must be something weird happening when it re-renders.

**Comment by robsontenorio** [comment]
Here is 

![umami](https://user-images.githubusercontent.com/118955/110769548-0c883f80-8237-11eb-9368-6ad74b18656d.gif)
