### ISSUE TITLE
Timeout error when deploying to Vercel

### ISSUE THREAD

**Issue by Okozzie** [mikecao/umami#536]
I am able to reach the login page, but when I type in the credentials it returns a `Internal Server Error`.

Here's the error log

`ERROR	PrismaClientInitializationError2 [PrismaClientInitializationError]: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter`

**Comment by mikecao** [comment]
Are you sure you have the correct database connection string?
