### ISSUE TITLE
[Feature Request] Display trackEvent "url" at dashboard

### ISSUE THREAD

**Issue by robsontenorio** [mikecao/umami#538]
According to the docs its possible to pass a `url` related to the event.

```
umami.trackEvent(event_value, event_type, [url], [website_id])
```

- Just can see it is saved at database. 
- But the dashboard does not make use of it.

It would be usefull someway to display that `url` on events dashboard. Maybe a tooltip on mouse hover? A new column? Or am I missing something?

![image](https://user-images.githubusercontent.com/118955/110806601-fc855580-8260-11eb-8f26-f2b7a9b1ae10.png)

**Comment by mikecao** [comment]
The problem is you can have multiple event type/value combos across many different urls. The url is just there in the database in case you want to do any external reporting.

**Comment by robsontenorio** [comment]
It is fair.
