### ISSUE TITLE
Little To No Data Collection Out Of Nowhere

### ISSUE THREAD

**Issue by adudeongithub** [mikecao/umami#540]
Does anyone have any idea or guess what happened here?
https://i.ibb.co/vVMXcxN/Screen-Shot-2021-03-11-at-5-49-16-PM.png

At some point last night, Umami simply stopped collecting data on my website. The only thing I suspect as a possible culprit is the upgrade of Wordpress I did (now running current version, 5.7) just hours before this happened.

Thanks in advance for any help or insight.

**Comment by mikecao** [comment]
Go to your website, open up the developer tools and go to the network tab. You should see requests to `/api/collect`. If you don't there is something wrong with your setup.

**Comment by adudeongithub** [comment]
Thanks for the response, @mikecao.

I think it had something to do with the fact that the version of Umami I was running wasn't current. Fixed now.
