### ISSUE TITLE
IGNORE_IP does not support cider notation

### ISSUE THREAD

**Issue by ntimo** [mikecao/umami#544]
Hello,
I just noticed that the IGNORE_IP variable does not support cider ranges.

I think it would be very handy to be able to configure network ranges using the cidr notation like 10.0.0.0/8 for example.

**Comment by mikecao** [comment]
Will probably need an npm package to resolve ip ranges and change the logic in `/api/collect`.

**Comment by gnarlex** [comment]
[NPM package `ipaddr.js`](https://www.npmjs.com/package/ipaddr.js?activeTab=readme) looks promising:

```javascript
const addr = ipaddr.parse('2001:db8:1234::1');
const range = ipaddr.parseCIDR('2001:db8::/32');

addr.match(range); // true
```
