### ISSUE TITLE
Invalid domain

### ISSUE THREAD

**Issue by FNGR2911** [mikecao/umami#547]
I'm not sure if it's since the update to v1.14 but I'm facing the issue that, when I try to add a new domain, it doesnt work anymore.

<img width="626" alt="Bildschirmfoto 2021-03-16 um 10 00 11" src="https://user-images.githubusercontent.com/6659625/111282726-9755a980-863e-11eb-9d4a-54527e3990d3.png">

Why is that? Without https:// and www it's working, but then it shows my own domain as a referrer.

Thanks for help!

**Comment by gnarlex** [comment]
Protocols are technically not part of the domain. In v1.14 we fixed the domain input to reflect this and reject protocols in the user input. Therefore `https://matti.dev` is invalid, but `matti.dev` is accepted. It's unusual though, that `www.matti.dev` was not accepted. I tried it myself and it worked (see attached screenshot). Could you double-check again?

![Screenshot 2021-03-16 at 12 37 13](https://user-images.githubusercontent.com/24435169/111303028-58325300-8654-11eb-802e-341a8f586ec5.png)

> but then it shows my own domain as a referrer

Is it possible that the referrer domain is a substring of the domain in the settings?

**Comment by FNGR2911** [comment]
Ah ok, I understand.  So, this doesn't work:

https://matti.dev
https://www.matti.dev

This work:
matti.dev
www.matti.dev

So, if my server would be configured to redirect everything to www.matti.dev I should put this into domain. If my server redirects every request to matti.dev without www prefix, I should enter just matti.dev. Right?

**Comment by gnarlex** [comment]
Correct 👌

**Comment by FNGR2911** [comment]
Thank you @gnarlex, now it's clear and working fine ;) I like your PR to put that info into a placeholder. Or, maybe it could be a small description below the input. Anyway, thanks!
