### ISSUE TITLE
The bar graph is a little bit confusing. 

### ISSUE THREAD

**Issue by lucky13820** [mikecao/umami#55]
In the bar chart, the unique visitors and the page views are stack on top of each other. So when both bar graphs shown, it makes it feels like the the page views are lot more than it is.

For example, I have 95 page views and 57 unique visitors. When both are shown, it feels like I have 152 page views.  
![9A98D2CA-B04C-4DC6-8A19-5800105DF4A2](https://user-images.githubusercontent.com/7293811/90970482-7c60f380-e4ba-11ea-8818-bef7671d4b95.jpeg)

**Comment by mikecao** [comment]
@lucky13820 Bars no longer stack in the latest update.
