### ISSUE TITLE
Incorrect metrics when filtering certain page paths

### ISSUE THREAD

**Issue by Sammy-T** [mikecao/umami#553]
I've noticed that selecting an index path without a trailing slash (e.g. `/some-page`) from the 'Pages' section, seems to always return 0 for all results even though the section shows views for that page:

![screen_1](https://user-images.githubusercontent.com/22360092/111577553-dee84c80-8788-11eb-8005-50d3942c770a.png)
![screen_2](https://user-images.githubusercontent.com/22360092/111577557-e0b21000-8788-11eb-82ea-f0195b5e3ff4.png)
![screen_3](https://user-images.githubusercontent.com/22360092/111577560-e3146a00-8788-11eb-86b1-2dad7d1806d1.png)

From what I've seen so far, it looks as though the api returns valid results for requests where the `url` parameter points to a file or to a path with a trailing slash (e.g. `/some-page.html`, `/`, `/some-page/`).

**Comment by mikecao** [comment]
Closing this. Will track in #606
