### ISSUE TITLE
Suggestion: Add an "All time" time filtering option to the dropdown.

### ISSUE THREAD

**Issue by NoLooseEnds** [mikecao/umami#554]
**Suggestion:**
Add an "All time" time filtering option to the dropdown. I know you can do that manual in the custom option, but still a nice and hopefully easy improvement.

<img width="325" alt="Screenshot 2021-03-18 at 10 42 37" src="https://user-images.githubusercontent.com/4103531/111605746-d4ed3a80-87d6-11eb-8a01-e9e2ab0b5b45.png">

Keep up the good work! :)

**Comment by ShubhamVerma1811** [comment]
Hi,
I would like to give issue a shot.
