### ISSUE TITLE
RFE: full configuration through .env or api endpoint

### ISSUE THREAD

**Issue by iFloris** [mikecao/umami#556]
Hi, 

It would be very helpful if we could pre-configure umami entirely through the docker-compose .env or alternatively through the api. Our usecase would be to either store the full config in git and rebuild when neccesary or to preconfigure umami so that it works out-of-the box.

This would include:
- admin password
- sites

It would also be efficient if we could then get the tracker code and the share url for the preconfigured websites through the api :)

**Comment by mikecao** [comment]
I think this should be possible after this PR #559 is merged.

**Comment by mikecao** [comment]
PR #559 is merged.
