### ISSUE TITLE
Enhancement: Prisma Migrate with database seeding

### ISSUE THREAD

**Issue by beornf** [mikecao/umami#559]
With Prisma Migrate reaching [general availability](https://www.prisma.io/blog/prisma-migrate-ga-b5eno5g08d0b) a `prisma migrate deploy && prisma db seed` workflow would help in making production schema updates easier addressing #527, #545 and #556.

I've written a PR with updated schemas, migrations and a seed file. After making a change to a schema in development you would run either:

`prisma migrate dev --name=change --schema=./prisma/mysql/schema.mysql.prisma`
`prisma migrate dev --name=change --schema=./prisma/postgresql/schema.postgresql.prisma`

You would see similar output:

```
The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210319130843_change/
    └─ migration.sql

Your database is now in sync with your schema.
```

These changes would be committed to source code and can be easily applied in production.

Pull a Docker image or repository in production and bring the schema up to date by running the commands:

```
prisma migrate deploy --schema=./prisma/mysql/schema.mysql.prisma
prisma db seed --schema=./prisma/mysql/schema.mysql.prisma --preview-feature
```

OR

```
prisma migrate deploy --schema=./prisma/postgresql/schema.postgresql.prisma
prisma db seed --schema=./prisma/postgresql/schema.postgresql.prisma --preview-feature
```

The seed file also supports a preconfigured password by reading the `ADMIN_PASSWORD` environment variable.

**Comment by mikecao** [comment]
This looks great. A few questions though,
1) Are the migration files necessary at this point? the DB schema hasn't changed yet. Though I could see it being useful for future updates.
2) Can we use this to initially populate the database so users won't have to run the sql file manually?

**Comment by beornf** [comment]
1. Migration files aren't strictly necessary unless you had to rename table columns in production with no risk of data loss.
2. I tested the commands below work to populate the schema. The caveat is you'd need to take a database snapshot when the schema changes if you run the commands again after the initial seed phase.

```
prisma db push --schema=./prisma/schema.mysql.prisma --preview-feature
prisma db push --schema=./prisma/schema.postgresql.prisma --preview-feature
```

Note the help output:

```
🙌  Push the state from your Prisma schema to your database
WARNING Prisma db push is currently in Preview (https://pris.ly/d/preview).
There may be bugs and it's not recommended to use it in production environments.
```
