### ISSUE TITLE
[Roadmap] Provide more chart options

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#56]
Provide more chart options:
- Line graph
- Side by side bar graphs
- Should be able to toggle chart display with quick buttons similar to dates

**Comment by axelekwall** [comment]
@mikecao Is this something you want help with? I have some experience with visualizations and would like to give it a shot!

**Comment by mikecao** [comment]
@axelekwall Sure you can try and tackle this. I think to start off the user should be able to toggle between line and bar charts.
