### ISSUE TITLE
Feature Request: A/B Testing

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#564]
One of the main reasons we use Analytics is to know how users use our website and make improvements. For landing pages, it's all about conversions. To effectively launch a campaign, many marketers prefer A/B Testing to track their conversion rate on each of their landing page. 

So, I would suggest Umami add this feature. It can be simple redirect for the start, then can be improved later. 

**Expected Phases**
- [ ] Phase 1: A/B Testing - Simple Page Redirection & Track conversion (umami event)
- [ ] Phase 2:  Advanced Experiments such as change heading, text, colors etc. 
- [ ] Phase 3: Smart Traffic Optimization - Giving more weightage to the most converting Variant

If you like this idea, please upvote. or reply below to discuss. 

~Surjith

**Comment by mikecao** [comment]
This is way beyond scope of the app. But I don't even know how this would work. Only you have control over the functionality of your website. The only part that interacts with your website is the tracking script and it can't do all of that.

**Comment by surjithctly** [comment]
Yes, Its possible. If you see Google Analytics, they provide an option. Also, you can check this site: https://splitbee.io/ where they are also providing this option. 

The logic for Phase 1 is while loading the page, redirect to x or y page based on the config. Since its a javascript plugin, it can be done. May be its too complex, we can just do the Phase 1 with redirection only? 

Let me know what you think.

**Comment by mikecao** [comment]
I'm sure it's possible, but again beyond scope of the app. You can already accomplish what you want with a simple script.

```javascript
window.location.href = Math.random() > 0.5 ? 'https://example.com/a' : 'https://example.com/b';
```

And umami will collect the stats as usual. Just compare the numbers.

**Comment by NoLooseEnds** [comment]
Maybe Umami could have a plugin system, so other people can make things like A/B testing – without bloating the original base.

**Comment by abrambailey** [comment]
> I'm sure it's possible, but again beyond scope of the app. You can already accomplish what you want with a simple script.
> 
> ```js
> window.location.href = Math.random() > 0.5 ? 'https://example.com/a' : 'https://example.com/b';
> ```
> 
> And umami will collect the stats as usual. Just compare the numbers.

Not sure you understand how AB testing works. You typically have the same URL for both states. However, I could see just creating a different set of events and funnel for A and B.
