### ISSUE TITLE
Unable to create multiple users for single website/URL

### ISSUE THREAD

**Issue by pramodb05** [mikecao/umami#566]
Dear Team,

I tried to create few user accounts for user team to share the dashboard view (specific items) of a website.

but it seems not support multiple user for a single website dashboard.

If someone has already created, help will be appreciated.

**Comment by mikecao** [comment]
That's right, each user account owns the website. If you want to share websites between users you have to use the Share URL feature.

**Comment by magicgg91** [comment]
Hello, 
Just found this issue and answer.
Cool that Share URL exists, but how to proceed if we want to restric the access to this Share URL ?

**Comment by andreaskviby** [comment]
> Hello,
> Just found this issue and answer.
> Cool that Share URL exists, but how to proceed if we want to restric the access to this Share URL ?

I also need to know this, I don't want the stats to be public just available for one more user.

**Comment by pramodb05** [comment]
So I think this issue still not closed and @mikecao  if you and team can help us to get the user role based access for each dashboard.
It'll be a great feature.
