### ISSUE TITLE
Recommended Servers sizing

### ISSUE THREAD

**Issue by AlaxBabaxXD** [mikecao/umami#568]
Dear Team,
We want to use your service, you have server requirements, if yes, please specify which ones.

**Comment by gnarlex** [comment]
It really depends on your traffic and the amount of tracked events.

Are you looking for minimal requirements?

I have it running on a 1 vCPU, 1GiB RAM vServer and didn't run into any issues yet with aprox. 20 visitors a day and no custom events. And I think it definitely could serve more than that.

However, if you have an app used by 1000+ users per day firing a lot of custom events, you are going to need more than that in terms of CPU, RAM, Bandwidth and Storage for the database.
