### ISSUE TITLE
[Roadmap] Real-time dashboard

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#57]
Provide a real-time dashboard:
- Polling for data
- Show visitors as they come in
- Show active urls being visited
- Show real-time country highlights

**Comment by vitobotta** [comment]
This is awesome, looking forward to it! :)

**Comment by mikecao** [comment]
Sneak peek of WIP
![image](https://user-images.githubusercontent.com/477975/95660924-e58add80-0adf-11eb-951a-c377f340c04f.png)

**Comment by vitobotta** [comment]
@mikecao Looks great! When do you think this will be in a new docker image? No rush eh :D
