### ISSUE TITLE
Option to hide Chart on Dashboard

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#577]
I'm currently tracking five websites using Umami. So, from the dashboard it's really hard to get track of these websites because of the long scroll. So I prefer an option to hide the chart in the dashboard so that I can see all of my sites without scrolling. 

I can always see the chart on the details page. It would be great if you could provide this option. 

**Expected result:**
![image](https://user-images.githubusercontent.com/1884712/112606093-3879f800-8dd5-11eb-8229-2678e2aab522.png)

**Comment by mikecao** [comment]
Should be possible.
