### ISSUE TITLE
Build Issue With 1.16.0 on FreeBSD

### ISSUE THREAD

**Issue by wgmyers** [mikecao/umami#583]
Umami 1.16.0 did not build off the bat (FreeBSD 12.1-RELEASE-p6) for me.

I got a lot of error messages from prisma saying 

```
error: Native types can only be used if the corresponding feature flag is enabled. Please add this field in your generator block: `previewFeatures = ["nativeTypes"]`
```

Adding the `previewFeatures = ["nativeTypes"]` line directly to `prisma/schema.prisma` failed, because that is generated from one of `prisma/schema.mysql.prisma` or `prisma/schema.postgresql.prisma`.

Adding the previewFeatures line to the mysql flavour of the file worked fine, and the build then worked fine.

Not sure what the long term fix is here. On initial install, several versions of Umami ago, I ran into an issue where I had to install prisma myself by hand as there was (is?) no automatic way of doing so on FreeBSD. After that, though, everything was fine through to and including 1.15.0.

Do I need to manually update prisma (I remember it being a faff), or should I submit a pull request adding the previewFeatures line to the mysql schema? Or do I need to make a note to myself to add that line manually each time there's an update until such time as I update prisma.

**Comment by mikecao** [comment]
Prisma was updated to the latest version 2.19 in 1.16. Native types should have been stable since prisma 2.17. Are you updating all your dependencies on every update?

**Comment by wgmyers** [comment]
Thanks for this: very clear answer.

No, I have not been updating prisma, which is the only external dependency - it's still running the same version as when first installed (1.11 or 1.12 or so); yes I clearly need to update prisma more regularly from now on, starting tomorrow (is rather late here rn).
