### ISSUE TITLE
Dashboard Optimization

### ISSUE THREAD

**Issue by paperrgb** [mikecao/umami#592]
My current RAM usage is at about 80% of 1GB - it looks like MySQL alone takes up about 20% (will probably increase to 2GB soon).

CPU usage jumps up quite a bit each time I visit the dashboard, could this not be loaded all at once?

I'm currently tracking about 50 subdomains and it seems to work fine. 

When I'm on the dashboard however, it makes several API calls per website being tracked. Does this establish a new MySQL connection for each request?

I have about 500 subdomains that I want to track, would I run into `max_connection` issues just from visiting the dashboard?

**Comment by mikecao** [comment]
It depends on how you are hosting the app. If in a serverless environment (like Vercel) every api call is making a new database connection. If you're hosting it normally, it will use the connection pool. However, it still needs to make lots of individual calls. If are tracking 50 domains, that could be a performance issue.

**Comment by paperrgb** [comment]
Thanks, since individual API calls aren't a problem, could the dashboard maybe only display 5 at a time or something? Then perhaps there could be a "Load More" button to load the rest.

It normally works fine, but CPU usage jumps up just from visiting the dashboard

**Comment by mikecao** [comment]
Your use case is pretty uncommon. A majority of people only track a few sites. I think we can do progressive loading so it only loads in batches, or do the the load more thing.

**Comment by paperrgb** [comment]
Sounds great, I use this for each of our clients as it is a lot easier to keep everything in one place

**Comment by visini** [comment]
I have a similar use case with more than a few domains. Besides optimizing the dashboard page to include progressive loading, it could also be worthwhile to explore slimming down the dashboard entirely (as an optional, non-default option) which will simply display a list of links to open the site-specific dashboards, and not load any data beyond the list of websites.

**Comment by mikecao** [comment]
@visini You can already do this. Go to Settings -> Websites. From there you can click on the name of the website to get to the details.

**Comment by visini** [comment]
> @visini You can already do this. Go to Settings -> Websites. From there you can click on the name of the website to get to the details.

I‘ve modified the source code for the dashboard to show the same list of websites that is shown in website settings. Cheers!

**Comment by GurjinderSingh** [comment]
@mikecao 
have you looked into https://clickhouse.tech/ database ?

https://clickhouse.tech/docs/en/introduction/adopters/


I looks very promising and very big tech using it too

**Comment by mdestafadilah** [comment]
> > @visini You can already do this. Go to Settings -> Websites. From there you can click on the name of the website to get to the details.
> 
> I‘ve modified the source code for the dashboard to show the same list of websites that is shown in website settings. Cheers!

may you can make PR with your modified code, we can review ..
