### ISSUE TITLE
ARM architecture support for images

### ISSUE THREAD

**Issue by denysdovhan** [mikecao/umami#593]
I'm trying to host umami on my personal Raspberry Pi.

When I try to run an image, I get this error:

```sh
$ docker run ghcr.io/mikecao/umami:mysql-latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

AFAIK, all of the umami's dependencies (node, yarn, etc) can be run on ARM. Is it possible to add arm support to your images?

**Comment by denysdovhan** [comment]
I went googling and found these links, that might be useful:

* https://ownyourbits.com/2018/06/27/running-and-building-arm-docker-containers-in-x86/
* https://github.com/docker/buildx#building-multi-platform-images

Here's an example of how `zigbee2mqtt` does that in their GitHub workflow: https://github.com/Koenkk/zigbee2mqtt/blob/master/.github/workflows/ci.yml#L58-L68

Here's how AdGuardHome does that:

* A GitHub workflow https://github.com/AdguardTeam/AdGuardHome/blob/master/.github/workflows/build.yml#L106-L111
* A script for building https://github.com/AdguardTeam/AdGuardHome/blob/master/scripts/make/build-docker.sh

There's even action for that: https://github.com/docker/setup-buildx-action

This must be relatively easy to do. Let me know how can I help.

**Comment by mikecao** [comment]
I'm not sure there is enough demand for ARM to justify building the extra images. But we can support it via a script if it's easy to do. Something like `yarn build-arm`.

**Comment by denysdovhan** [comment]
@mikecao that might be a good start. But why are you against building arm support to existing images? As I understand this requires only slight changes in the build `main.yml` workflow.

Would you consider accepting a PR if I will make the required changes?

**Comment by mikecao** [comment]
It's just more to support and fix if something goes wrong. I don't want to put a build out there that I can't test. With a script whoever wants to use it can just run it and we can make fixes without putting out bad builds.

Also see these threads, #272 and #531

**Comment by denysdovhan** [comment]
I've read the thread you've mentioned and must agree this is harder than it seems (as always 😀). `yarn build-arm` would be a good start.
