### ISSUE TITLE
Excluding path / segments from tracking

### ISSUE THREAD

**Issue by nhaberl** [mikecao/umami#594]
It would be great to have the chance to also exclude paths / segments from tracking not only domains.
Reason for this is that someone maybe integrates a member area within the same domain and it would be great to seperate it from public tracking.

**Comment by mikecao** [comment]
You can already do this, just disable the tracker on the pages you don't want to track.

**Comment by cupcakearmy** [comment]
@mikecao it would be great to have some kind of configuration option. Would make integration much easier.
Generally tracking is more of a blacklist than a whitelist, which means more work if you just want to exclude a few paths.
