### ISSUE TITLE
'prisma' 2.18.0 vs 'prisma/cli' 2.17.0 in package.json when attempting umami upgrade

### ISSUE THREAD

**Issue by craig-constantine** [mikecao/umami#595]
Currently have Umami 1.14.0 installed and I wanted to 'git pull' myself up to the latest 1.16.0…

```
17:25UTC:root@ns:~/umami# git pull
Updating 405766d..ce35a2d
error: Your local changes to the following files would be overwritten by merge:
	package.json
Please commit your changes or stash them before you merge.
Aborting
```

Wait, what did I do to my local...

```
17:25UTC:root@ns:~/umami# git diff
diff --git a/package.json b/package.json
index 485cc22..da4bd9c 100644
--- a/package.json
+++ b/package.json
@@ -98,7 +98,6 @@
   },
   "devDependencies": {
     "@formatjs/cli": "^2.13.16",
-    "@prisma/cli": "2.17.0",
     "@rollup/plugin-buble": "^0.21.3",
     "@rollup/plugin-node-resolve": "^11.1.1",
     "@rollup/plugin-replace": "^2.3.4",
@@ -121,6 +120,7 @@
     "postcss-preset-env": "^6.7.0",
     "prettier": "^2.2.1",
     "prettier-eslint": "^12.0.0",
+    "prisma": "^2.18.0",
     "rollup": "^2.38.3",
     "rollup-plugin-hashbang": "^2.2.2",
     "rollup-plugin-terser": "^7.0.2",
```

Oh, right! A while back I did... something… to upgrade Prisma. Was that an NPM update I did? sheesh I cannot recall.

Anyway, is it safe to just revert my pacakge.json?  (I know how to do that.)

I'm concerned that if the Umami 1.16.0's package.json says it depends on **prisma/cli** 2.17.0 , while I now have **prisma** 2.18 . . .

**Comment by craig-constantine** [comment]
Tangent: I'm a github newb... am I supposed to tag this as Troubleshooting, eg,  https://github.com/mikecao/umami/issues/583  is neatly tagged as such, but I don't see how to do it... cluebat please :)

**Comment by mikecao** [comment]
Just delete your local changes and re-run install. It should fix everything up. And only I can tag.
