### ISSUE TITLE
Provide a Docker image

### ISSUE THREAD

**Issue by Kovah** [mikecao/umami#6]
A Docker image can be used to setup the app more easily and provides less hassles with the installation. It would be great to provide an image that includes the pre-built application.

Examples: [Plausible](https://github.com/plausible/analytics/blob/master/Dockerfile) [Ackee](https://github.com/electerious/Ackee/blob/master/Dockerfile)

**Comment by mikecao** [comment]
Definitely plan on doing so.

**Comment by lucky13820** [comment]
Yeah, a docker image or docker compose support would be perfect.

**Comment by initbar** [comment]
Seconded. +1

**Comment by TonyLuo** [comment]
+1

**Comment by mikecao** [comment]
I should mention that I am not very familiar with Docker, so a PR would be appreciated.

**Comment by jkyngan** [comment]
+1
