### ISSUE TITLE
Internal server error when logging into dashboard

### ISSUE THREAD

**Issue by pfist** [mikecao/umami#603]
I followed your guide to setup up Umami on a DigitalOcean droplet with MySQL. Everything is up and running, including a proxy to my subdomain, but when I visit the site and try logging in with the default credentials (admin and umami), an `Internal Server Error`  message appears below the password field.

<img width="414" alt="firefox_H3lINWWlaX" src="https://user-images.githubusercontent.com/1567037/114103385-e7aada80-987d-11eb-8fb9-c3f7a5884c32.png">

**Comment by mikecao** [comment]
You need to post what the error is. Try checking the console in the browser developer tools.

**Comment by pfist** [comment]
Here are the errors that show up in the console. The two 404s happen on page load; the 500 happens when I try to login.

<img width="477" alt="explorer_8chefs10yY" src="https://user-images.githubusercontent.com/1567037/114121057-8f3a0400-98a2-11eb-9e39-4dee86f483d4.png">

**Comment by mikecao** [comment]
You need to expand the error to see the actual message. Or check your network tab.

**Comment by pfist** [comment]
The stack trace is a very long list of oddly-named functions coming from files in `/_next/static/chunks/` ending with an anonymous function in `https://u.polymoon.net/_next/static/chunks/commons.795e5953e5cae5c52f22.js`. I have no experience with Next.js so I'm not sure what to make of it.

Here are the headers:

<img width="413" alt="firefox_0zSSgaO0gz" src="https://user-images.githubusercontent.com/1567037/114130814-35433980-98b6-11eb-9594-1433ae74c8b8.png">

**Comment by mikecao** [comment]
There has to be some error message. All these screens show is that something went wrong.

**Comment by pfist** [comment]
I'm not sure where else to look. I don't see any error messages besides what I've shown from the dev tools. Does umami have logs I can check?

**Comment by mikecao** [comment]
You can try running in dev mode, `npm run dev` or `yarn dev`. All errors will be printed to the console.

**Comment by pfist** [comment]
Perfect, I'll try that and let you know what I find.

**Comment by pfist** [comment]
Here's the error that shows up in the console when I try to login. Is this a problem with the DATABASE_URL in my .env perhaps?

<img width="857" alt="WindowsTerminal_5dpudXVIjc" src="https://user-images.githubusercontent.com/1567037/114240275-1d15fd80-993c-11eb-97e3-3f975cf46a24.png">

**Comment by pfist** [comment]
I'm in! I had to set my MySQL user's password to one without special characters. Prisma couldn't parse `DATABASE_URL` with special characters in the password. Thanks again for the making this app. I'm really exciting about owning my analytics and better respecting the privacy of my site visitors. 😄
