### ISSUE TITLE
Page filter doesn't work

### ISSUE THREAD

**Issue by magicgg91** [mikecao/umami#606]
Hello,
If I click on 1 page, it adds a filter for the graph, but there is no data displayed anymore, as it should have the number of pageviews.

**Comment by mikecao** [comment]
You need to post an example. It works fine for me.

**Comment by magicgg91** [comment]
Please find graph for today's visits on a website I track with Umami :

![umami_issue1](https://user-images.githubusercontent.com/16479933/114298677-e5cc5b80-9ab7-11eb-9159-b57803caab4f.PNG)

If I click on the most (or second most) viewed page, graph shows 0 pageviews/visitors

![umami_issue2](https://user-images.githubusercontent.com/16479933/114298680-e9f87900-9ab7-11eb-9e4d-43206e96fcab.PNG)
![umami_issue3](https://user-images.githubusercontent.com/16479933/114298686-ec5ad300-9ab7-11eb-8168-75008de14e5f.PNG)

It works only for root page, there is 29 pageviews shown in graph, which is ok for number of pageviews displayed in bottom

![umami_issue4](https://user-images.githubusercontent.com/16479933/114298689-ee249680-9ab7-11eb-9ee2-7a5fea6bfae3.PNG)

Let me know if you need more informations.
Thanks

**Comment by Sammy-T** [comment]
This looks to be a similar issue to mine #553. As far as I can tell, this doesn't seem to affect everyone. But I haven't figured out why that is.

**Comment by magicgg91** [comment]
Thanks for your feedback.
I've found also something in this way, and it's more about how datas are stored/used.

In database, urls are stored with / at the end as there is no extension to webpages on my site.
But on Umami dashboard, final / is not displayed, and search of related informations are not found (search must be strict I think)

I've tried to update 1 line in DB removing final / and it worked, I can see 1 view in graph.

![issue_umami5](https://user-images.githubusercontent.com/16479933/114302645-3ba9ff00-9aca-11eb-97c9-47079da9c761.PNG)
![issue_umami6](https://user-images.githubusercontent.com/16479933/114302646-3d73c280-9aca-11eb-90f6-08a3b7b1eab5.PNG)

**Comment by Wonderfall** [comment]
I can reproduce the issue on my blog, and in fact it would affect any version of Ghost CMS. I found that just adding manually the trailing slash in the request URL (like `https://umami.domain.tld/website/1/MyBlog?url=%2Fsome-article` + `/`) makes the page filter working again.

I'm not familiar with the codebase but after a quick check it seems to me a change in [filter.js](https://github.com/mikecao/umami/blob/master/lib/filters.js) which references [removeTrailingSlash](https://github.com/mikecao/umami/blob/c5d23867f57ebf769cb6d0209fbb7bdab2b32f4a/lib/url.js#L1) would solve this issue. Although I don't want to break anything so I'm just guessing right now.

(Thanks for doing Umami btw, it's a very clean and bloat-free tool.)

**Comment by Kdecherf** [comment]
This issue can be closed as the fix was released in v1.17.0.

**Comment by magicgg91** [comment]
I confirm, it's resolved.
Thanks again for your work.
