### ISSUE TITLE
Strange white rectangle on mobile menu

### ISSUE THREAD

**Issue by tairosonloa** [mikecao/umami#629]
On mobile version there is a strange white rectangle over the unami dashboard menu button.

It happens in both light and dark theme. Android 10 and Google Chrome.

![IMG_20210416_013249.jpg](https://user-images.githubusercontent.com/14878189/114950613-bb7df380-9e53-11eb-8e54-145a306f4725.jpg)

**Comment by Sammy-T** [comment]
I was having the same issue. Currently there's a fix for it on the dev branch #591 but it hasn't been included in the master branch just yet.

**Comment by mikecao** [comment]
Fixed in #591
