### ISSUE TITLE
Feature request: wildcard (*) support for domain field

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#632]
Feature request for wildcard support in the domain field of a website.

Following example:
Say I'd want to collectively track multiple sites across multiple regions. Namely
- `console-eu.example.com`
- `console-us.example.com`
- `console-cn.example.com`
- …

In order to correctly filter referrers it would be nice to have to specify a wildcard character in the domain field, like this:
- `console-*.example.com`

Rough implementation proposal:
- Replace domain input validation regexp to allow asterisk symbol (*)
- When filtering referrerral links, use regexp matching instead of `.contains(…)`
- Mapping domain value to regexp:
 - `.` --> `\.`
 - `*` --> `[a-z0-9]*`

**Comment by etc-tiago** [comment]
Any update to this issue?

**Comment by mikecao** [comment]
Added a new subdomain filter that should work without wildcards.
