### ISSUE TITLE
Is it possible to deploy on Cloudflare Pages?

### ISSUE THREAD

**Issue by neelygenet** [mikecao/umami#633]
I am trying to deploy it on the new Cloudflare Pages service, which is pretty good when comparing with Vercel and Heroku since it is completely free. However, I am getting in trouble when trying to deploy it. Could someone help me?

I am trying to:
Build command: `npm run build`
Output directory: `/public`

I also have defined the environment variables `DATABASE_URL` and `HASH_SALT`.

However, although Cloudflare says the deployment was successful, the deployed page is completely blank, without any file and returning 404. Does anyone have an idea of how to deploy it correctly? I am quite sure that my commands are correct, but I think it can be a Cloudflare Pages problem side.

**Comment by Form1ca** [comment]
deploy finished without errors?
can you public deploy log from Cloudflare Pages

**Comment by surjithctly** [comment]
I guess its because of the /api routes. Vercel does it automatically for us. Check docs on how to make it work with other providers.

**Comment by neelygenet** [comment]
Yes, that's it. There is no support for Cloudflare Pages for now because of the API routes.

**Comment by matthewjewell** [comment]
API routes shouldn't be a problem now, they get identified as dynamic in the build process. However, CF Pages has a hard limit of 25mb per asset, GeoLite2-City.mmdb is almost twice as large so deployment fails at the last minute.
