### ISSUE TITLE
Feature request: Filtering views based on location, referrers etc..

### ISSUE THREAD

**Issue by AbstractGeek** [mikecao/umami#636]
It would be nice to also have filters based on location and referrers, in addition to the page based filters. For example, it might be nice to look at which pages interest people from a particular referrer and what portion of the views account from this referrer. It might also be nice to have a negation filter, i.e everything except this referrer or location. 

Thanks for developing umami! It is very clean and easy to use!

**Comment by mikecao** [comment]
covered by #533
