### ISSUE TITLE
how to get session id from the tracker code

### ISSUE THREAD

**Issue by jkyngan** [mikecao/umami#64]
Hi,

how can i get the session id from the tracker code?

**Comment by mikecao** [comment]
You can't, the session is only processed on the server side.

**Comment by SoftCreatR** [comment]
For privacy reasons, you should not try to link a session to a specific user.

**Comment by mikecao** [comment]
Closing as answered.

**Comment by erdalkaraca** [comment]
Hi, is the session_id returned by umami.identify() in its fetch response guaranteed to be returned in future versions?
It is not used, but it is possible to intercept/hack the request and grab it for internal use.
