### ISSUE TITLE
Access-Control-Allow-Origin header not being sent by the api?

### ISSUE THREAD

**Issue by Fawesum** [mikecao/umami#648]
I'm trying to get the API to work so I can show the live counter in my blog admin panel. 
I have umami set up on a subdomain (and the api works brilliantly on a test page there), so I got a cors error at first, but even after setting up apache so that the `Access-Control-Allow-Origin = "*"` header is (supposed to be) sent I'm still getting the error.

`Access to XMLHttpRequest at 'https://subdomain.mysite.com/api/website/1/stats?start_at=1620165600000&end_at=1620252000000' from origin 'https://www.mysite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

All pages on the subdomain like `https://subdomain.mysite.com/` and `https://subdomain.mysite.com/page` is now showing the header correctly in chrome dev tools, but the umami dashboard is not, even though it's on `https://subdomain.mysite.com/umami`
I've tried setting the header options in both .htaccess and on the apache settings for the subdomain.

Any ideas?

**Comment by mikecao** [comment]
It should be sent by the api. There is specific CORS middleware that enables it.

**Comment by Fawesum** [comment]
Well it's not showing up in the header response on either the API call or on the umami dashboard, so I don't know?
I'm getting the data with an Ajax call, is there any parameters I should send with it?

**Comment by Fawesum** [comment]
This is the call I'm making:

```
$.ajax({
    url: "https://subdomain.mysite.com/umami/api/website/1/active",
    type: "GET",
    headers: {
              "cookie": "umami.auth=MYTOKEN"
             },
    success: function( data ) {
             console.log( data[0].x ); //live users
             }
});
```

**Comment by Fawesum** [comment]
Any ideas here?

**Comment by mannp** [comment]
Hi @Fawesum did you get this sorted, as I am struggling to get unami working you to this same error...

**Comment by Fawesum** [comment]
Hey @mannp. Unfortunately not...

**Comment by nh2** [comment]
I observe that it is sent by the API, e.g. in the response headers of `/collect`.

But it is not sent in the response headers for the tracker script, that is, `umami.js`.

This results in CORS preflight requests to API endpoints like `/collect`.

---

If I add the header in nginx using:

```
add_header Access-Control-Allow-Origin *;
```

then the header is set twice for `/collect`, resulting in a `CORS errror` `Cross-Origin Resource Sharing error: PreflightMultipleAllowOriginValues`.

**Comment by scenery** [comment]
After several nights of hard work, finally solved this problem by editing nginx config:

```
server {
    ...
    add_header Access-Control-Allow-Origin '*';
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    if ($request_method = 'OPTIONS') {
        return 204;
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_hide_header 'Access-Control-Allow-Origin';
    }
}
```

Simply add a line ```proxy_hide_header 'Access-Control-Allow-Origin';``` 

Still don't the reason, but it just works.

**Comment by codebox** [comment]
> After several nights of hard work, finally solved this problem by editing nginx config:
> 
> ```
> server {
>     ...
>     add_header Access-Control-Allow-Origin '*';
>     add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
>     add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
>     if ($request_method = 'OPTIONS') {
>         return 204;
>     }
> 
>     location / {
>         proxy_pass http://localhost:3000;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_hide_header 'Access-Control-Allow-Origin';
>     }
> }
> ```
> 
> Simply add a line `proxy_hide_header 'Access-Control-Allow-Origin';`
> 
> Still don't the reason, but it just works.

thanks, this fixed it for me as well

**Comment by frog42** [comment]
Great thread but I ran across an error if my Access-Control-Allow-Headers didn't also include X-Umami-Cache.

So the full list should be: 'DNT,X-Umami-Cache,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'
