### ISSUE TITLE
[DB] Potential Bug: sending NULL via umami.trackView(String, NULL)

### ISSUE THREAD

**Issue by foxytocin** [mikecao/umami#649]
It is possible to accidentally write NULL to the database. Did so accidentally for [referrer] value.

umami.trackView(url, **[referrer]**)

```
Usage:
umami.trackView('/home', NULL);
```
**When displaying the details page with the referrer statistics in the browser, this leads to the following error**
Browser: 'An unexpected error has occurred.'
Console:
<img src="https://user-images.githubusercontent.com/18313993/117156051-98dd5b80-adbd-11eb-9380-ba20c08b4479.jpg" width="700">

Fantastic project, best regards

**Comment by mikecao** [comment]
That's def a bug, we should guard against that.

**Comment by foxytocin** [comment]
Made a PR to fix the issue by checking also against **ref !== null** so that the illegal access of property _startsWith_ doesn't happend. This doesn't guard against entering _null_ to the DB.

<img src="https://user-images.githubusercontent.com/18313993/117265173-40a56880-ae54-11eb-98aa-c4ca95edbcb1.jpg" width="700">
