### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ArshZilpe** [mikecao/umami#656]
https://umami.is/ is down. Is this temporary? I would like to look at the docs haha.

**Comment by foxytocin** [comment]
Yep, I've already sent Mike an email about it. What do you want to know? Maybe we can answer it here quickly as long as the website is not available.

**Comment by ArshZilpe** [comment]
Great! It's nothing urgent haha. I was just interested in looking at the deployment options. I can wait till the website is back up. Thanks!
