### ISSUE TITLE
Metrics & Pageviews take very long

### ISSUE THREAD

**Issue by SoftCreatR** [mikecao/umami#66]
I'm analyzing a relatively large website since Aug 21 and it already takes ages until the stats are loaded.

![image](https://user-images.githubusercontent.com/81188/91100722-faadc900-e665-11ea-96fd-e6b1b7e08ec6.png)

The metrics took 15.91s and the pageviews 19.68s to load. So after a week, it will take more than 30 seconds, which is way too long.

**Comment by mikecao** [comment]
That sounds really long. Those queries should be using indexed columns so it shouldn't take that long. What kind of server is it running on?

**Comment by SoftCreatR** [comment]
Umami is hosted on a small Hetzner Cloud machine (CX 21). I'm using MySQL as database.

**Comment by mikecao** [comment]
I'm running on a much smaller server (although fewer users) and I haven't had queries that long. Check your database and make sure the indexes were created.

**Comment by SoftCreatR** [comment]
Indexes are there.

**Comment by mikecao** [comment]
You can try doing an `EXPLAIN` on the query to see what's going on. This is the query for metrics for MySQL:

```sql
select sum(t.c) as "pageviews",
  count(distinct t.session_id) as "uniques",
  sum(case when t.c = 1 then 1 else 0 end) as "bounces",
  sum(t.time) as "totaltime"
from (
  select session_id,
  date_trunc('hour', created_at),
  count(*) c,
  floor(unix_timestamp(max(created_at)) - unix_timestamp(min(created_at))) as "time"
from pageview
where website_id=?
  and created_at between ? and ?
  group by 1, 2
) t
```

Replace the `?` with parameters.

**Comment by SoftCreatR** [comment]
Running the query itself, it takes 7,125s:

```sql
select sum(t.c) as "pageviews",
  count(distinct t.session_id) as "uniques",
  sum(case when t.c = 1 then 1 else 0 end) as "bounces",
  sum(t.time) as "totaltime"
from (
  select session_id,
  date_trunc('hour', created_at),
  count(*) c,
  floor(unix_timestamp(max(created_at)) - unix_timestamp(min(created_at))) as "time"
from pageview
where website_id=2
  and created_at between from_unixtime(1597788000) and from_unixtime(1598392799)
  group by 1, 2
) t
```

Explained:

|id|select_type|table|type|possible_keys|key|key_len|ref|rows|Extra|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|1|PRIMARY|<derived2>|ALL|||||242784||
|2|DERIVED|pageview|ref|pageview_created_at_idx,pageview_website_id_idx|pageview_website_id_idx|4|const|242784|Using where; Using temporary; Using filesort|

> Also, what is the date range on that query?

7 days is set in the UI. However, the first entry was created on 2020-08-20 03:14:25.

**Comment by mikecao** [comment]
Try creating a new composite index and see if that helps:

```sql
create index pageview_website_id_created_at_idx on pageview(website_id, created_at);
```

**Comment by SoftCreatR** [comment]
Still no change.

metrics: 10.96s
pageviews: 19.03s

**Comment by mikecao** [comment]
@SoftCreatR do you think you can send me a mysql dump of your data? I only have postgresql data. I ran a test with 500K records and it returned in 30ms. I want to see if there is something mysql specific.

**Comment by mikecao** [comment]
Ok, I mocked up a database in MySQL with a million records. Even this simple query it takes 5 seconds:

```sql
select session_id,
count(*) c
from pageview
where website_id=1
group by 1
```

The same query in Postgres takes 13ms. It seems MySQL has issues with `group by` and `count` in the query. May need someone with more MySQL experience to chime in here.

**Comment by SoftCreatR** [comment]
I guess, the problem here is the numeric grouping. I'm not sure, but it could be, that indexes don't have that much effect in this case.

**Comment by mikecao** [comment]
@SoftCreatR try adding this index:

```sql
create index pageview_website_id_session_id_created_at_idx on pageview(website_id, session_id, created_at);
```

**Comment by SoftCreatR** [comment]
No change. Ill send you a dump of my db. Maybe that helps.

**Comment by mikecao** [comment]
@SoftCreatR Getting closer to a solution. I've got the main queries down to less than 2 seconds.

**Comment by mikecao** [comment]
@SoftCreatR try pulling the lastest build. I made some improvements. And make sure you create this index:

```sql
create index pageview_website_id_session_id_created_at_idx on pageview(website_id, session_id, created_at);
```

**Comment by SoftCreatR** [comment]
Created the index, pulled the latest commits, rebuilt it. Result:

![image](https://user-images.githubusercontent.com/81188/91606001-ad856c00-e971-11ea-9e36-0e9604f511f3.png)

**Comment by SoftCreatR** [comment]
It's even worse: It consumes all available RAM and CPU so it's completely useless for me atm.

**Comment by SoftCreatR** [comment]
So, after some analysis, 3 queries are fired:

```sql
select sum(t.c) as "pageviews",
    count(distinct t.session_id) as "uniques",
    sum(case when t.c = 1 then 1 else 0 end) as "bounces",
    sum(t.time) as "totaltime"
  from (
     select session_id,
       DATE_FORMAT(created_at, '%Y-%m-%d %H:00:00'),
       count(*) c,
       floor(unix_timestamp(max(created_at)) - unix_timestamp(min(created_at))) as "time"
     from pageview
     where website_id=2
     and created_at between TIMESTAMP'2020-08-21 22:00:00' and TIMESTAMP'2020-08-28 21:59:59.999000'
     group by 1, 2
 ) t
```

Execution time (Avg): 10.375s

```sql
select DATE_FORMAT(convert_tz(created_at,'+00:00','+02:00'), '%Y-%m-%d') t,
    count(distinct session_id) y
  from pageview
  where website_id=2
  and created_at between TIMESTAMP'2020-08-21 22:00:00' and TIMESTAMP'2020-08-28 21:59:59.999000'
  group by 1
  order by 1
```

Execution time (Avg): 2.750s

```sql
select distinct url x, count(*) y
  from pageview
  where website_id=2
  and created_at between TIMESTAMP'2020-08-21 22:00:00' and TIMESTAMP'2020-08-28 21:59:59.999000'
  group by 1
  order by 2 desc
```

Execution time (Avg): 18.004s

**Comment by mikecao** [comment]
@SoftCreatR The data dump was very useful. I was able to fix a couple bugs from it. For example the domain field for the website should just be the domain, not including http. So thanks for that.

Using the new dump and  I made a few small improvements. Here are the numbers from the details page:

![image](https://user-images.githubusercontent.com/477975/91628661-c6445080-e976-11ea-9a5e-1cbd846e0193.png)

A little higher than I'd like but not terrible. But I think I understand what is going on with your server. You are running it on a live site while I am just using a local MySQL instance with no incoming traffic. With the amount of hits you are getting, it's probably taking up all your resources for these queries. You might need a much stronger server or setup a read replica.

Originally I had a cookie using localStorage that would cache some data save a few queries, but I removed it due to GDPR concerns. It would probably help a lot in your case. I can add it back and make it configurable. What do you think? Since you're EU based it's probably more of a concern for you.
