### ISSUE TITLE
Aborted Core Dump - node_http_parser

### ISSUE THREAD

**Issue by Retro64XYZ** [mikecao/umami#666]
`ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /var/www/node/umami/.env
info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
node[18880]: ../src/node_http_parser.cc:567:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
 1: 0xb12b40 node::Abort() [node]
 2: 0xb12bbe  [node]
 3: 0xb2a2c2  [node]
 4: 0xd6014b  [node]
 5: 0xd615ec  [node]
 6: 0xd61c66 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x160c699  [node]
Aborted (core dumped)
`

I am receiving the above error. I am on ubuntu 20.04 LTS and -

`ubuntu@ip-172-31-19-129:/var/www/node/umami$ npm -v
7.11.2
`

Any thoughts on how to fix this?

**Comment by renatkalimulin** [comment]
How did you solve this?
