### ISSUE TITLE
Google tagging umami instances as deceptive

### ISSUE THREAD

**Issue by arunbabucode** [mikecao/umami#672]
Hi,

This is not a bug report, I am using umami js on one of my apps to track user engagement. This was highly effective since most of the users I am targeting were developers or technical advanced users with adblockers. And hence most of the SaaS analytics were getting blocked.

Anyway, my self hosted umami was highly effective where other apps failed. But, today, I got a warning message when I tried to log into my umami instance. Google says "Deceptive site ahead" with the custom red background. I quickly checked my app and it was showing the same message since umami was making requests from that website.

I would like to know if this is a common issue others faced or trying to understand why Google is marking my instance as dangerous.

![image](https://user-images.githubusercontent.com/7436679/118695283-4f552d80-b80d-11eb-9529-4e913ca7a6a9.png)

**Comment by mikecao** [comment]
Try removing umami and see if you are still getting the warning. I doubt umami itself is flagged because I use it on all my websites, including https://umami.is

**Comment by arunbabucode** [comment]
I removed the tracking link from the main website, and there was a link on the above warning to report it as a false positive. Did that and within almost an hour, google removed the "dangerous" label from the link. Reactivated the tracking link on the main site and it works now. Closing the issue, but have no clue why this happned.

**Comment by zix99** [comment]
Sorry to bump, but I'm getting the same thing.  I was able to remove it by un-deploying the site, and google quickly re-added the deceptive site warning once I re-added.  I'm not sure how much I can do to fix this besides stopping to use Umami.  I do wonder if they're looking for something specific with subdomains or how the script is accessing data.  Posting here in case others run into this.
