### ISSUE TITLE
Dashboard title {x} current {x, plural, one {visitor} other {visitors}}

### ISSUE THREAD

**Issue by AlexanderPotapov** [mikecao/umami#674]
Hello

I use macOS Sierra and 12.1.2 Safari that produced "{x} current {x, plural, one {visitor} other {visitors}}" on the dashboard. Screenshot attached.

Probably supporting of 3 years old browser is not the point, but I always use outdate browser to make sure, that application works as it should even with old standards. 
![image](https://user-images.githubusercontent.com/13100024/118841726-d61b1080-b8c8-11eb-9386-b58450c7164c.png)

Thank you!

Cheers
Alexander

**Comment by mikecao** [comment]
That is strange, it shouldn't be a browser issue. Those are the localization strings before they get translated. But you should never see them.

**Comment by AlexanderPotapov** [comment]
Thank you for swift reply, Mike.

Sure, this is Safari issue, but I'm not sure if it's only desktop version involved or mobile Safari as well.

Any way, it is to letting you know.

Thank you once again
Alexander
