### ISSUE TITLE
Umami counts multiple page views by one page request

### ISSUE THREAD

**Issue by mrcgrhrdt** [mikecao/umami#676]
When I open my website, tracked by Umami, it counts the page view x5 or even more. When I reload the page it counts just one page view.

### My tech stack is:
- NuxtJS (Static site rendered)
- Deployed to Netlify

### My HTML looks like the following:

``` HTML
<template>
	<div>
		<div class="content">
			<Header />
			<div class="spacer"></div>
			<main>
				<section class="mission">
					<div class="comingSoonBadge">
						<p class="comingSoonText">COMING SOON</p>
					</div>
					<h1 class="missionStatement">Step up your<br>digital life!</h1>
					<h2 class="caption">WorkAround is a community for digital nomads around the world to connect with each other.</h2>
				</section>
				<div class="midSpacer"></div>
				<section class="contact">
					<div class="contactSpacer"></div>
					<h3 class="note">We are working hard to release the first beta of WorkAround in September 2021. Until then, please leave your email to be the first to be notified.</h3>
				</section>
			</main>
			<div class="spacer"></div>
		</div>
		<Footer />
    <script async defer data-website-id="<my-id>" src="https://<my-instance>/umami.js"></script>
	</div>
</template>
```

On a normal html website it worked perfectly fine, but now with Vue/Nuxt not anymore.

I appreciate any hint.

**Comment by joshinat0r** [comment]
Shouldn't your IDE already yell at you when you try to use `script` tags within a template?
Thats the issue right there, if you want to embed a script don't do it in components where a framework decides when to load/unload/rerender.

Nuxt specifically has the `nuxt.config.js` where you can add scripts that wont be touched by Vue
```
export default {
  ...
  head: {
    ...
    script: [
      {
        src: 'SCRIPT_URL',
        'data-website-id': 'WEBSITE_ID',
        async: true,
        defer: true,
        'data-do-not-track': true // thats how you add other attributes to the script tag
      }
    ]
  }
  ...
}
```
That'll add the appropriate script tag to the head of you site and wont get touched, works fine on my prerendered Nuxt site.

**Comment by mrcgrhrdt** [comment]
Hii @joshinat0r,
unfortunately VS Code does not yell at me😅 

I knew about the `script` object in the nuxt config but didn't know how to realize the `async` and `defer` tags. 

Thank you very much for the help!
