### ISSUE TITLE
Display of Chinese variants

### ISSUE THREAD

**Issue by Alan-Liang** [mikecao/umami#678]
<https://github.com/mikecao/umami/blob/5ecaf5587b6bb5968a4b0c53c110bf807dbe9fed/lib/lang.js#L133-L134>

Maybe they should be displayed as `zh-CN` and `zh-TW`, or even better, `zh-Hans` and `zh-Hant`?

**Comment by mikecao** [comment]
I prefer the short name display. It's uniform across languages.
