### ISSUE TITLE
Crypto: synchronous password hashing?

### ISSUE THREAD

**Issue by Alan-Liang** [mikecao/umami#679]
<https://github.com/mikecao/umami/blob/5ecaf5587b6bb5968a4b0c53c110bf807dbe9fed/lib/crypto.js#L42-L48>

Why would we use `hashSync` and `compareSync` in asynchronous functions? They could lead to reduced I/O efficiency.

**Comment by mikecao** [comment]
It's not that big a deal performance wise, but yes, should be sync calls.
