### ISSUE TITLE
Railway shared dashboard not rendering

### ISSUE THREAD

**Issue by keerthik** [mikecao/umami#683]
[Shared dashboard hosted on Railway](https://umami-0ce3be-production.up.railway.app/share/QFjN7Inl/LTV) is not rendering any graphs. 

This dashboard is linked from the docs on [deploying to Railway](https://umami.is/docs/running-on-railway).

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/203238/119274446-ea6b5000-bbdd-11eb-982d-d2bc72db0dd5.png">

Reproduced on Firefox 88.0.1 and Chrome 90.0.4430.212 on OSX 11.2.3.
Reproduced on Firefox 88.0.1 on Windows 10.

**Comment by mikecao** [comment]
It looks like you're getting a server 500 error. Make sure the share url and all your settings are correct.

**Comment by keerthik** [comment]
Looks like this comment/issue needs to be applied to the Railway [starters repository](https://github.com/railwayapp/starters/issues) if that is the case. This isn't my umami instance, it's from the share link given as an example at the bottom of the [Deploying to Railway](https://umami.is/docs/running-on-railway) umami documentation.

**Comment by mikecao** [comment]
You should file an issue with Railway in this case.
