### ISSUE TITLE
Refused to display 'https://stats.domain.ext/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by alessandrodorazio** [mikecao/umami#685]
Hi guys,
I'm trying to embed with an iframe the share page, but I receive this error, anyone know how to resolve?

**STEPS TO REPRODUCE**
1) Embed the page /share/{share_id}/{website_name} into an HTML page
2) Visit the page

I resolved removing, on the server side, the header X-frame-options

**Comment by Vikingoa** [comment]
Hi @alessandrodorazio, could you tell me how you did it on the server side please ?
I am confronted to the same problem.
