### ISSUE TITLE
About the color of unique visitors legend

### ISSUE THREAD

**Issue by Hsiao-Feng** [mikecao/umami#686]
I noticed that the color of unique visitors legend is not close to the chart. If the alpha value is set to 0.8, it will be closer to the chart. So I think it will be better to change it to 0.8 .

---

**Before**

![before](https://user-images.githubusercontent.com/13806806/119834713-c89e0000-bf32-11eb-8996-46b5a4dac290.png)

---

**After**

![after](https://user-images.githubusercontent.com/13806806/119834727-cb005a00-bf32-11eb-8167-d464c0cdf839.png)

**Comment by Fawesum** [comment]
I approve of this wonderfully anal analysis.
