### ISSUE TITLE
Administrator: See and edit websites of other users in settings

### ISSUE THREAD

**Issue by gnarlex** [mikecao/umami#687]
Hey there! :)

Currently, the administrator can only look into other users' dashboards via `Settings > Accounts`. It would be very convenient for an administrator to have the ability to edit / "get tracking code" of a user's websites.

Thought about changing the view under `Settings > Websites` to display all users' websites and add an additional column "Owner" representing the user that "added" that website (see attached image)
(Bonus: Add a dropdown for filtering the websites based on owner)

<img width="1135" alt="Screenshot 2021-06-01 at 12 35 52" src="https://user-images.githubusercontent.com/24435169/120310188-65b3bc80-c2d6-11eb-8005-673f763a187d.png">

**Comment by mikecao** [comment]
This is a good idea. The administrator should have the same level of control as the user.
