### ISSUE TITLE
[Feature Request] Share dashboards between users

### ISSUE THREAD

**Issue by persunde** [mikecao/umami#690]
First I would like to say I love your program! Thank you so much <3

Could you implement it so that it is possible to **share one or more dashboards with one or more users**.
Use-case 1: The Administrator wants to share dashboard Homepage with User1 and User2, but not User3.
Use-case 2: User1 wants to share dashboard MY-WEBSITE1 with User2 and/or the Administrator. 

I have a website where I want some of my clients to see some of the dashboards/analytics, but not all of them. And some of these "private" dashboards could then potentially be viewed by multiple different users. Even if you could only share a dashboard with one other user that would also be good enough.
I would greatly appreciate it if this was implemented. 

You can share an URL, but this makes it public to everyone. I want to be able to share non-public dashboards between users.

If this already exists, please let me know how to do this, as I was unable to do this in the settings from either the Admin user or a test user.

Thank you for your time spend developing this software!

**Comment by mikecao** [comment]
This has been discussed before but basically umami does not have a complex role system on purpose. The share url feature serves this purpose. it does what you want with the least amount of issues because accounts can delete websites they own. The private share url is at least read only.

**Comment by persunde** [comment]
So this means there are NO plans to develop this feature in the future? I understand.
Anyways, thank you for this great software.
