### ISSUE TITLE
Somaliland shows up as "undefined"

### ISSUE THREAD

**Issue by nukeop** [mikecao/umami#691]
See this screenshot.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/12746779/120676897-085e6d80-c486-11eb-9b94-b44240f52cc8.png">

Somaliland is in the northern part of Somalia and apparently considered a separate country. When you hover over it, it shows up as "undefined".

https://en.wikipedia.org/wiki/Somaliland

**Comment by mikecao** [comment]
There datamaps source we are using does not give Somaliland an id, that's why it show up as undefined. Apparently there is no official country code for it according to this https://stackoverflow.com/questions/16170385/somaliland-country-abbreviation
