### ISSUE TITLE
The table `public.account` does not exist in the current database.     at cb (/Users/vic2/GitHub/proj/umami/node_modules/@prisma/client/runtime/index.js:34780:17)

### ISSUE THREAD

**Issue by cekvenich2** [mikecao/umami#692]
I used the online tutorial to create on supabase postgres and get the error.
Public schema exists, and I granted rights, but no joy.
Help?

**Comment by mikecao** [comment]
Log into your database and see if the tables are there.

**Comment by babeuloula** [comment]
Hello, I've got the same issue. 
On the docker image on the directory `/docker-entrypoint-initdb.d` you don't have `schema.postgresql.sql` because it's a directory.
