### ISSUE TITLE
Thanks for making this ❤️

### ISSUE THREAD

**Issue by harrisjose** [mikecao/umami#7]
I've been debating rolling my own hacky solution for a while now - just needed some stats without stepping into the chasm that is google analytics - so this is just perfect for me. 

Again, great stuff and thanks for putting this out in the open 🏆

**Comment by mihha** [comment]
I agree with @harrisjose 

Your application is wonderful!

Thank you for sharing this with the community

**Comment by mikecao** [comment]
Thank you all for using it!

**Comment by jkyngan** [comment]
thank you !

**Comment by martin-ro** [comment]
looks great..  ty

**Comment by MonksterFX** [comment]
Really good work!

**Comment by mech** [comment]
Allows me to study Next.js example also. Appreciated and useful 👍

**Comment by surjithctly** [comment]
Thanks for making this 😍😍😍
