### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by blaskoviktor** [mikecao/umami#702]
Hello, I have made a Hungarian translation. Unfortunately GitHub doesn't allow to attach the json file, so I zipped it. I hope that's not a problem. :)
[hu-HU.zip](https://github.com/mikecao/umami/files/6623414/hu-HU.zip)

**Comment by blaskoviktor** [comment]
I completely forgot the country codes. :) So here they are, and some changes to the previously submitted translation.
[umami-hu-translation.zip](https://github.com/mikecao/umami/files/6626111/umami-hu-translation.zip)

**Comment by mikecao** [comment]
Thank you! I'll work on getting this added

**Comment by blaskoviktor** [comment]
Thank you too! I once again checked the translation to make sure it is correct, and noticed that I had omitted one word.
`"metrics.device.desktop": "Asztali"`
It still makes sense, but it looks nicer that way:
`"metrics.device.desktop": "Asztali számítógép"`
Shorter form:
`"metrics.device.desktop": "Asztali PC"`

**Comment by mikecao** [comment]
This is now available in v1.19.0 🥳
