### ISSUE TITLE
Rate limit require

### ISSUE THREAD

**Issue by bulog** [mikecao/umami#708]
I just tried to do the post request to the collect endpoint for as many as times in the console of the Chrome with javascript code, all requests handled success by the umami server.

So is there a way to limit this kind of fake request data?

The code I just tested is bellow:

``` javascript
var data = JSON.stringify({"type":"pageview","payload":{"website":"d0059975-b79a-4f83-8926-ed731475fded","hostname":"umami.is","screen":"1600x900","language":"zh-CN","cache":null,"url":"/","referrer":""}});

var i = 1;
var imax = 10000;
function post() {
fetch('https://app.umami.is/api/collect',{
 　   method:"POST",
 　   mode: 'cors',
　　headers: {
　　　　'Content-Type': 'application/json'
　　},
　　body: data
　　}).then(() => {
        i++;
        if(i < imax) post();
    }).then(() => {})
}
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
post();
```

**Comment by mikecao** [comment]
I would appreciate it if you didn't spam my sever for your tests.

 But to answer your question, all rate limiting has to be done on the web server itself. I'm using Vercel and I don't know what kind of features they have available.

**Comment by bulog** [comment]
Sorry for the test data. yes, nginx and cloudflare can do the limiting
