### ISSUE TITLE
Session view

### ISSUE THREAD

**Issue by prenaux** [mikecao/umami#709]
Maybe I missed it and its already there, but is there some kind of session view?

That is a list of all the latest sessions and a detail page for each session. Essentially a UI for the following:
(using PostgreSQL)

List sessions:
```
SELECT
  session_id, hostname, browser, os, device, screen,
  (SELECT COUNT(*) FROM pageview WHERE session_id = session.session_id) AS pageview_count,
  (SELECT COUNT(*) FROM event WHERE session_id = session.session_id) AS event_count,
  created_at
FROM session ORDER BY created_at DESC LIMIT 50;
```

List of visits:
```
SELECT url, referrer, created_at FROM pageview WHERE session_id = 2 ORDER BY created_at DESC;
```

List of events:
```
SELECT url, event_type, event_value, created_at FROM event WHERE session_id = 2 ORDER BY created_at DESC;
```

**Comment by mikecao** [comment]
No, there is no such view. The closest thing is the real-time view where you can watch what users are doing.

**Comment by prenaux** [comment]
Where should I look in the code base to add a view myself?

**Comment by prenaux** [comment]
Ok, thanks I'll take a look to see if I can that myself.
