### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by julimancan** [mikecao/umami#716]
Hi there, I really love your idea I think it's awesome to use Open Source projects. 
I wanted to use your project together with a Supabase DB as they are open source and it's already hosted online. Setting up was a breeze I forked your project and then connected it to Vercel setup my DATABASE_URL from what I got from Supabase and setup my own HASH_SALT string. 

I deployed it and it was amazing changed my pw and connected my own personal site to test. Everything worked and umami was getting the site visits.

But a few minutes later it stopped working, I tried going to the websites and to the dashboard and sometimes it would get some information but most often than not it didnt. I have attached a screenshot of the errors the console shows. 
![image](https://user-images.githubusercontent.com/64240466/124167330-e8649e80-da71-11eb-9ce8-bde65de5098e.png)

Back on my site there was also another error:
POST https://******.vercel.app/api/collect 500

Any idea what could have gone wrong? Is it because of Supabase?

**Comment by mikecao** [comment]
You need to go to your Vercel dashboard to get the actual error occurring on the server. Should be under the Functions log.

**Comment by julimancan** [comment]
These are the log errors from trying to checkout the stats on my umami site

![image](https://user-images.githubusercontent.com/64240466/124323947-1cae8c80-db50-11eb-96a7-cbb4f31451e3.png)

**Comment by mikecao** [comment]
Looks like an issue with the Supabase database. The error just says something went wrong at the database level.

**Comment by julimancan** [comment]
Dammm I really wanted to use Supabase thank you for taking the time to reply to this!
