### ISSUE TITLE
Windows 11 Support In Analytics

### ISSUE THREAD

**Issue by mtgsquad** [mikecao/umami#720]
My Friend, was showing me his analytics, saying that he saw that i logged in, It said that i opened the website with a `Windows 10 Laptop`, when i'm on windows 11, this would be quite a good feature update. Thanks.

**Comment by mikecao** [comment]
The detection is performed by the `detect-browser` package. You can file a bug with them.

**Comment by lkinsella** [comment]
Just to note for others coming by this, the problem is with the User Agent which always reports Windows 10, for example I'm on 11 but my current user agent is:-

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
```

It is somewhat annoying but not a lot you can do about it.
