### ISSUE TITLE
Error with custom docker-compose: "Can't reach database server"

### ISSUE THREAD

**Issue by william-roy** [mikecao/umami#725]
I'm trying to add Umami to my existing docker-compose setup, and it starts up just fine, but upon trying to login, can't seem to connect to the database (a digital ocean postgres database cluster). I've seeded the database using the `sql/schema.postgresql.sql` file, which worked just fine—I can connect through pgadmin and verify this. I can also verify the database is connectable:
![Screenshot 2021-07-11 204301](https://user-images.githubusercontent.com/51927032/125215256-e88e4680-e288-11eb-873a-bf611b0dfbad.png)

Here's the relevant part of the docker-compose.yml (omitting private info):
![image](https://user-images.githubusercontent.com/51927032/125214824-2f7b3c80-e287-11eb-9199-dc86746b6323.png)

And here's the error (again, omitting private info):
```
umami     | PrismaClientInitializationError2 [PrismaClientInitializationError]: Can't reach database server at `<host>`:`25060`
umami     |
umami     | Please make sure your database server is running at `<host>`:`25060`.
umami     |     at cb (/app/node_modules/@prisma/client/runtime/index.js:35107:17)
umami     |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
umami     |   clientVersion: '2.23.0',
umami     |   errorCode: undefined
umami     | }
```

I've seen other closed issues where there were problems with the connection string, but i've triple-checked it and can say for sure it is correct and valid. I also have another service in the same docker-compose file connecting to another database in the same cluster just fine, so I don't think it's an issue of permissions, firewalls, outbound connections, etc.

**Comment by william-roy** [comment]
I managed to solve this by creating a connection pool for Umami and connecting to that. [This tutorial](https://www.digitalocean.com/community/tutorials/how-to-deploy-your-own-web-analytics-software-with-umami-on-digitalocean-s-app-platform) mentions that:

> PostgreSQL was built to have persistent connections. The Next.js API routes that Umami runs on, however, are not able to share database connections across requests. To support the short-lived connections that will be made from the API route and prevent errors, you will create a connection pool for your cluster.

I didn't see anything about this mentioned in Umami's docs, but it may be worth adding a note somewhere if there isn't one already.

**Comment by mikecao** [comment]
@william-roy Thanks for the info. The text about postgresql seems odd to me though. I am running postgresql myself and don't have any connection issues, and I don't use pooling. Maybe it's something specific with docker.

**Comment by william-roy** [comment]
It might be something specific to digitalocean's database clusters? Maybe @okezieuc can clue us in.

**Comment by thorie7912** [comment]
I narrowed down the issue to my host firewall. For example, if I disable my firewall with the command `ufw disable` and then try the same `nc` command it connects properly. Apparently this ufw-docker incompatibility was well-known since 2014 and leading to high-profile security incidents.
