### ISSUE TITLE
Umami Tracker is being blocked by Brave Browser

### ISSUE THREAD

**Issue by mcnaveen** [mikecao/umami#726]
Umami Tracker script `umami.js` is getting blocked by Brave Browser not sure this is happening with other AdBlockers.

Is it because of subdomain contains `analytics.example.com` or since umami is now used by many so they are aware of it and blocking.

Is there any workaround to bypass this?

**Comment by mikecao** [comment]
Depends on how they are blocking it. If it is just by name, then rename the script to something else.

**Comment by mcnaveen** [comment]
How to rename the script?

**Comment by mikecao** [comment]
Just rename `umami.js` to something else.

**Comment by cirrusflyer** [comment]
Does making a copy and then calling it in the site code do the same thing?  I've tried this, and doesn't seem to work.

**Comment by Luminilion** [comment]
https://www.freecodecamp.org/news/save-your-analytics-from-content-blockers-7ee08c6ec7ee/ Found this without actually implementing it, but the concept makes sense --> hide your analytics url behind a website url e.g. google.analytics.com requests hidden behind mycompanywebsite.com requests

**Comment by mcnaveen** [comment]
Also, I found using the words "stats, tracking, views, counter" in the subdomain of Umami is automatically blocked by AdBlockers. So I'm using the name `umami.` as my subdomain

**Comment by mcnaveen** [comment]
Hi @mikecao 

Here is a little update.

I tried proxy passing the umami.js file with Nginx Configuration, but I don't know why it's not tracking. (But the same block works with Plausible)

```
    location = /js/script.js {
        proxy_pass https://mydomain.com/umami.js;
        proxy_buffering on;

        proxy_set_header Host mydomain.com;
        proxy_ssl_name mydomain.com;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse off;
    }

```

**Comment by StarryMoe** [comment]
Hi @mcnaveen 

Here is the Nginx Configuration reference. This is what I found in Plausible's issues, the same applies to umami, it works fine on my site, hope it helps you.

  
`
  rewrite ^/script.js$ /umami.js last;

  location / {
    proxy_pass http://localhost:3000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
`

**Comment by mcnaveen** [comment]
Thanks @StarryMoe

**Comment by mcnaveen** [comment]
Hi @StarryMoe is this still working?

**Comment by StarryMoe** [comment]
Hi @mcnaveen
This method is outdated and if you browse the [documentation](https://umami.is/docs/environment-variables) you will find that the latest version of Umami has a
The TRACKER_SCRIPT_NAME environment variable allows you to customize the name of the script without requiring additional settings from nginx.

**Comment by mcnaveen** [comment]
Why I'm asking is to hide the umami domain name under the proxy using nginx.

**Comment by StarryMoe** [comment]
Maybe this - [Proxying with Nginx](https://umami.is/docs/running-on-digitalocean)
