### ISSUE TITLE
v1.19.0 and Vercel

### ISSUE THREAD

**Issue by mikecao** [mikecao/umami#731]
I am currently seeing an issue where the country IP database is missing when deployed to Vercel. This release also updated Next.js to the latest version which seems to be the issue. If you are hosting on Vercel, I would recommend staying on v1.18.0 until this is resolved.

**Comment by 0xjessel** [comment]
Currently getting this 500 error when pinging `/api/collect`:

`ENOENT: no such file or directory, open '/var/task/public/geo/GeoLite2-Country.mmdb'`

In case anyone also is encountering this issue and needs these keywords to find this issue.

**Comment by mikecao** [comment]
In v1.20.0 I reverted the Next.js version back to 10 so Vercel should work again. Still trying to figure out why it's happening but we'll keep it at this version until there's a solution.

**Comment by DominikGeimer** [comment]
> In v1.20.0 I reverted the Next.js version back to 10 so Vercel should work again. Still trying to figure out why it's happening but we'll keep it at this version until there's a solution.

I just tested it and it works. Thanks.

**Comment by christopherpickering** [comment]
Trying to find what's going on... it seems like when I build on netlify it is in a different dir than where the site is run from :
![image](https://user-images.githubusercontent.com/17788706/154816227-8b16d792-937f-49c1-af69-be1d7ee12030.png)

**Comment by christopherpickering** [comment]
I have four other umami sites on v 1.25, which work fine. I tried downgrading next to the version used there, but no luck. I don't understand as the logs on the v 1.25 install are identical... So I tried installing w/ v 1.25 - same code as my other sites, and got the same error lol. I must be missing something very dumb 😁

**Comment by mikecao** [comment]
Well you got further than me. I’ve never been able to successfully deploy to netlify.

**Comment by christopherpickering** [comment]
lol really? Maybe I should try on vercel. I just don't understand why 4 sites are working and one won't. I wonder if netlify is doing something differently now. Anyways, I'm trying to build locally and updated gitignore to include the geo db and will see what happens.

**Comment by christopherpickering** [comment]
No luck, I switched to vercel and it works.

**Comment by christopherpickering** [comment]
@mikecao Thanks for the tool, I love it.

**Comment by christopherpickering** [comment]
fyi, I found a fix for this in Netlify! It seems like the latest netlify plugin for next functions doesn't copy over any of the build. By adding ``netlify.toml`` to include the file.
```toml
[functions]
included_files = ["public/geo/*.mmdb"]
```
If you don't mind, I'll do a PR with this as it seems to be the only thing needed to make netlify work :)
