### ISSUE TITLE
Ignore sub domains

### ISSUE THREAD

**Issue by MickyBizzle** [mikecao/umami#747]
Is it possible to configure Umami to ignore subdomains?

My environment is set up such that dev.example.com is the preview branch and example.com is the live branch. I've configured the script with data-domains="example.com" but I'm still seeing dev stats in the dashboard which I'm assuming means that Umami doesn't care about sub domains?

Cheers

**Comment by GurjinderSingh** [comment]
normal practice is you disable stuff at code level server side. simply put a if else block in server side code where you echo your html.

**Comment by mikecao** [comment]
The domain is not relevant to the tracking script. @GurjinderSingh is correct, you should disable the tracker wherever you don't want it to track.
