### ISSUE TITLE
Multiple trackers for same domain

### ISSUE THREAD

**Issue by dyanakiev** [mikecao/umami#748]
Hello, is it possible to create multiple "websites" with the same domain or can i create just random string domains?
I want to track specific pages uniquely and i need separate scripts.

**Comment by mikecao** [comment]
Only the website id matters for collecting stats. The domain is just used to filter out referrers from the same domain.

**Comment by a1p4ca** [comment]
Sometimes you use different domains for the same site, such as the www domain. In this case, it is inconvenient to appear as a referrer if it is not set as a domain.

**Comment by tans** [comment]
so it can embed share URL in my saas to show my client their page analytic ？my saas uses the same domain for all clients.

**Comment by dyanakiev** [comment]
> so it can embed share URL in my saas to show my client their page analytic ？my saas uses the same domain for all clients.

sure you can :)
