### ISSUE TITLE
Show stats about browser languages

### ISSUE THREAD

**Issue by holtwick** [mikecao/umami#750]
Maybe I'm missing something, but I can only find statistics for countries, but not for **languages**. 

In Europe in **multiple countries, multiple languages** are used like in Switzerland or Belgium. Also do **many users speak multiple languages**.

It would be interesting to know which languages are used by the visitors to consider translations to new languages for a website etc.

Thanks for this awesome project!

**Comment by mikecao** [comment]
The data is stored but there is not UI for it yet. But the data exists if you want to query it.
