### ISSUE TITLE
[bug?] Filtering on sub pages does not show correct data (or at all).

### ISSUE THREAD

**Issue by NoLooseEnds** [mikecao/umami#754]
Running v1.20.0 in Docker.

Recently I've been having issues with showing stats filtered by a specific visited page/url. The thing is it only seems to be an issue on a specific site. 

The site can show all the different subpages gotten hits, but clicking on one of them shows zero visits in the header, but keeps the main site data. Visiting the sub-page directly via `?url=<url>` everything is zero (even if the toplevel/main site shows the subpage has had i.e 10 visits).

I've tested logging out and in again. Using a different browser. Incognito modes, etc.

I've put together an image showing the issue (from the left: main site, filtered on sub page from main site, visited directly via `?url=<url>`)
![umami_bug](https://user-images.githubusercontent.com/4103531/129192812-81615a6d-4a07-4cde-b814-8c6f47326443.jpg)

(I can send a private URL on PM if you want to see it live)

**Comment by mikecao** [comment]
I think I will need to revisit the URL filtering logic.

**Comment by mikecao** [comment]
Try again with the latest v1.24 and see if it's is still an issue. The filtering logic was reworked. Closing this issue, re-open a new one if needed.
