### ISSUE TITLE
[Feature request] Ping for visit time

### ISSUE THREAD

**Issue by marchellodev** [mikecao/umami#761]
Hello, I am trying to use umami in a mobile app. That's why I do not want to to send `pageview` every time the user changes the screen. However, visit time seems to be calculated by those `pageview` requests. Is there any way I could do just pings, not page visits, to update the server that the user is still online?

Thanks for such an amazing piece of software!

**Comment by mikecao** [comment]
The plan is to use the beacon api and that is covered by #446
