### ISSUE TITLE
about .env file in the README

### ISSUE THREAD

**Issue by felixsanz** [mikecao/umami#764]
readme says:

> Configure umami
Create an .env file with the following

> DATABASE_URL=(connection url)
HASH_SALT=(any random string)

So... create an .env file where? with what name?

**Comment by joshinat0r** [comment]
`.env` is the complete filename for your environment file. Check https://docs.docker.com/compose/env-file/ for more

**Comment by felixsanz** [comment]
it works thanks! It was kind of confusing because `create an .env file` sounds like you have to create a file with that extension, not name
