### ISSUE TITLE
Option to skip views from localhost?

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#768]
It would be great if Umami could skip views from localhost because there might be times when we keep developing projects even after adding Analytics.

If there is an option already, please guide me. I searched existing issues but did not find any.

**Comment by mikecao** [comment]
Either
1) modify your code to only render the tag when in production
2) or add `umami.disabled = true` to your browser localStorage

**Comment by WLun001** [comment]
Possible to disable it via query params like [Panelbear](https://panelbear.com/docs/exclude-browser/)

**Comment by LeoSeyers** [comment]
> It would be great if Umami could skip views from localhost because there might be times when we keep developing projects even after adding Analytics.
> 
> If there is an option already, please guide me. I searched existing issues but did not find any.

There is the `data-domains` option (https://umami.is/docs/tracker-config) for that purpose as well

**Comment by phosphotungstic** [comment]
I test on prod (I'm just a microblog, don't shoot!)
So using `data-domains` doesn't really work for me.
I've added a PR that could add the feature to both have it temporarily or set it as a localStorage option from the URI.
