### ISSUE TITLE
Location data is not working

### ISSUE THREAD

**Issue by plezploz** [mikecao/umami#769]
I've tested this and everything else works fine. Location _unknown_ is shown for a lot of the times:
![image](https://user-images.githubusercontent.com/58833036/130679600-d340e11e-ee79-496c-8683-2fb1a1b5dcf7.png)

Is there any way for this to be fixed?

**Comment by mikecao** [comment]
In most cases, it's because you didn't forward the ip information from your web server. See #444

**Comment by plezploz** [comment]
I use nginx and I tried forwarding the correct headers but location still shows as unknown for everyone.

**Comment by plezploz** [comment]
Never mind, I had to restart the server for the changes to take effect for some reason. A nginx restart didn’t cut it.
