### ISSUE TITLE
Mysql connection string not working

### ISSUE THREAD

**Issue by ntimo** [mikecao/umami#77]
Hello,
I just tried to setup umami but I always get this error in the logs:
```
PrismaClientInitializationError: error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `postgresql://.`
```

My connection string looks like this (the password is generated):
`mysql://umami:mPEunth4DXB25hDGwhnx@mariadb.example.com:3306/umami`

I am using Docker the image is build from the master brach (today). I am setting the database connection string using DATABASE_URL via docker-compose.

Do you have an idea why it is not working?

Thanks and best wishes,
Timo

**Comment by ntimo** [comment]
I also tried setting the env variable: `DATABASE_TYPE=mysql` but I still get the same error.

**Comment by jensao** [comment]
If you just building the image, does this work: `docker build . --build-arg DATABASE_TYPE="mysql"  -t umami:test `

If you are using a docker-compose file does something like this work:

```
umami:
    build: 
      context: ./umami
      args: 
        DATABASE_TYPE: mysql
```

**Comment by ntimo** [comment]
That works indeed. But why do I have to set this at build time? Also there should be docs for this :) I might open a PR for these, if you can tell me where I have to put these?

**Comment by mikecao** [comment]
The wiki is open for anyone who wants to create docs.

**Comment by mikecao** [comment]
Closing as resolved. File a new issue if you need additional help.
