### ISSUE TITLE
Umami on AWS

### ISSUE THREAD

**Issue by Vultik** [mikecao/umami#771]
Hello, Thank you for Umami. 
Do you know if it's possible to deploy umami on AWS Amplify ? 
For now, i use heroku but i have other apps on aws. I don't want to use an EC2 instance that seems to overkill.
So i successfully deploy the front end but there is issue with backend database.
Is there someone that successfully deploy umami on AWS ?

**Comment by Vultik** [comment]
Yes i know it's possible to use a database exposed to the public but the purpose was to have some kind of "localhost" database on aws that is linked to umami/prisma

**Comment by mikecao** [comment]
You can install umami on the same server as the database, if you're hosting the database yourself. Otherwise, I think AWS allows local IP addresses, assuming your servers are in the same region.
