### ISSUE TITLE
Replace MetricCard change from 0 to =

### ISSUE THREAD

**Issue by landjonathan** [mikecao/umami#772]
Today I happened to see the following:
<img width="121" alt="Screen Shot 2021-08-27 at 15 35 08" src="https://user-images.githubusercontent.com/43704451/131128224-becc6af9-ff28-4532-856d-8618f56ae3ba.png">

At first glance the labeling is confusing – there is no clear indication that the small number is relative, whether with sign or color. While comparing to other cards in the row explains the intention, it's still unclear when confusing on the single metric.

I think it would be a better UX to display an equals sign when there is no change.

If the change is accepted, I'd be glad to submit a PR. Would the following be correct approach, or am I missing something?
```js
// MetricCard.js

-   {~~change === 0 && <span className={styles.change}>{format(0)}</span>}
+   {~~change === 0 && <span className={styles.change}>=</span>}
```

**Comment by mikecao** [comment]
A better solution may be to not show anything at all when it's equal.
