### ISSUE TITLE
Feature request: Add 24 hour format

### ISSUE THREAD

**Issue by Vultik** [mikecao/umami#774]
As in title, it will be great especially for european users to have time in 24 hour format.
For example a buton,  in the settings dashboard to select between 12/24 hour format.
Thanks for this awesome light analytics tool :)

**Comment by Vultik** [comment]
In fact, i have discover that it's implemented when you select the language.
It will be great thought to choose between the 2 formats in the settings menu to keep the default language (en-US).

**Comment by mikecao** [comment]
This is solved by now using `English (UK)` as the language.
