### ISSUE TITLE
Support proxy authorisation headers

### ISSUE THREAD

**Issue by ntimo** [mikecao/umami#78]
Hello,
first off thanks for creating umami. :)

I would like to suppose to add support for http headers to login users. This could be used in SSO setup where a `Remote-User` header is send including the username. If this header is present umami could automatically login the user without the need to enter his password. This makes central management of credentials and auditing super efficient and easy.

**Comment by mikecao** [comment]
I'm not that familiar with SSO schemes, but would welcome a PR from the community. Not sure many users would need this feature so it will likely be low priority.
