### ISSUE TITLE
Unique constraint failed on the constraint: `session_uuid`

### ISSUE THREAD

**Issue by nullifye** [mikecao/umami#782]
I have upgrade to umami 1.22.0 and my **Realtime** page is blank.
I'm tailing the log and I see this error message.

How to resolve this? I'm using mariadb BTW

![umami](https://user-images.githubusercontent.com/11532124/132608927-52452ef4-b0cf-4835-98b9-a96aeb99d044.PNG)

**Comment by mikecao** [comment]
Usually this happens when there is a lot of traffic and the session_uuid isn't generated yet before another request comes in. We can probably check the error message to avoid this.
