### ISSUE TITLE
Recommend change the sql default charset to utf8mb4_general_ci

### ISSUE THREAD

**Issue by syhyz1990** [mikecao/umami#786]
It is recommended to change the sql file :

ENGINE=InnoDB COLLATE=**utf8_general_ci** => **utf8mb4_general_ci**

because if the url contain emoji, like `https://www.baiduyun.wiki/zh-cn/#🎨-助手界面` , when insert into pageview table, there is a mysql error in server 

![image](https://user-images.githubusercontent.com/5344173/133360956-5b34d69f-4514-45b8-9b2a-d566870ab687.png)

**Comment by mikecao** [comment]
I'm not sure about the support for `utf8mb4_general_ci` among MySQL version. I think whoever needs it can change it on their own setup.
