### ISSUE TITLE
Example for PHP Tracker

### ISSUE THREAD

**Issue by holtwick** [mikecao/umami#787]
For my websites I wanted to track downloads and other stuff, where no JS is involved. I used to use some PHP snippets with my previous solutions to track those. The server side PHP would call the API. Matomo e.g., has sample code for it, but I was not able to find some for Umamai. Therefore, I wrote my own ;)

https://gist.github.com/holtwick/cf952d02be5f2960e2742676461564fe

The `collect` API call is not documented very extensively, though I had to look into Umami's code. Passing the IP was a bit tricky and I ended up using your CloudFlare workaround. Most data is passed in headers, but might be more compfortable to solve as additional parameters to the JSON object.

So suggestion is to extend the documentation and add some more properties to the JSON object, in order to have complete control over the entry generated for Umami without using header modification tricks. Thanks.

**Comment by mikecao** [comment]
There some info about API usage here, https://umami.is/docs/api

**Comment by tvdsluijs** [comment]
I would like a PHP tracker to the UMAMI cloud. Not sure if I can use @holtwick code for this?
