### ISSUE TITLE
Date selector dropdown with calendar

### ISSUE THREAD

**Issue by dakshshah96** [mikecao/umami#79]
Instead of just having pre-defined options like _Last 24 hours, Last 7 days, etc._, it'd be great to have a date range selector in the form of a calendar along with it so users are able to view metrics for a specific date or a date range of their choice.

**For example:**

![Screenshot 2020-08-30 at 9 36 40 AM](https://user-images.githubusercontent.com/7896438/91650984-6cda3f80-eaa4-11ea-8a90-d478c227569f.png)

**Comment by mikecao** [comment]
Yes, that feature is planned.

**Comment by dakshshah96** [comment]
@mikecao Would be happy to help with this if needed!

**Comment by mikecao** [comment]
Added in latest release #154
