### ISSUE TITLE
Tracking module

### ISSUE THREAD

**Issue by darsain** [mikecao/umami#8]
Would it be possible to transform current tracking script into an npm module?

I'd like to import it into my code base so I can set it up and use directly in the app code.

Sending events and page views on purely JS based websites would then be trivial.

It'd also not be prone to being blocked by `*/umami.js` or similar rules.

**Comment by PabloSzx** [comment]
> It'd also not be prone to being blocked by `*/umami.js` or similar rules.

I think another feature that could tackle this issue is allowing to change the script file name to an arbitrary name from the dashboard.

**Comment by mikecao** [comment]
You can simply rename the file in the `public` directory to whatever you want and point your tracking code to it. The only important part of the tracking code is the `data-website-id`.

**Comment by mikecao** [comment]
I'll work on making it a global var so you can send event manually.
