### ISSUE TITLE
Country data NOT collecting properly

### ISSUE THREAD

**Issue by dsofeir** [mikecao/umami#814]
# Issue
Umami does not correctly record the country of visitors. All visitors are recorded as being from Germany, even though I am visiting the site from Australia. 

The server on which umami runs is located in Germany, however if you look at [the HTTP headers](https://github.com/mikecao/umami/files/7307774/umami_test_headers.txt) you will see no German IP address is mentioned. Also the Docker container is unaware it is located in Germany as the NGINX reverse proxy making the request to it and the LXC container in which it is nested both have a 10.109.0.0 (private) IP address.

## Environment
- Umami v1.22.0
- Running in an LXC nested Docker container
- External shared MariaDB database
- Behind an NGINX reverse proxy with following relevant settings:
```
proxy_set_header Host $host;
proxy_set_header X-Real-IP  $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header Forwarded "$proxy_add_forwarded;by=$server_addr;host=$host;proto=https;"; #RFC7239
```

## Screenshots
![umami_screenshot](https://user-images.githubusercontent.com/2790648/136483289-e5a00634-0caa-4df7-b61b-cb2628d64eda.png)

## Debug data
See [umami_test_headers.txt](https://github.com/mikecao/umami/files/7307774/umami_test_headers.txt) for all HTTP headers. Please note, this was created on a separate LXC container behind the same NGINX reverse proxy with an identical configuration

**Comment by ajnisbet** [comment]
Yeah the cloudflare header is wrong.

In my case, I have both the website and umami behind cloudflare and I'm using the public domain in nginx `proxy_pass`.

So a request goes 

```
client → cloudflare (www.example.com) → nginx_proxy → cloudflare (analytics.example.com) → umami
```

and at each step, cloudflare sets `cf-connecting-ip`  to the incoming ip, as it can't trust the value already in the header.


With so many headers and combinations of proxy software it's probably hard to support everything at once. An easy fix for me would be to not put umami behind cloudflare.

Could you first check for something like `x-umami-client-ip` that won't be overridden?

**Comment by mikecao** [comment]
@ajnisbet Have you tried setting the `X-Forwarded-For` header in your nginx proxy -> cloudflare step? It looks like they should respect the values, https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

**Comment by ajnisbet** [comment]
I tried just now, cloudflare does do `x-forwarded-for` properly, but `cf-connecting-ip` is still the nginx IP so umami is picking that up first.

It would work if the umami check for cloudflare was removed, but sounds like that would break vercel.

**Comment by dsofeir** [comment]
@ajnisbet Hello, I'm not using CloudFlare. All this is hosted on our own private cloud. Thank you

**Comment by dsofeir** [comment]
I have stated this already, but I should emphasize that NONE of the IP addresses contained in the sample headers I provided are German. So this is not the typical scenario where Umami is detecting the IP of the NGNIX reverse proxy as that has an address in the private rang 10.109.0.0/16.

**Comment by ajnisbet** [comment]
I think an env variable would be a tidy way to support all sorts of proxy setups, including mine. Sorry about hijacking dsofier's issue which seems a bit different.

**Comment by 907739769** [comment]
> I'm having the same issue. All visitors appear to come from the country in which the nginx proxy is located.
> 
> I'm using these settings:
> 
> ```
> location = /api/collect {
>             proxy_pass https://analytics.example.com/api/collect;
>             proxy_buffering on;
>             proxy_http_version 1.1;
>             proxy_ssl_session_reuse off;
>             proxy_ssl_server_name on;
>             proxy_set_header X-Forwarded-Proto https;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header X-Forwarded-Host  $host;
>         }
> ```

Thanks.

**Comment by charleslcso** [comment]
> > I'm having the same issue. All visitors appear to come from the country in which the nginx proxy is located.
> > I'm using these settings:
> > ```
> > location = /api/collect {
> >             proxy_pass https://analytics.example.com/api/collect;
> >             proxy_buffering on;
> >             proxy_http_version 1.1;
> >             proxy_ssl_session_reuse off;
> >             proxy_ssl_server_name on;
> >             proxy_set_header X-Forwarded-Proto https;
> >             proxy_set_header X-Real-IP $remote_addr;
> >             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >             proxy_set_header X-Forwarded-Host  $host;
> >         }
> > ```
> 
> This fixed my issue! Thanks!

I'm using this in my Nginx reverse proxy, and I'm still getting Unknown in Countries.
