### ISSUE TITLE
Error in endpoint api/website/[id]/metrics

### ISSUE THREAD

**Issue by RizkyRajitha** [mikecao/umami#82]
i setup project locally in master branch.

i can add a site . but when i go to dashboard it throws an error

![front](https://user-images.githubusercontent.com/38534289/91660818-aa1aed80-eaf5-11ea-87b4-235fc99df319.PNG)

---

![front 2](https://user-images.githubusercontent.com/38534289/91660890-1a297380-eaf6-11ea-8349-65afa6fc8159.PNG)

error in cli

![cli](https://user-images.githubusercontent.com/38534289/91660824-b43cec00-eaf5-11ea-88e2-7b5a9c202077.PNG)

i modified the code and found that i get a empty object

modified `pages\api\website\[id]\metrics.js` with console log
```
import { getMetrics } from 'lib/queries';
import { ok } from 'lib/response';

export default async (req, res) => {
  const { id, start_at, end_at } = req.query;

  const metrics = await getMetrics(id, new Date(start_at), new Date(end_at));

  console.log(metrics);

  const stats = Object.keys(metrics[0]).reduce((obj, key) => {
    obj[key] = +metrics[0][key];
    return obj;
  }, {});

  return ok(res, stats);
};

```

postgres db tables

session

![session](https://user-images.githubusercontent.com/38534289/91660854-e9e1d500-eaf5-11ea-861e-89852597dad2.PNG)

pageviews

![pageview](https://user-images.githubusercontent.com/38534289/91660857-eea68900-eaf5-11ea-8b96-7f02e1343800.PNG)

is tried both localhost and also cloud dbs. both same issue.
 
thanks

**Comment by mikecao** [comment]
Are you running the latest version? That code doesn't look right. This is what is there currently:

```javascript
const metrics = await getMetrics(+id, new Date(+start_at), new Date(+end_at));
```

**Comment by RizkyRajitha** [comment]
yes i tweaked it (removed `+` ) to test .
this (with `+` ) won't work either .

**Comment by RizkyRajitha** [comment]
ahhh. figured it out finally .

my db path was 
`DATABASE_URL=postgres://postgres:123@localhost:5432/postgres`
when i changed that to 
`DATABASE_URL=postgresql://postgres:123@localhost:5432/postgres`
now it is working correctly . 

my bad.

thanks ✌
