### ISSUE TITLE
Use for browser extensions

### ISSUE THREAD

**Issue by marcelreppi** [mikecao/umami#835]
I wanted to use umami to track events in a browser extension, however I can't make it work for some reason.
~~Using the `script` tag doesn't work due to CSP~~ I got it working only for the Vue.js files of my browser extension but not for any background scripts. I tried downloaded the script and import it instead and do the tracking via JS but `umami` is not added to the `window` object for the background scripts.

Any ideas how to get this working for browser extensions? 

Thanks!

**Comment by marcelreppi** [comment]
I now got it working just for the Vue.js files of my browser extension by setting the `content_security_policy` in the `manifest.json` and using the `script` tag as usual in my `index.html`.
However I still have an issue using it in background scripts. `umami` is not available on the `window` object.

**Comment by marcelreppi** [comment]
I got it working for background scripts by using a background page instead of single scripts but that kind of breaks my application.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background
```
  "background": {
    "page": "my-background.html"
  }
  ```

I would highly prefer using the `scripts` syntax 😞 
```
  "background": {
    "scripts": ["umami.js", "my-background.js"]
  }
```

**Comment by marcelreppi** [comment]
Got it working now with the `script` syntax by altering the downloaded `umami.js` file the following way:
1. `m = v.querySelector("script[data-website-id]")` to `m = v.querySelector("script[src*='umami']")`
2. `w = g("data-website-id")` to `w = "WEBSITE_ID"`
3. `y = g("data-host-url")` to `y = "HOST_URL"`

Hope this helps anyone running into the same issue.

Maybe you could make it more easily usable for browser extensions in the future :)

**Comment by mikecao** [comment]
Not sure what a browser extension would be for, but moving this to discussions since it's not an issue.
