### ISSUE TITLE
I don't know where I get the `websiteId` or srcUrl?

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [mikecao/umami#836]
I am using the gatsby plugin `gatsby-plugin-umami`

```
  {
    resolve: `gatsby-plugin-umami`,
    options: {
      websiteId: 'UMAMI_WEBSITE_ID',
      srcUrl: 'https://umami.example.com/umami.js',
      includeInDevelopment: false,
      autoTrack: true,
      respectDoNotTrack: true
    },
  },
```
what should I do to get the websiteId?
and also from I will bring the srcUrl?
I followed along with [this tutorial](https://dev.to/jakobbouchard/setting-up-umami-with-vercel-and-supabase-3a73?signin=true)  using Vercel and superbase..

**Comment by marcelreppi** [comment]
You first need to deploy Umami [somewhere](https://umami.is/docs/hosting) (Vercel, Heroku etc.), then [login](https://umami.is/docs/login) and then [create a website](https://umami.is/docs/add-a-website). You will then find the `websiteId` and `srcUrl` when you look at the [tracker code](https://umami.is/docs/collect-data).

**Comment by WatheqAlshowaiter** [comment]
Thanks, @marcelreppi , I have solved the issue.
