### ISSUE TITLE
Hitting Refresh on Custom Range would cause an error and the button is stuck at loading.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [mikecao/umami#840]
Hey,
While I was going through the code for custom date filter, I found that the refresh for custom is not handled in `RefreshButton.js`.
Hitting refresh on custom would make the resfresh button stuck at loading and cause an error.
Steps to reproduce:
1. Go here - https://app.umami.is/share/8rmHaheU/umami.is
2. Select any custom date range, doesn't matter "Single day" or "Date Range"
3. Hit the refresh button.

The button is stuck at loading and errors can be seen in the console.

**Comment by mikecao** [comment]
Confirmed, thanks
