### ISSUE TITLE
View details throws unexpected error

### ISSUE THREAD

**Issue by JojiiOfficial** [mikecao/umami#848]
Under /website/_website-id_/_website_ I get an _Unexpected error has occurred_ 

It worked until yesterday and I haven't changed anything. The dashboard works fine.
![ao](https://user-images.githubusercontent.com/15957865/142241915-7ca89812-85c6-4552-bbb1-2319feb12610.png)

**Comment by mikecao** [comment]
It looks like it's failing to render some bad characters. Will need to know what those are first. More info here, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI

**Comment by JojiiOfficial** [comment]
How should I approach to figure that out? There is a lot of data being sent to the frontend and the js is minified so its impossible to read it or hack on it. That site contains a lot of Japanese text and its now the second time that this has happened. After one day I can access this site again.
