### ISSUE TITLE
Deprecate shipping custom fonts in favor of system font stacks.

### ISSUE THREAD

**Issue by codyogden** [mikecao/umami#850]
In `v1.18.0`, umami began using `@fontsource` to ship and serve local font files to avoid the Google's CDN. [I'm no fan of Google](https://github.com/codyogden/killedbygoogle), obviously, but I've been [struggling with issues deploying](https://github.com/mikecao/umami/discussions/746) to production with the Dockerfile--specifically causing working memory exhaustion during the build process. I was reviewing dependencies and realized that the four `@fontsource` dependencies nearly double the size of the production `node_modules` folder.

For instance, (on local) `yarn install --production --frozen-lockfile` with the four `@fontsource/*` packages is 514.3MB (the image is over 600MB when node, etc is added). Removing those four dependencies, the same install becomes 283.5MB locally. Specifically, the Noto Sans Simplified Chinese, Noto Sans Japanese, and Noto Sans Traditional Chinese ship a large set of font files that are held in memory during multiple `COPY` events in the build process.

I believe there's a couple ways to avoid shipping hefty font files:

### i18n System Font Stacks
It seems feasible that umami could assign variable [system font stack](https://css-tricks.com/snippets/css/system-font-stack/) that target current and future i18n requirements languages. There are [system font stacks](https://readium.org/readium-css/docs/CSS09-default_fonts.html) for various languages used in other projects. I'm not personally knowledgeable enough in i18n to know if these font stacks could work as a replacement for the custom fonts?

### Use Handpick
Another option would be to integrate [handpick](https://github.com/redaxmedia/handpick) which could make the font dependencies optional and allow us to opt-in/target them to be installed during the build. but we'd still need a default system font stack to be implemented as a fallback.

### Another solution?
There might be another solution I'm not seeing.

**Comment by mikecao** [comment]
This is a good idea. Managing @fontsource dependencies is a pain as well.
