### ISSUE TITLE
First login generates Error

### ISSUE THREAD

**Issue by ddeimeke** [mikecao/umami#86]
I just installed Umami from a Git clone. Database MariaDB 10.3.24, node 10.19.0, npm 6.13.4. All went well.

Upon first login I get the following error message.

```
$ npm start

> umami@0.20.0 start /home/umami/umami.git
> next start

info  - Loaded env from /home/umami/umami.git/.env
ready - started server on http://localhost:3000
{ JWEInvalid: could not resolve a usable "alg" for a recipient
    at Encrypt.[PROCESS_RECIPIENT] (/home/umami/umami.git/node_modules/jose/lib/jwe/encrypt.js:100:15)
    at Encrypt.encrypt (/home/umami/umami.git/node_modules/jose/lib/jwe/encrypt.js:170:30)
    at single (/home/umami/umami.git/node_modules/jose/lib/jwe/index.js:8:6)
    at createSecureToken (/home/umami/umami.git/.next/server/pages/api/auth/verify.js:1367:51) name: 'JWEInvalid', code: 'ERR_JWE_INVALID' }
```

**Comment by ddeimeke** [comment]
I already am on the latest version available in the software collections of CentOS, which is - by the way - the same version available on the recent version of Ubuntu (20.04).

**Comment by mikecao** [comment]
I wonder if this has anything to do with it, https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm_options

`
The algorithm is dependent on the available algorithms supported by the version of OpenSSL on the platform. Examples are 'sha256', 'sha512', etc. On recent releases of OpenSSL, openssl list -digest-algorithms (openssl list-message-digest-algorithms for older versions of OpenSSL) will display the available digest algorithms.
`
Specifically, umami is trying to create a `sha512` hash using the `crypto` module from node.

**Comment by ddeimeke** [comment]
In my opinion this looks good.

```
$ openssl list-message-digest-algorithms | grep -i sha512
RSA-SHA512 => SHA512
SHA512
SHA512
sha512WithRSAEncryption => SHA512
```

**Comment by ddeimeke** [comment]
I go with the Docker container for now.

**Comment by mikecao** [comment]
Closing for now since this could be an external issue. Re-open if needed.
