### ISSUE TITLE
v1.24.1 build fails on FreeBSD - workaround

### ISSUE THREAD

**Issue by wgmyers** [mikecao/umami#863]
Ran into issue #856 with v1.24.0, but v.1.24.1 build fails on FreeBSD also.

This is because next.js now by default uses SWC, which does not currently provide a FreeBSD binary.

See: https://nextjs.org/docs/messages/failed-loading-swc

I tried to build SWC locally, but that failed too - the SWC build eventually finished (after 15 minutes!) but only to create a binary that dumps core.

The workaround I found was to disable SWC, as per the link above, by creating a `.babelrc` file in the root dir of your umami repo containing the following:

```
{
  "presets": ["next/babel"]
}
```

You may need to blow the whole of `node_modules` away and reinstall. I did. After that, umami 1.24.1 installs and runs fine.

**Comment by chibiribiri** [comment]
Same goes for CentOS.
