### ISSUE TITLE
Feature request: select which weekday should the week start with

### ISSUE THREAD

**Issue by tairosonloa** [mikecao/umami#866]
When selecting a custom time range in whatever metric, a calendar view is opened to pick the desired range. However, weeks start on Sunday, but I would like to have an option in the profile config to make weeks start on Monday, just as you can set your timezone.

Weeks starting on Sunday is something weird if you are not from USA ;)

PS. I would love to contribute with this feature, but I have no time for it in the following two months. I'm opening the issue for everyone who want to achieve this in the meantime. If it's still open by February, I think I'll try to implement it by myself.

**Comment by mikecao** [comment]
The display of date and time is dependent on the locale. If you want the week to start on Monday, switch to the `English (UK)` locale.
