### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by mihha** [mikecao/umami#88]
Hi,

I was using verion 0.17.0 until now

Today I stopped my instance and did the following:
`git pull`

Is this enough to update my verison to the latest one?

I am not sure which version of umami I have now when I start it again

**Comment by mikecao** [comment]
The proper way to update is to pull, install any new dependencies, and rebuild

```
git pull
npm install
npm run build
```

**Comment by saiftheboss7** [comment]
Could you add a notification inside so whenever there's a new version - we know from the dashboard inside that there's a new version



________________________________

**Comment by axelekwall** [comment]
I created a PR to add a new page to the docs with instructions on how to update. I can also look into the suggestion from @saiftheboss7 if you think that's a good idea @mikecao?

**Comment by saiftheboss7** [comment]
It'd be awesome if it could be fully automated like WordPress. Click and update. :D (if that's possible)

**Comment by mikecao** [comment]
@axelekwall @saiftheboss7 I don't like idea having a notification inside the app. It should be a stand-alone app without external dependencies.

I am working on an umami-cli that will make installation and updates easier.

**Comment by mikecao** [comment]
Closing as answered.
