### ISSUE TITLE
Fails on Vercel (using PlanetScale/MySQL) 

### ISSUE THREAD

**Issue by danaugrs** [mikecao/umami#880]
First, thanks @mikecao for making Umami! It's awesome!

I'm having an issue when deploying to Vercel.
Here's the error I get after trying to login:

```
ERROR	PrismaClientInitializationError3 [PrismaClientInitializationError]: Can't reach database server at `<host_redacted>`:`3306`Please make sure your database server is running at `<host_redacted>`:`3306`. 
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36380:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/auth/login.js:115:21)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1017:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:904:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:210:32)
    at async Server.run (/var/task/node_modules/next/dist/server/next-server.js:1088:29)
    at async Server.handleRequest (/var/task/node_modules/next/dist/server/next-server.js:304:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9) {  clientVersion: '2.29.1',  errorCode: undefined}
```
Here's the weird part - the same database connection works when running the client locally.
Increasing the Prisma `connect_timeout` in `DATABASE_URL` didn't work.

Observation: I'm using PlanetScale (https://planetscale.com) and therefore:
1) had to remove foreign key constraints from the schema.
2) needed to add `?sslcert=ca-certificates.crt` to `DATABASE_URL` (where `ca-certificates.crt` is in `./prisma`).

I have no idea why it works locally (with remote db) but not on Vercel.
I know this is not an issue with Umami itself, but hoping someone can help, and that when resolved this can help others!

**Comment by danaugrs** [comment]
The problem happens because the file `ca-certificates.crt` doesn't exist in the environment of the deployed cloud functions.
It's working after following the solution in this comment: https://github.com/prisma/prisma/issues/1673#issuecomment-647107891

**Comment by mmaaaaz** [comment]
Hi, can you please guide me how can I setup umami with planetscale?

I have tried multiple times with no success.

**Comment by T4533N** [comment]
Would love it if you could make a guide about how you solved it @danaugrs. 👍🏻

**Comment by mikecao** [comment]
@danaugrs Feel free to add a guide to the website, https://github.com/mikecao/umami.is

**Comment by culee** [comment]
Hi, here is my workaround to make it work with `PlanetScale`. Hope it helps.

- Clone the `umami` repo to local
- Create `.env` file
- Add `DATABASE_URL` and `HASH_SALT` value into `.env` (like the documentation told)
- Update `schema.mysql.prisma` (see [why](https://github.com/prisma/prisma/issues/7292))
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}
```
- Add `seed` to `package.json`
```
"prisma": {
  "seed": "node prisma/seed.js"
},
```
- Run `npx prisma db push --schema=./prisma/schema.mysql.prisma` to sync schema
- Run `npx prisma db seed` to push default data to `PlanetScale`
- Verify if data is seeded `npx prisma studio --schema=./prisma/schema.mysql.prisma`
- Done

**Comment by danaugrs** [comment]
Hey @mikecao and everyone, I just setup a fresh Umami instance with PlanetScale + Vercel and created a guide.
Here's the PR: https://github.com/mikecao/umami.is/pull/51

These are the instructions for PlanetScale:

1. Fork the [https://github.com/mikecao/umami](https://github.com/mikecao/umami) project to your GitHub account.
2. Create a database on PlanetScale called `umami-db` and get its connection string (Hint: select "Prisma" from the "Connect with" menu). It should look something like this: `mysql://username:password@host/umami-db?sslaccept=strict`
3. Add `DATABASE_URL` and `HASH_SALT` (any random string) to you `.env` file:
```
DATABASE_URL=mysql://username:password@host/umami-db?sslaccept=strict
HASH_SALT=any-random-string
```
4. Open `schema.mysql.sql` and delete all lines starting with `foreign key` and make sure to delete the dangling commas.
5. Download the [PlanetScale CLI](https://github.com/planetscale/cli/releases) and authenticate with `pscale auth login`.
6. Create the tables by running the following command on the root of the project: `pscale shell umami-db main < sql/schema.mysql.sql`.
7. You should now be able to build and start Umami (`npm run build` followed by `npm start`).
6. Follow the **Getting started** guide starting from the [Login](/docs/login) step and be sure to change the default password.

Notes:

* I did not have to modify `schema.mysql.prisma` (as suggested by @culee above) to get things to work, but it might be beneficial.
* The original problem I encountered when deploying to Vercel (with PlanetScale) didn't manifest itself, and the corresponding solution I previously used (https://github.com/prisma/prisma/issues/1673#issuecomment-647107891) was unnecessary.

Hope this helps!

**Comment by grepsci** [comment]
@danaugrs thanks for updating the `running on planetscale` doc, but when I tried to follow line for line, it doesn't work out of the box.

I followed @culee 's post with initial suggestions and it was reaffirmed in [planetscale's prisma documentation](https://docs.planetscale.com/tutorials/automatic-prisma-migrations#execute-your-first-prisma-db-push)

By updating a couple lines in `schema.prisma`, you don't have to touch any `foreign key` lines in `sql/schema.mysql.sql`

The original project leverages yarn and although there is no `package-lock.json` i reinstalled `yarn` just to make sure i had the same dependencies via `yarn.lock` as the main repo.

After running `yarn build`, planetscale db needs to be updated and one could run `npx prisma db push`

[why prisma db push?](https://docs.planetscale.com/tutorials/automatic-prisma-migrations#quick-introduction-to-prisma's-db-push)

Then you can run `yarn start` to view your local instance

Happy to update the guide to reflect this or defer to @danaugrs as the original author
