### ISSUE TITLE
Umami emits "Uncaught TypeError: t.className.split is not a function" exceptions for every click action in svelte-kit app

### ISSUE THREAD

**Issue by np-nam** [mikecao/umami#884]
I think the issue is pretty easy to resolve, but anyone knows the real cause for it?

**Comment by mikecao** [comment]
This is likely the event capturing code. Not sure why but it looks like `t` is undefined.

**Comment by np-nam** [comment]
@mikecao t comes from this line: https://github.com/mikecao/umami/blob/master/tracker/index.js#L112

you can ease fix the error by replace `element.className.split(' ')` with `element.classList`, but I'm not still not sure why className doesn't not exist. isn't it supposed to be a default attribute of a dom element?

**Comment by saschwarz** [comment]
FWIW - I see this on every page transition in one of my angular apps; I'm not using any events explicitly. I don't recall seeing it when I first started using umami.

**Comment by JeDaYoshi** [comment]
@saschwarz - I mainly tried my commit on a Nuxt.js SPA and it tracked views correctly, so the issue doesn't persist on that.
And in fact, my changes from back then could have not affected this; or at least not the same way, since the tracker used `element.className.split(' ')` prior to that.

I can try taking a look about why is this happening, since I'm curious as of why className is not defined.

**Comment by JeDaYoshi** [comment]
@saschwarz thanks for the information! Something I forgot testing was SVG elements, which might work differently. I have a better idea of what to tackle now, I'll look into a proper solution for that then :)

**Comment by evilfer** [comment]
Hi,

We have updated to v1.25.0 (using docker image `ghcr.io/mikecao/umami:postgresql-latest`), but we are still seeing the problem, at least in the console:

![image](https://user-images.githubusercontent.com/2108433/150548542-8361a7a2-8bb2-4cea-a336-ade6c5e3657f.png)

Page views seem to be tracked, so I'm not sure what's the impact of these errors.

**Comment by mikecao** [comment]
@evilfer Can you check to see what that object `t` is in the debugger? There is already a check to determine if `className` is defined, but I guess we need to update to make sure it's a string.

**Comment by saschwarz** [comment]
@mikecao FWIW in my case (above), `t` is an SVG `g` element and `t.className` returns an `SVGAnimatedString` instance.

**Comment by np-nam** [comment]
can we just use classList instead?
