### ISSUE TITLE
MySQL connect to MAMP

### ISSUE THREAD

**Issue by BasJan81** [mikecao/umami#886]
Hi,

Receiving **Internal Server Error** when trying to (first) login with admin & umami. 

Using MAMP to handle MySQL so I guess I need my socket.

`
DATABASE_URL=mysql://root:root@localhost:8889/myDatabase?unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock
`

**Comment by mikecao** [comment]
what does the error say?

**Comment by mdestafadilah** [comment]
> Hi,
> 
> Receiving **Internal Server Error** when trying to (first) login with admin & umami.
> 
> Using MAMP to handle MySQL so I guess I need my socket.
> 
> `DATABASE_URL=mysql://root:root@localhost:8889/myDatabase?unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock`

it's your password wrong.
