### ISSUE TITLE
Compatible with react native?

### ISSUE THREAD

**Issue by 10000multiplier** [mikecao/umami#887]
Would it be possible to integrate umami with react native, for use on mobile apps?

**Comment by mikecao** [comment]
The UI can already be accessed on mobile. If you're asking if there's going to be a react native port, it's very unlikely.

**Comment by 10000multiplier** [comment]
Ah it was a hail mary anyway. Just want to sincerely thank you for creating this amazing open source software. I know it can be a thankless job.

**Comment by ThatOneCalculator** [comment]
Would this ever be reconsidered? Being able to use Umami to get analytics on both a website and mobile app would be very useful.

**Comment by sybers** [comment]
Maybe there was a misunderstanding regarding the initial request. I guess the author was asking if it was possible to get analytics about mobile app users, not if the Umami dashboard was usable on a mobile device :)

**Comment by tan-ahmed** [comment]
bump

**Comment by partytoni** [comment]
Bump 2

**Comment by mikecao** [comment]
You simply need to send a HTTP request in order to track stats. You can easily do that on mobile.

**Comment by ThatOneCalculator** [comment]
But won't that fail due to the origin of the mobile app not being the website's url?

**Comment by MohammadAzimi** [comment]
The exact issue is that we don't know which HTTP request is sent and when. I mean for example when the visit is called. Should I store any id's like session id or... any logic that is implemented in the web script

**Comment by ramazansancar** [comment]
Same issue

**Comment by YaserKhangoli** [comment]
I’ve recently published a React Native library for integrating Umami Analytics.  
It’s designed to be lightweight and easy to use.  
Feedback is very welcome.
:boom:  https://www.npmjs.com/package/react-native-umami-sdk
https://github.com/YaserKhangoli/react-native-umami

**Comment by amitsamanta996** [comment]
> I’ve recently published a React Native library for integrating Umami Analytics. It’s designed to be lightweight and easy to use. Feedback is very welcome. 💥 https://www.npmjs.com/package/react-native-umami-sdk https://github.com/YaserKhangoli/react-native-umami

This package is not working. Nothing is reflected in the dashboard
