### ISSUE TITLE
Having issues importing mysql

### ISSUE THREAD

**Issue by Dinip** [mikecao/umami#9]
Hi,

Having some issues importing mysql schema:
`root@ubuntu:/opt/analytics# mysql -u analytics -p analytics < sql/schema.mysql.sql`
`Enter password: `
`ERROR 1064 (42000) at line 79: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 9`
![image](https://user-images.githubusercontent.com/8941012/90569288-81196500-e1a5-11ea-9a39-b0001abb049e.png)
Mysql version 8.0

**Comment by mikecao** [comment]
I just fixed the script. Try pulling the latest version.

**Comment by IAmStoxe** [comment]
So glad I checked the issues and you JUST happened to just update <3. I had the same problem and was banging my head against the wall the last 30. Confirmed it's gone now :) 👍  for speedy assistance!

 
![image](https://user-images.githubusercontent.com/16467875/90573178-a0df6780-e16a-11ea-8981-386eaa73707a.png)

**Comment by Dinip** [comment]
seems fixed!
