### ISSUE TITLE
Cannot POST /api/auth/login

### ISSUE THREAD

**Issue by Georg-code** [mikecao/umami#900]
Hello, I'm using Umami on a path (/webstats) and I can't log in because of this error
`<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot POST /api/auth/login</pre> </body> </html> `

I have configured the `BASE_PATH=/webstats `

and my Nginx config looks like this:
`     location /webstats {
          proxy_pass http://localhost:3000;
          proxy_redirect http://localhost:3000/ /;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
`

I don't know if I'm doing something wrong. Thanks for your help!

**Comment by Samuel-5485** [comment]
hello @Georg-code how are you.
the error you see <pre>Cannot Post /api/auth/login</pre> go head & check your code that you call post
such like this `app.post("auth/login")`. be sure that you import the code in you are file  such like this `const  loginroute = require("../routes/login". in addition check if there is other port is open in your server on the command prompt write this 
`sudo lsof -i:<Your PORT>` if there is other port is open kill it sudo kill -9 <the port you want to kill>
by doing this your error may no appear!!!
thanks! keep it up.

**Comment by Samuel-5485** [comment]
hello @Georg-code how are you.
the error you see <pre>Cannot Post /api/auth/login</pre> go head & check your code that you call post
such like this `app.post("auth/login")`. be sure that you import the code in you are file  such like this `const  loginroute = require("../routes/login". in addition check if there is other port is open in your server on the command prompt write this 
`sudo lsof -i:<Your PORT>` if there is other port is open kill it sudo kill -9 <the port you want to kill>
by doing this your error may no appear!!!
thanks! keep it up.
