### ISSUE TITLE
Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by louis-l** [mikecao/umami#912]
Hi there,

I use Sentry to track errors and have been receiving these errors quite often recently: 
**Object doesn't support property or method 'forEach'** 

It happens on:
- window OS
- IE 11

![Screen Shot 2022-01-13 at 11 12 12 am](https://user-images.githubusercontent.com/10172565/149243015-92cb1123-86de-4ea6-9b54-0b96f386fc0b.png)

Above is the report from Sentry. Its maybe happening on other browsers as well.

Presumably just missing a polyfill?

**Comment by mikecao** [comment]
I think this may be the solution, https://stackoverflow.com/questions/45260298/queryselectorall-method-is-not-supported-with-ie11-in-standards-mode

**Comment by louis-l** [comment]
Thanks @mikecao 

Are you suggesting:
1. JS approach https://stackoverflow.com/a/59300110/5324881
1. or HTML approach https://stackoverflow.com/a/45260313/5324881

I dont have IE to test it, so will take whatever you suggest 👍

**Comment by mikecao** [comment]
We should fix the tracker using the JS approach. We can't guarantee that a page will have the proper meta tags.

**Comment by louis-l** [comment]
Cool, let me know if you want to PR for this.
