### ISSUE TITLE
Fail to update

### ISSUE THREAD

**Issue by TerryHoCQ** [mikecao/umami#919]
Hello, fail to update to 1.25, please help to check, thanks
![Clipboard02](https://user-images.githubusercontent.com/72144546/149943933-047db119-8238-4c27-a73c-c4e034c34f9a.png)
!

**Comment by mikecao** [comment]
Try installing the library
```
apt-get install musl-dev
```
And then
```
ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
```
