### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by vinicius-camara** [mikecao/umami#92]
Is it possible add support to i18N?

**Comment by mikecao** [comment]
I've got i18N working on the `dev` branch right now. If anyone wants to provide translations it'd be greatly appreciated. Just copy the `lang/en.json` file and translate all the `defaultMessage` strings and save as a new file with locale code like `fr.json` or `es.json`.

**Comment by mikecao** [comment]
`dev` branch has been merged into `master`. There is a file called `lib/lang.js` that defines all the supported languages and function. You will need to update it if you are doing local development. Otherwise you can just provide an updated `lang/[id].json` file and I can update for you.

**Comment by err931** [comment]
Nice work! :tada:

Which branch should I submit to a pull request if I want to add a new language file?

Also, should the locale ID comply with [RFC 3282](https://tools.ietf.org/html/rfc3282)?

(e.g. `ja`, `en-au`, `zh-tw`)

**Comment by err931** [comment]
Nice work! :tada:

Which branch should I submit to a pull request if I want to add a new language file?

Also, should the locale ID comply with [BCP47](https://tools.ietf.org/html/bcp47)?

(e.g. `ja`, `en-au`, `zh-tw`)

**Comment by mikecao** [comment]
@err931 Yes please use the BCP47 code. You can either submit to dev or master. I'll make sure it's merged either way.

**Comment by ym-project** [comment]
I noticed one thing. On the page [https://app.umami.is/share/8rmHaheU/umami.is](https://app.umami.is/share/8rmHaheU/umami.is) you can see different metrics such as: browsers, devices, etc. All metrics are plural except "operating-system".
https://github.com/mikecao/umami/blob/master/lang/en.json#L173-L175

Is it a bug?
