### ISSUE TITLE
Custom date selection not registered by dashboard (v1.25.0)

### ISSUE THREAD

**Issue by spcanelon** [mikecao/umami#923]
Hello! 👋🏽  And thanks for Umami! 🤩 

I updated to v1.25.0 today with no issue, but I noticed that I could not use the Custom Date feature like I used to be able to. Selecting a single date or a date range using the calendar (see screenshot) and saving does not update the dashboard.

I'm using Railway to host my database and deploy Umami. Please let me know if there's any additional information I can provide. Thanks!

----

Selecting a date range of January 9, 2022 to January 10, 2022:

![image](https://user-images.githubusercontent.com/49913337/150055070-32990ed4-b029-4368-b5f1-2857f08febde.png)

**Comment by mikecao** [comment]
I probably introduced a bug 🤦‍♂️. I'll look into it.
