### ISSUE TITLE
Prepared statement already exists.

### ISSUE THREAD

**Issue by riccardodivirgilio** [mikecao/umami#927]
Hello I'm trying to setup umami for my website.

I have been using docker image **ghcr.io/mikecao/umami:postgresql-latest**, I'm using a managed database instance from DigitalOcean, and I'm connecting using a managed session pool. 
After a couple of restarts (I needed to delete the image from Kubernetes after I changed some environment variables) all internal pages are blank (attaching screenshot), because some requests are returning a 500 error.

<img width="1322" alt="Screenshot 2022-01-20 at 12 01 09" src="https://user-images.githubusercontent.com/187641/150326435-459d5939-eb86-4982-815d-6b1bff7dc9c9.png">

When asking for logs from the docker container I got this:

```
PrismaClientUnknownRequestError: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s3\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(477), routine: Some("StorePreparedStatement") }) }) })
    at cb (/app/node_modules/@prisma/client/runtime/index.js:38687:17) {
  clientVersion: '3.6.0'
}
```

**Comment by mikecao** [comment]
This might be an issue with DigitalOcean's managed session pool. Can you try disabling it and trying again?

**Comment by riccardodivirgilio** [comment]
It seems that my connection pool was not big enough to accomodate prisma connection pool, which is using on my machine 9 connections. How do I tweaks the number of connections that prisma is using? I can't find it in the docs.
Thanks!

**Comment by sumul** [comment]
This may be related to https://github.com/prisma/prisma/issues/11643. 

I ran into a similar issue hosting my PostgreSQL database on supabase. In case anyone else ends up here, here's the solution that worked for me: 

**Solution: add `?pgbouncer=true` to your DATABASE_URL environment variable.** 

It should end up looking like this:

`postgres://postgres:[YOUR-PASSWORD]@[host].supabase.co:6543/postgres?pgbouncer=true`
