### ISSUE TITLE
Feature-Request: URL-Schema

### ISSUE THREAD

**Issue by ddeimeke** [mikecao/umami#93]
The blog software I use, uses only an index.php with the page/article names behind a question mark.

Take a look at the following examples:

- https://www.deimeke.net/dirk/blog/index.php?/archives/4023-Linkdump-352020.html
- https://www.deimeke.net/dirk/blog/index.php?/pages/about_me.html

Umami shows only the index.php and not the informations behind that.

Please allow statistics for pages following an URL-schema ("like 'index.php?/.*.html')

**Comment by mikecao** [comment]
Ok, I can make it so `?/` is recognized as a page in the combined filter. In the meantime, you can click `More` and filter by `Raw` which will show you all the URLs.

**Comment by ddeimeke** [comment]
@mikecao This would be perfect for me. Thanks for the hint to use "More" :-)

**Comment by ddeimeke** [comment]
Thanks a lot @mikecao, that works perfectly well.
