### ISSUE TITLE
schema

### ISSUE THREAD

**Issue by PatelN123** [mikecao/umami#937]
Hi, 

When building with vercel, I get the error:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/79650289/151120492-6a93acf0-1751-48a6-a00c-7b621f8cc7c4.png">

It does not stop me from building, however it is quite annoying and I'd like to know if this affects the build?

**Comment by mikecao** [comment]
It doesn't affect the build. It's just a post install script run by prisma that tries to generate the schema. But umami does it in a separate step.
