### ISSUE TITLE
[Question] Can I host the tracking script on a CDN?

### ISSUE THREAD

**Issue by dakshshah96** [mikecao/umami#95]
Instead of including the script directly from the server i.e., `https://myserver.com/umami.js`, is it possible to replicate this script and host it on a CDN (like S3+CloudFront) for faster load times?

Will the tracking script still work if I do that?

**Comment by mikecao** [comment]
Yes, the tracking script can be hosted anywhere. Just add a `data-host-url` attribute pointing to where your umami is hosted.

**Comment by dakshshah96** [comment]
Thanks, but did you mean `data-website-id`?

If not, can you please give an example for what it'd look like?

**Comment by mikecao** [comment]
By setting data-host-url attribute in the umami tracker, you can tell umami where to make the API calls. For instance to
a subfolder or another domain.

```html
<script async defer 
  data-website-id="83dd64c4-17ad-4e3e-a905-b3d8c867c1a5"
  src="http://mywebsite.com/umami.js"
  data-host-url="http://umami.mywebsite.com">
</script>
```

This feature  was just released. I will update the docs soon.

**Comment by dakshshah96** [comment]
Got it, thanks a lot!
