### ISSUE TITLE
Can I display Browser and OS Versions?

### ISSUE THREAD

**Issue by ericmackrodt** [mikecao/umami#951]
Hi, I have installed umami on my server to monitor my personal websites. I love how simple it is so far.
I'm just wondering if it would be possible to display the OS and Browser versions.
The reason I ask that is because both my websites are built to run on very old browsers and I want to be able to see what versions of Internet Explorer the user is using as well as what versions of Windows (95, 98, ME, XP and so on).

Thanks in advance.

**Comment by suciptoid** [comment]
Yes you can, on demo page: https://app.umami.is/share/8rmHaheU/umami.is?view=browser
<img width="1159" alt="Screen Shot 2022-02-09 at 16 29 46" src="https://user-images.githubusercontent.com/1310895/153166225-589492e0-d8d3-4006-a914-94295a19b5db.png">

**Comment by ericmackrodt** [comment]
@suciptoid Hi, thanks for getting back to me.
If I'm not mistaken, those are not the versions, they are the number of visitors.

**Comment by suciptoid** [comment]
@ericmackrodt oh sorry. After reading the source code (https://github.com/mikecao/umami/blob/master/lib/request.js#L79-L88), only browser name is recorded.

**Comment by bjoe2k4** [comment]
I'd be interested in seeing browser versions here, too.

**Comment by mikecao** [comment]
umami uses this package for detection, https://www.npmjs.com/package/detect-browser
You can modify the source pretty easily to include the browser version, but honestly these days version number doesn't matter as much with browsers constantly updating.
