### ISSUE TITLE
Countries Data is always Unknown

### ISSUE THREAD

**Issue by HaruMiyaGi** [mikecao/umami#952]
I have umami v1.25.0 running on EC2 instance with pm2 and nginx, connected to RDS database, the tracking script is attached to a nextjs app hosted with Vercel.

Everything works fine except all my visitors countries are detected as unknown.

How should I proceed to fix / debug this issue?

**Comment by HaruMiyaGi** [comment]
This was the solution: https://github.com/mikecao/umami/issues/501#issuecomment-837512468

**Comment by cjxe** [comment]
@HaruMiyaGi do you still use this setup? What do you think of it?
