### ISSUE TITLE
[feature request] allow customizing `umami.js` script's filename

### ISSUE THREAD

**Issue by kiprasmel** [mikecao/umami#953]
umami is blocked by e.g. ublock-origin. ublock uses e.g. lists, and `/umami.js` is already included there.

setting a custom filename would allow to avoid this. it doesn't feel wrong either because we are self-hosted & do not track.

not sure if this would make sense to allow configuring the same filename for the whole app (all websites), or perhaps better would be allowing to configure on each website?

thanks!

**Comment by Code-Jonny** [comment]
The easiest to do is use an alias for the file on the web server, e.g. with .htaccess in apache. You can then just leave the file's original name which should be better for updating reasons. And in your web code you can point to that alias name avoiding blocklists.

**Comment by Vultik** [comment]
> The easiest to do is use an alias for the file on the web server, e.g. with .htaccess in apache. You can then just leave the file's original name which should be better for updating reasons. And in your web code you can point to that alias name avoiding blocklists.

Good idea !
How can it be done on Heroku ?

**Comment by di-dc** [comment]
Unless I'm mistaken, changing the name of the script (umami.js) won't get you past uBlock Origin -- it looks like the EasyPrivacy list includes a rule for "://analytics.*/collect", which blocks the api call that the script (whatever you name it) makes to the path _/api/collect_.

**Comment by sparanoid** [comment]
@di-dc If you're using Nginx with Umami there's a workaround:

```nginx
  location = /app.js {
    proxy_pass http://umami:3000/umami.js;

    proxy_set_header Accept-Encoding "";

    sub_filter '/api/collect' '/api/my-good-script';
    sub_filter_types *;
  }

  location = /api/my-good-script {
    proxy_pass http://umami:3000/api/collect;
  }
```

**Comment by AliMickey** [comment]
Is the custom nginx path still the recommended way to go?

Or will there be a noscript alternative (eg. shynet) to bypass this.

**Comment by mikecao** [comment]
@AliMickey umami can do this internally, use the environment variable `TRACKER_SCRIPT_NAME`.

**Comment by AliMickey** [comment]
> 

Yeah but the POST endpoint is still blocked.

**Comment by rohandebsarkar** [comment]
Possible solution: #1026
