### ISSUE TITLE
Use Umami with chatbots (telegram, viber)

### ISSUE THREAD

**Issue by Hassan-Mallah** [mikecao/umami#954]
Hey,

Thank you for the nice service :)

Is it possible to use Umami api events for chatbots analytics (e.g telegram bots)? or it's best used for websites, visits and clicks?

I tried with python and our chatbot platform (https://just-ai.com/en/) but no luck.

Cheers

**Comment by mikecao** [comment]
Sure, you can send whatever events you want. Though it was built mainly to track websites.

**Comment by Hassan-Mallah** [comment]
> Sure, you can send whatever events you want. Though it was built mainly to track websites.

Thank you for your reply :)
We also found a way. cheers
