### ISSUE TITLE
Realtime Mobile View

### ISSUE THREAD

**Issue by nfn** [mikecao/umami#959]
Hi

When on my mobile viewing Realtime Stats, the Country visitors is out of the page;

https://i.ibb.co/3NHjpy5/Screenshot-20220214-195003-2.jpg

https://i.ibb.co/zHwz1TT/Screenshot-20220214-195010-2.jpg

Thanks

**Comment by mikecao** [comment]
What phone are you using? It should scroll instead of push the screen like that.

**Comment by nfn** [comment]
Hi,

I tested with OnePlus 8T and iPhone 12 with the same behavior.

Note, this only occur in the Real Time view. In the dashboard works correctly, scrolling insira a frame o something similar.

Thanks

**Comment by thomasbnt** [comment]
Can reproduce that on **Xiaomi Redmi Note 10S**

**Comment by mathieulesniak** [comment]
Also can reproduce it on an iPhone 11. Only in realtime, no problem on regular dashboard
