### ISSUE TITLE
Doesn't work with postgres:// only postgresql://

### ISSUE THREAD

**Issue by Paxa** [mikecao/umami#97]
Could be nice to support both

**Comment by mikecao** [comment]
That is a limitation of the Prisma which requires `postgresql`.  https://www.prisma.io/docs/reference/database-connectors/connection-urls#overview. You can still set the `DATABASE_TYPE` env variable to tell umami what database you're really using.

But now that I think about it, maybe there's something we can do on the app side to translate `postgres` to `postgresql`. It just need to work well with Prisma. I'll explore it a bit.

**Comment by Paxa** [comment]
Ok, understandable

I guess it can bee achieved with something like this at beginning of main file

```js
if (process.env.DATABASE_URL && process.env.DATABASE_URL.startsWith("postgres://")) {
  process.env.DATABASE_URL = process.env.DATABASE_URL.replace(/^postgres:/, "postgresql:");
}
```
