### ISSUE TITLE
API Authorization with Cookie Header not allowed

### ISSUE THREAD

**Issue by Kamieljv** [mikecao/umami#974]
When I try authorizing for the API as described in the docs, by adding a `Cookie` header with the `umami.auth` cookie, I get the following error: `Attempt to set a forbidden header was denied: Cookie`.

I am using axios from a Vue front-end. My code looks as follows: 
```
this.$http.get('https://[my-umami-host]/api/websites', {
  withCredentials: true,
    headers: {
	    'Cookie': `umami.auth=${token}`
    }
  }).then((response) => {
    console.log(response);
  })
```
I tested the server configuration by sending a HTTP request via `curl`, passing the token. That worked fine.
What could be the problem? And is it possible to add authentication using the `Authentication` header? 

Edit: I also tried to include only the `withCredentials: true` in the axios config. This does pass along my CSRF cookie with the request, but does not include the `umami.auth` cookie.

**Comment by mikecao** [comment]
As of v1.26.0 umami uses a bearer token instead of a cookie. Just change your header to `Authorization: Bearer ${token}`. More info here, https://umami.is/docs/api.

**Comment by Kamieljv** [comment]
Great, thanks! That'll do.
