### ISSUE TITLE
Tracking SPA's

### ISSUE THREAD

**Issue by flauc** [mikecao/umami#98]
Hi @mikecao this looks really awesome, thank you! 

Is it possible to track single-page applications? Basically apps that don't refresh between page changes but use pushState for navigation?

**Comment by mikecao** [comment]
Yes, it already does.

**Comment by flauc** [comment]
Thank you for the quick response. Perhaps it should be documented somewhere I know it's more a less commonplace nowadays but still worth pointing out. 

It looks like you expose an easy method for logging custom events as well, something that would be great to document as well, but can I ask why isn't the event_type customizable as well? 

```js
window.umami = event_value => collect('event', { event_type: 'custom', event_value });
```

**Comment by mikecao** [comment]
Yes, I need to update a lot of the docs. The event type really shouldn't matter. It's only if you want to query the database directly to get all the events that you sent as `custom`.

**Comment by flauc** [comment]
Awesome, thanks.
