### ISSUE TITLE
Issue with TRACKER_SCRIPT_NAME ?

### ISSUE THREAD

**Issue by meirroth** [mikecao/umami#982]
Hi,
I noticed that the tracker script name (umami.js) is hard coded in three locations, and I am wondering if it will cause issues, if TRACKER_SCRIPT_NAME is set to something other than 'umami'?

https://github.com/mikecao/umami/blob/1e4c3ebf3b7a280f4a61cc40f2e6cc34933bf47e/.gitignore#L18
https://github.com/mikecao/umami/blob/1e4c3ebf3b7a280f4a61cc40f2e6cc34933bf47e/components/pages/TestConsole.js#L47
https://github.com/mikecao/umami/blob/1e4c3ebf3b7a280f4a61cc40f2e6cc34933bf47e/next.config.js#L27

Thanks

**Comment by mikecao** [comment]
The next release should resolve all these issues. Currently when you set a different tracker name, it builds the tracker with the new name. However, this doesn't work for pre-built docker images. The solution is to using middleware functions in the latest Next.js, that will just point your new tracker name back to `umami.js`.

**Comment by mikecao** [comment]
Fixed in v1.27.0

**Comment by meirroth** [comment]
Hi, @mikecao, v1.27.0 fixed the custom tracking code endpoint being accessible, but as I referenced in this issue above, the string "umami" is still being statically used in the UI.

Same as https://github.com/mikecao/umami/issues/972#issuecomment-1057720606

Thanks.

**Comment by mikecao** [comment]
That one is tricky because of the way Next.js handles environment variables. Technically it should still work because the middleware points to `umami.js` so both should work. I'll have to think about this a bit.

**Comment by meirroth** [comment]
@mikecao I'm not familiar with Next at all... but I experimented replacing the hard coded string in TestConsole.js and TrackingCodeForm.js with variable process.env.TRACKER_SCRIPT_NAME but I don't think it worked...
See here: https://github.com/meirroth/umami/commit/a673ccfbb1d4bf703ff8c5d23219e7a794070933
