### ISSUE TITLE
Umami throws `t.className.split` error on updating svg element

### ISSUE THREAD

**Issue by surjithctly** [mikecao/umami#986]
I have a strange issue, where umami throwing 1000s of errors while updating an SVG. 

```
umami.js:1 Uncaught TypeError: t.className.split is not a function
    at z (umami.js:1:1887)
    at umami.js:1:2094
    at Array.forEach (<anonymous>)
    at MutationObserver.C
```

See screenshot. I updated to latest version, but the issue still exists. I saw #884 is closed, but the issue is not solved yet. My `<svg>` element has two `circle` and one `text` with classes inside that. But Umami classes are not there. 

![CleanShot 2022-02-24 at 20 58 14](https://user-images.githubusercontent.com/1884712/155554819-5331d737-eecc-4401-9ca1-88dd5da2d071.gif)

**Comment by mikecao** [comment]
Did you rebuild your tracker? That piece of code `t.className.split` is not in the new tracker bundle.

**Comment by surjithctly** [comment]
Yes, sorry, it was the disk-cache. It had 30 days cookie. Updated to the latest and it fixed.
