### ISSUE TITLE
Umami is detected and blocked on a subdomain by uBlock Origin

### ISSUE THREAD

**Issue by AFilthyLeaf** [mikecao/umami#987]
I was using the one-click deploy option for umami on Heroku, then set a custom domain within Heroku. uBlock Origin detected umami despite it being mapped to a subdomain of the site with my content on it. The website says that Umami bypasses adblockers when used with a subdomain, so I'm assuming this is an issue with Heroku or I am just messing something up. 

(I selected EU server on Heroku, if that affects anything)

**Comment by RikoDEV** [comment]
uBlock detects umami from the js filename.  To get around this, just change the name from unami.js to anything else.

**Comment by di-dc** [comment]
Unless I'm mistaken, changing the name of the script (umami.js) won't get you past uBlock Origin -- it looks like the EasyPrivacy list includes a rule for "_://analytics.*/collect_", which blocks the api call that the script (whatever you name it) makes to _/api/collect_.

**Comment by GamerKingFaiz** [comment]
For anyone coming here from a Google search, Umami provides [environment variables](https://umami.is/docs/environment-variables) that you can use to get around this.

```
TRACKER_SCRIPT_NAME = <script name>
COLLECT_API_ENDPOINT = /api/x
```

See the docs I linked for more details.
