### ISSUE TITLE
Scrolling over the map partially zooms and also scrolls the page

### ISSUE THREAD

**Issue by christopherpickering** [mikecao/umami#990]
When scrolling over the map the page is also scrolling at the same time, so there is no way to zoom in. Should the map either be locked w/ no zoom, or have a different way to zoom than page scrolling?

Here's a screen video:
https://user-images.githubusercontent.com/17788706/155855101-ddd93553-b9cb-457d-bc3b-1172a4983c25.mov

**Comment by mikecao** [comment]
What OS and browser are you using? I can't seem to replicate this on Windows using Chrome.

**Comment by christopherpickering** [comment]
Thanks! I'm on the latest Mac OS Monterey and Safari 15. I think I can put a BrowserStack share: 
https://live.browserstack.com/dashboard?try_live_url=umami.is#os=OS+X&os_version=Monterey&browser=Safari&browser_version=15.1&zoom_to_fit=true&full_screen=true&url=umami.is&speed=1

**Comment by mikecao** [comment]
This seems like a Safari issue. I don't really have control over the zooming because it's a 3rd party component. I think what we can do is add some zoom buttons.

**Comment by mikecao** [comment]
Hmm, doesn't look like there is a hook to control zooming in the map component. I did find that you can double-click on the map and it will zoom and SHIFT+double-click to zoom out.

**Comment by christopherpickering** [comment]
Thanks for checking it out!
