### ISSUE TITLE
Error when updating user's default date range

### ISSUE THREAD

**Issue by MarceauKa** [mikecao/umami#994]
### Version
1.26.0

### Steps to reproduce
Updating the default date range from `Last 24 hours` to `This month` (for example) throws the following message `Application error: a client-side exception has occurred (see the browser console for more information).`

### Current fix
Clear the localStorage (via web inspector) and delete the value `umami.date-range` (`undefined`)

**Comment by H0rn0chse** [comment]
I have the same issue.

Clearing the localStorage removed the client side error but I was still unable to set the date range afterwards via the UI.
As a workaround I've set the date range manually ibn the localStorage: `"30day"`, `"1month"`, ... instead of `"24hour"`
